### ISSUE TITLE
JSX element type 'Particles' does not have any construct or call signatures.

### ISSUE THREAD

**Issue by Mayron** [tsparticles/tsparticles#1003]
**Is the latest version affected?**

- [x] Yes
- [ ] No

**Which library are you using?**

- [ ] Vanilla JS (`tsparticles`)
- [ ] React (`react-tsparticles`)
- [ ] Vue.js 2.x (`particles.vue`)
- [ ] Vue.js 3.x (`particles.vue3`)
- [ ] Angular (`ng-particles`)
- [ ] Svelte (`svelte-particles`)
- [x] Preact (`preact-particles`)
- [ ] Inferno (`inferno-particles`)
- [ ] jQuery (`jquery-particles`)

**Describe the bug**
I am using the following packages with TypeScript version `^4.0.3`:

```
"preact": "^10.5.3",
"preact-particles": "^1.18.10",
"typescript": "^4.0.3"
```

![image](https://user-images.githubusercontent.com/5854995/98361946-57454100-2024-11eb-82e2-fb3a1eb73a84.png)

It doesn't seem to like the definition:

```ts
type Particles = PureComponent<IParticlesProps, IParticlesState>;
declare const Particles: Particles;
```
Usually, I would expect to see a class rather than a const but I'm no expert. For example, if I change it to:

```ts
export default class Particles extends React.PureComponent<
  IParticlesProps,
  IParticlesProps
> {};
```
then this works. 

**To Reproduce**
1. Use `typescript": "^4.0.3` in your package.json and try to import and use Particles from `preact-particles`.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser [e.g. chrome, safari]: I use Chrome but this error is from VS Code.

**Comment by matteobruni** [comment]
Thanks for reporting that, I'm working on 1.18.11 for other fixes, I'll check out this too!

Anyway, that error should not break the component, I think.

**Comment by Mayron** [comment]
@matteobruni Damn, that was quick! Thank you :) I hope that the suggested change I included is helpful, but I didn't want to add it as a pull request because I'm no expert with definition files. Much appreciated.
