### ISSUE TITLE
Trying to create a plugin for wordpress

### ISSUE THREAD

**Issue by mister-mst** [tsparticles/tsparticles#1005]
Hello, I am trying to develop a plugin for wordpress, with this library that can be easily integrated:

It works in a very simple way, you simply have to add the particle configuration in the box that appears in the administration menu, and you have to add the CSS ID of the element where you want to show the TSParticles animation.

**The problem** occurs in the particle configuration. If I use the models that I can download from [here](https://vincentgarreau.com/particles.js/) (old library particle.js) everything works well. However if I create the configuration from the [tsparticles web](https://tsparticles.matteobruni.it) nothing works.

- This code generated with [vincentgarreau.com](vincentgarreau.com) works well: 
[config-OK.js.zip](https://github.com/matteobruni/tsparticles/files/5505157/config-OK.js.zip)

- This code generated with [sparticles.matteobruni.it](https://tsparticles.matteobruni.it) do not work: 
[particles.json.zip](https://github.com/matteobruni/tsparticles/files/5505165/particles.json.zip)

- This code extracted from a [codepen example](https://codepen.io/matteobruni/pen/mdVJBXw) created with tsparticles **works surprisingly well!:** 
[codepen.js.zip](https://github.com/matteobruni/tsparticles/files/5505181/codepen.js.zip)

I don't know what's going on, I think it would be very useful to have a plugin like this for the whole community, I hope it can be solved :)

Great job! thanks for everything!

**Comment by matteobruni** [comment]
Hi @mister-mst 

You didn't fill the issue template. I need to know what version are you using, if you are using an outdated version please update and check that the issue is still there.

I downloaded the configs but I noticed a difference between the three files, the first and the third are `js` file, the second one instead is a `json`.

The `json` file is not a script file, it must contain only an object-like structure.

All the code exported from <https://particles.matteobruni.it> have a `json` output and not javascript, and resuming my first sentence, all the config exported from the website are certified only with the latest `major`.`minor` version.

The included `tsparticles.min.js` file doesn't contain the version and it seems a lot outdated, please download the latest version from [here](https://www.jsdelivr.com/package/npm/tsparticles)

**Comment by mister-mst** [comment]
Hi!

Thanks for the quick reply, I have included in the plugin the latest version of tsparticles.min.js (1.18.10), the error keeps occurring.


The 3 configuration files should all be .json, as you can see, none include scripts, all are object-like structure.

The .js extension has not affected the tests, since in the plugin I directly insert the code by copying and pasting the content of the file in the admin panel. However, I have recreated the file for convenience:

- This code generated with [vincentgarreau.com](vincentgarreau.com) works well: [Config-OK.json.zip](https://github.com/matteobruni/tsparticles/files/5505462/Config-OK.json.zip)


- This code generated with [sparticles.matteobruni.it](https://tsparticles.matteobruni.it) do not work: [particles.json.zip](https://github.com/matteobruni/tsparticles/files/5505165/particles.json.zip)

- This code extracted from a [codepen example](https://codepen.io/matteobruni/pen/mdVJBXw) created with tsparticles **works surprisingly well!:** [codepen.json.zip](https://github.com/matteobruni/tsparticles/files/5505463/codepen.json.zip)


Thanks again!

Greetings

**Comment by matteobruni** [comment]
The json are still invalid since they contains javascript code.

Anyway if I copy just the configuration options inside a CodePen with the version `1.18.10` it works fine.

I need more details, I don't have a WordPress to test it.

**Comment by mister-mst** [comment]
If you need, please send me your email and I will send you a wordpress site where you can test the plugin.  

The plugin does not use the configuration .json files.  The plugin generates a text box where to copy the configuration, it is for this reason, why I think the file extension is not relevant in this case.

I'm not sure where the problem can come from.

**Comment by matteobruni** [comment]
You can find my email [here](https://github.com/matteobruni/tsparticles/blob/a1ace8a44bac2b6cf6562b9488d6f8c085f8c6de/core/main/package.json#L77)
