### ISSUE TITLE
[help] Adding pathseg to Vue/Gridsome project

### ISSUE THREAD

**Issue by 484-studio** [tsparticles/tsparticles#1024]
I know what I need (to add pathseg) as a node_module to my project, however, struggling to work out what's next. 
I've installed the module but when trying to import or require it in a Vue file, I get error: 'window is not defined' inside pathseg.

What is it I'm missing?

TYIA

**Comment by matteobruni** [comment]
Hi @484-studio,

`pathseg` and `tsParticles` are not SSR libraries since they are client-side only.

Try reading [here](https://gridsome.org/docs/assets-scripts/#without-ssr-support), that article explains how to add non-SSR libraries to a Gridsome project

**Comment by 484-studio** [comment]
That was much simpler than I thought - thanks so much!
