### ISSUE TITLE
Parsing Json config file in props of particles

### ISSUE THREAD

**Issue by ghost** [tsparticles/tsparticles#1031]
/* DO NOT DELETE THE TEMPLATE BELOW, you can safely delete this line */

**Which version are you using?**
Ex. 1.18.11

**Is the latest version affected?**

- [x] Yes
- [ ] No

**Which library are you using?**

- [x] Vue.js 2.x (`particles.vue`)

Is there a way by which I can parse the json config that I got from the website and inject it into the props of the Particles component? because I does not seem to work when I copy the configuration in the showcase in codepen, I want to know how to load the json from the website and use it in my vue components.

**Comment by matteobruni** [comment]
Hi @Yael95,

Loading it using an AJAX request actually is not supported but can be an idea for the upcoming `1.19` version.

For now, you can check out a sample made with the JSON import syntax: https://codesandbox.io/s/particlesvue-with-json-config-lgpjc

Let me know if it helps.

**Comment by ghost** [comment]
hi @matteobruni ,
I have been trying to use your examples in the codepen but couldn't I have been trying to import the polygon mask from the codepen you shared but wasn't able to include it in a component, would you have any pointers why I get just the string of the options printed out .

**Comment by ghost** [comment]
About the sandbox I do not seem to get where your component is, is it the hello world component that you are using the config file in?

**Comment by ghost** [comment]
if you can just show me with an example sandbox for instance the vue implementation of the polygon mask it would help to get the sense out of this amazing tool as I am struggling to get it to work on vue except for the demo config you have on the repo.

**Comment by matteobruni** [comment]
I've updated the CodeSandbox sample linked in the previous message. I've added some comments but I'll explain here too:

The file *App.vue* uses the `Particles` component but its initialization is made in the *main.js* file.

```javascript
/* the import of the Particles.vue plugin */
import Particles from "particles.vue";
/* the import of the polyfill library needed for the polygon mask */
import "pathseg";

/* adds the Particles.vue plugin to the Vue instance, this enables the component */
Vue.use(Particles);
```

This is the code needed to make `particles.vue` work correctly. The `import "pathseg";` is needed only for `polygonMask` configurations since some browsers have removed the SVG 1.1 compatibility (Chrome for example).

If you are using some SSR framework you need to import both `particles.vue` and `pathseg` client-side.

**Comment by Yael95** [comment]
<template>
  <div id="tsparticles">
    <Particles :options="{ fpsLimit: 60, particles: { number: { value: 200,
    density: { enable: true, value_area: 1000 } }, color: { value: ["#54097F",
    "#96d3fd", "#c996fd"] }, shape: { type: "circle", stroke: { width: 0.5,
    color: "#fff" }, polygon: { nb_sides: 8 }, image: { src: "img/github.svg",
    width: 100, height: 100 } }, opacity: { value: 0.6, random: false, anim: {
    enable: false, speed: 1, opacity_min: 0.1, sync: false } }, size: { value:
    2, random: true, anim: { enable: false, speed: 40, size_min: 0.1, sync:
    false } }, line_linked: { enable: true, distance: 120, color: "#ffffff",
    opacity: 0.4, width: 1 }, move: { enable: true } }, interactivity: {
    detect_on: "canvas", events: { onhover: { enable: true, mode: "grab" },
    onclick: { enable: false }, resize: true }, modes: { grab: { distance: 150,
    line_linked: { opacity: 0.8 } }, bubble: { distance: 400, size: 40,
    duration: 2, opacity: 8, speed: 3 }, repulse: { distance: 200, duration: 0.4
    }, push: { particles_nb: 4 }, remove: { particles_nb: 2 } } },
    retina_detect: true }" />
  </div>
</template>

<script>
export default {}
</script>

<style lang="scss" scoped>
html,
body {
  height: 100vh;
  margin: 0px;
  padding: 0px;
}
#tsparticles {
  width: 100%;
  height: 100%;
  background: url('https://static.pexels.com/photos/326337/pexels-photo-326337.jpeg');
  background-size: 800px 600px;
  background-repeat: no-repeat;
  background-size: cover;
}
</style>
`<bold>Here is my component that I used for the forest polygon example in the code pen </bold>`

and here is my plugin in Nuxt : 

import Vue from 'vue'
import Particles from 'particles.vue'
import pathseg from 'pathseg'

Vue.use(Particles)

and I still get only the image without the particles showing

**Comment by ghost** [comment]
Thank you for your help I got the polygon forest to work, thank you for your help and patience.
