### ISSUE TITLE
How to set up svelte-particles as a foreground clickthrough layer...

### ISSUE THREAD

**Issue by rchrdnsh** [tsparticles/tsparticles#1042]
**Which version are you using?**

latest

**Is the latest version affected?**

- [ ] Yes

**Which library are you using?**

- [ ] Svelte (`svelte-particles`)

Here is a REPL of the issue:

https://svelte.dev/repl/2ef0c3ffa03f46fd8887909a0793959a?version=3.23.2

The canvas? i think, is only filling up half of the viewport, and I can get any styles into the component to change it...or not sure how...

It's basically the SSR example with the config altered to make snow...otherwise, it's the same.

**Comment by matteobruni** [comment]
Hi @rchrdnsh,

I've opened the link but it seems to work fine, what is the broken behavior?

Anyway, I fixed the configuration to make the button clickable. You can see the new configuration here: https://svelte.dev/repl/ff70fdab5da6401584c0346f647e844f?version=3.23.2

To make the button work the particles component shouldn't have:

- a specified size (like `width: 100%` or `height: 100%`)
- a `z-index`
- placed over other HTML elements

After those points checked you just need to set these values in your particles configuration:

```javascript
{
    backgroundMode: {
        enable: true,
        zIndex: 100 /* choose your value */
    },
    interactivity: {
        detectsOn: "window" /* this disables the pointer events on canvas */
    }
}
```

**Comment by rchrdnsh** [comment]
ah yes, thank you! I originally had something funky going on in the configuration, but I fixed it by tweaking one of your codepen examples and then copying it in...thank you also for helping with the foreground click through issue as well. Works great now!!!

For got to close this one out as well, thanks :-)
