### ISSUE TITLE
Vue2x: IE11 script1010 error

### ISSUE THREAD

**Issue by werty1001** [tsparticles/tsparticles#1100]
**Which version are you using?**
2.1.11

**Is the latest version affected?**

- [x] Yes
- [ ] No

**Which library are you using?**

- [ ] Vanilla JS (`tsparticles`)
- [ ] React (`react-tsparticles`)
- [x] Vue.js 2.x (`particles.vue`)
- [ ] Vue.js 3.x (`particles.vue3`)
- [ ] Angular (`ng-particles`)
- [ ] Svelte (`svelte-particles`)
- [ ] Preact (`preact-particles`)
- [ ] Inferno (`inferno-particles`)
- [ ] jQuery (`jquery-particles`)

**Describe the bug**
When using `particles.vue` and opening in IE11, the error occurs: `SCRIPT1010: Expected identifier`.

**Screenshots**
![1](https://user-images.githubusercontent.com/6961502/101192536-406a2c80-366c-11eb-82db-b19044190b39.png)
![2](https://user-images.githubusercontent.com/6961502/101192556-4829d100-366c-11eb-9782-d53748ba81bc.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: IE
 - Version: 11

**Comment by matteobruni** [comment]
I'm sorry but the Internet Explorer support is not on my to-do list, since the browser has been replaced by Edge.

If anyone wants to make a PR about it, is welcome to submit it.

**Comment by werty1001** [comment]
I found how to fix the error, we can add to `vue.config.js` transpile option:
```
  transpileDependencies: [
    'tsparticles',
  ],
```
Thanks for VUE component!

**Comment by matteobruni** [comment]
Thanks to you for the solution, I'll add it to the documentation!
