### ISSUE TITLE
Cannot find a way to get a reference to the Container object with React

### ISSUE THREAD

**Issue by monteiz** [tsparticles/tsparticles#1108]
**Which version are you using?**
1.18.11

**Is the latest version affected?**

- [X] Yes
- [ ] No

**Which library are you using?**

- [ ] Vanilla JS (`tsparticles`)
- [X] React (`react-tsparticles`)
- [ ] Vue.js 2.x (`particles.vue`)
- [ ] Vue.js 3.x (`particles.vue3`)
- [ ] Angular (`ng-particles`)
- [ ] Svelte (`svelte-particles`)
- [ ] Preact (`preact-particles`)
- [ ] Inferno (`inferno-particles`)
- [ ] jQuery (`jquery-particles`)

I did not find in the documentation a way to get a reference to the Particles instance, in order to call its methods (play, refresh and so on). Can you give an example?

**Comment by matteobruni** [comment]
Hi @monteiz 

Actually, there is a `container` property in the `<Particles />` tag which is a `React` `ref` property.

You can see a sample here:

https://codesandbox.io/s/compassionate-mcnulty-ocu3r?file=/src/App.js

The `useEffect` retrieves the object after the loading and logs it in the `console` just to show that the object is the right one

**Comment by monteiz** [comment]
That did the job, thank you so much.

I needed that because using SSR, the initial canvas size is [0,0].

I have to set the correct canvas size after the first render:

```
	useEffect(() => {
		if (containerRef && containerRef.current) {
			setTimeout(() => {
				containerRef.current.canvas.width = window.innerWidth;
				containerRef.current.canvas.height = window.innerHeight;
				containerRef.current.refresh();
			}, 1000);
		}
	}, []);
```
