### ISSUE TITLE
[REACT] Can we get a 'onload' event? 

### ISSUE THREAD

**Issue by tomswork** [tsparticles/tsparticles#1218]
Hey guys it would be great to get an onload prop on the react component (similar to the load promise on normal tsparticles) - doesnt look like there is a way to set this up otherwise. 

**Which version are you using?**
react-tsparticles 1.18.11

**Is the latest version affected?**

- [x] Yes
- [ ] No

**Which library are you using?**

- [ ] Vanilla JS (`tsparticles`)
- [x] React (`react-tsparticles`)
- [ ] Vue.js 2.x (`particles.vue`)
- [ ] Vue.js 3.x (`particles.vue3`)
- [ ] Angular (`ng-particles`)
- [ ] Svelte (`svelte-particles`)
- [ ] Preact (`preact-particles`)
- [ ] Inferno (`inferno-particles`)
- [ ] jQuery (`jquery-particles`)

**Comment by matteobruni** [comment]
Hi @tomswork, the upcoming `2.0.0` release will have this feature.

This will also permit the loading of any preset or plugin in all components, actually, it's possible only in the core version.

**Comment by tomswork** [comment]
Ok great @matteobruni looking forward to it 👍

**Comment by matteobruni** [comment]
The `loaded` property will accept a `(container) => void` function, and it will be called when the assigned container will be initialized. This will be introduced starting from `2.0.0-alpha.2` for `React`, `Preact` and `Inferno`
