### ISSUE TITLE
Border-radius option in the JS particles library?

### ISSUE THREAD

**Issue by Henama** [tsparticles/tsparticles#1220]
Hi,

First of all thanks for the JS particles library. It is a very cool library (using 1.18.11). I'm curious of it is possible to create a rectangle with a smooth border. Just like in CSS: border-radius: 10px (for example). I cannot find something like this on CodePen or on Google for this plugin.

Thanks.

**Comment by matteobruni** [comment]
Hi @Henama,

I don't understand what are you requesting, what should have the `border-radius`? You can set it to the `div` style like any other div or directly on the `canvas` element.

**Comment by Henama** [comment]
Hi @matteobruni,

Thanks for your message.

I try to create particles: circles and rectangles. But I want smooth borders on the rectangles. I want this kind of shapes in my particles effect: https://pasteboard.co/JIFI8cQ.jpg

Is this possible by using shapes? And how can I get this done?

Thanks.

**Comment by matteobruni** [comment]
Actually, that shape is not supported, but if you want to create your custom shape you can have a look at some external shapes I've made.

Checkout these:

- Bubble shape effect: https://github.com/matteobruni/tsparticles/tree/master/shapes/bubble
- Heart shape: https://github.com/matteobruni/tsparticles/tree/master/shapes/heart
- Multiline text shape: https://github.com/matteobruni/tsparticles/tree/master/shapes/multiline-text
- Spiral shape: https://github.com/matteobruni/tsparticles/tree/master/shapes/spiral

Hope it helps, if you need more help, don't hesitate to ask, I'd like to have these rounded shapes in the project if you want, or if you want to publish them yourself I'll add the links in the documentation

**Comment by Henama** [comment]
Thanks again for your reply!

Hm, I'm not that familiar with JS to creates custom shapes like your examples. Could you give me some input, maybe a small example, so I can tweak/customize it?

I know I've to use `tsParticles.addShape` to add a Shape. But I don't know how to configure it into a rectangle with rounded borders..

Thanks!

**Comment by matteobruni** [comment]
I linked the 4 additional shapes, you can start from the `heart` sample (it's the simpler).

If you don't want to use TypeScript, you can just use a single JavaScript file, don't worry.

The first param is the shape `type` (to be used instead of `circle` or others) and the second one is a function with the canvas context, the particle, and the radius in the parameters, you don't have to return anything, just use the 2d context drawing functions.

You can read more here about drawing to a canvas: https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Drawing_shapes

An important note: the (0,0) coordinate is the particle center.

**Comment by Henama** [comment]
Thanks for your reply.

I tried with your advice to create a shape, but without luck. It's hard for me to draw a shape like this and implement it to de `tsParticles.addShape` function. Is there any possibility you could help me with this shape?

**Comment by matteobruni** [comment]
If you can show me what you have done for now I can give you more help

**Comment by Henama** [comment]
Thanks for your reply.

```
tsParticles.addShape("smoothrectangle", function (context, particle, radius) {
    const x = -radius;
    const y = -radius;

    context.beginPath();
    context.moveTo(20, 10);
    context.lineTo(80, 10);
    context.quadraticCurveTo(90, 10, 90, 20);
    context.lineTo(90, 80);
    context.quadraticCurveTo(90, 90, 80, 90);
    context.lineTo(20, 90);
    context.quadraticCurveTo(10, 90, 10, 80);
    context.lineTo(10, 20);
    context.quadraticCurveTo(10, 10, 20, 10);
    context.stroke();
});
```
At this moment I made this, the shape is 'ok' now, but I don't know how to make the difference between filled shapes and not (it should be randomize). And it looks like it doesn't sync with the options. I can't change the size of them for example in `tsParticles.load`..

**Comment by matteobruni** [comment]
You don't need to call `stroke` or `beginPath`, tsParticles already handle them with right options.

You should not use constant values but calculate values using `radius`.

I try to add it to a codepen so I can check it

**Comment by Henama** [comment]
Thanks for your reply.

I removed the stroke. See my codepen here: https://codepen.io/Henama/pen/GRjBOVa, but no luck with the rectangles..

**Comment by matteobruni** [comment]
I've checked out the codepen, the `type` was misplaced, it's outside the `particles` section.

**Comment by Henama** [comment]
Thanks for your reply.

Oh, it looks much better now! Could you tell me why the rectangles are not bouncing well here, to other particles and why the size is not variable here?

**Comment by matteobruni** [comment]
You need to replace all the constant values with `radius` based formulas, remembering that the `0,0` coordinates must be the shape center to have good bounces and rotations

**Comment by Henama** [comment]
Thanks for your reply.

What do you mean with this: "_remembering that the 0,0 coordinates must be the shape center to have good bounces and rotations_"? I can't figure out how to bounce properly..

**Comment by Henama** [comment]
Thanks for your reply.

I can't figure how this should be done, I'm not that good in Javascript. Sorry Matteo, thanks for your help.

**Comment by matteobruni** [comment]
Hi @Henama,

I created the shape you requested also working for `v1`.

You can see a working sample here: https://codepen.io/matteobruni/pen/RwodxpY

NB: You need to include also the script from <https://www.jsdelivr.com/package/npm/tsparticles-shape-rounded-rect>, the `rounded-rect` shape is not included in the base library.
