### ISSUE TITLE
[Question] class instead of div for the container

### ISSUE THREAD

**Issue by noraj** [tsparticles/tsparticles#1251]
**Which version are you using?**

1.18.11

**Is the latest version affected?**

Not an issue.

**Which library are you using?**

- [x] Vanilla JS (`tsparticles`)
- [ ] React (`react-tsparticles`)
- [ ] Vue.js 2.x (`particles.vue`)
- [ ] Vue.js 3.x (`particles.vue3`)
- [ ] Angular (`ng-particles`)
- [ ] Svelte (`svelte-particles`)
- [ ] Preact (`preact-particles`)
- [ ] Inferno (`inferno-particles`)
- [ ] jQuery (`jquery-particles`)

## Question

Instead of using tsparticles as a full size background I want to use it as an element that I can use to replace images. Right know the loader is supporter an id (which is an unique css selector) but is there a way to use a class (can match multiple elements) instead so I don't have to create 10 identical classes and load tsparticles 10 times? But before that another question is can we load several times tsparticles on the same page?

![image](https://user-images.githubusercontent.com/16578570/105739795-c9009d00-5f38-11eb-8fb8-7e47e9b7b95a.png)

Of course I'll use the configuration for all the 10 elements.

**Comment by matteobruni** [comment]
Hi @noraj,

Actually, anything different from an `id` is not supported. But maybe it won't be supported in the future too. The reason is simple, I do not recommend more than `1` tsParticles instance per page since the performance would drop significantly.

Maybe a better solution is to create a transparent div on top the one you are trying to target at the moment and load there the particles instance.
You can then change the options and refresh the tsParticles instance or use themes and switch them.

If you need more help don't hesitate to ask.

**Comment by noraj** [comment]
In my case there won't be performance issue as I was planning to use a static display (no animation), just a random set of particles at start. But if it won't be supported in the future I'll just export it as a picture and load the picture multiple times but i won't be random and it will have a fixed size.

**Comment by matteobruni** [comment]
@noraj maybe I understood bad what you want to achieve in the first place.

Do you want to have a random configuration loaded every time? This can be achieved with a single instance

**Comment by noraj** [comment]
Imagine a page where I have 10 images, I wanted to replace the 10 images with 10 instances of tsParticles (eg a 250x250 div) without any animation (static) but the random case checked so each image would be different but using the same config (the particles would just be placed differently for each). But you already answered me there was no solution for that and won't be in the future. As creating `n` id and loading `n` times the script is not an option I'll just stick to an exported image.

By the way on codepen I see only examples where tsParticles is used as a fullpage background and sometimes just a login form on hit but no examples where tsParticles is only a background of an element (eg. a [hero](https://codepen.io/chris__sev/pen/qPNNwy)).

**Comment by matteobruni** [comment]
Thank you @noraj, I'll create a sample with a hero section, maybe it will be clearer that the container is any HTML element with that id, it's the CSS that makes the difference in this case.

Anyway, I'm still thinking about what you want to achieve. I think I have a solution as you can see [here](https://codepen.io/matteobruni/pen/XWjLOpQ)

As I said this configuration uses more resources but with a lighter config like the one used in the sample it's still acceptable.

**Comment by noraj** [comment]
> Anyway, I'm still thinking about what you want to achieve. I think I have a solution as you can see [here](https://codepen.io/matteobruni/pen/XWjLOpQ)
> 
> As I said this configuration uses more resources but with a lighter config like the one used in the sample it's still acceptable.

Wow nice trick, I'll try that tomorrow.



> Thank you @noraj, I'll create a sample with a hero section, maybe it will be clearer that the container is any HTML element with that id, it's the CSS that makes the difference in this case.

Yes, I had a hard time playing with that but failed.

**Comment by matteobruni** [comment]
@noraj [here](https://codepen.io/matteobruni/pen/QWKXPRq) you can find a sample with tsParticles in the hero you linked, a little CSS is needed but is not breaking the layout

**Comment by noraj** [comment]
@matteobruni You're amazing, thx a lot.
