### ISSUE TITLE
Polygon Mask bounce back inline is not working

### ISSUE THREAD

**Issue by matteobruni** [tsparticles/tsparticles#1256]
PolygonMask with inline configuration is breaking with the repulse mouse event, the particles are not bouncing back to their initial position

**Comment by ognjenjevremovic** [comment]
Recently I worked on my personal portfolio website and wanted to use the _particles.js_ library for some particles effects.
However, I found out the project was _abandoned_ and not actively maintained. Reading through the issues on the that project I found out about your Typescript version of the library; _tsparticles_ an actively maintained _"fork"_ that is very much worked on with new features being added.

I wanted to contribute back to this project, as I really found great value using it (and it saved me a lot of time!).
Looking at the open (labeled) issues I found out about this one, labeled as a _good first issue_ which is also of high priority and it is up for grabs.
It seems that this would be a good place to start for newcomers to the project.

Do you mind giving a more detailed explanation about this issue? How may one reproduce it and how should one approach this?
May you give slight hints on where the problem might be located (is it in the library `core` or is perhaps a part of the `plugins` and how it should be tackled?

Many thanks for this awesome project! 🎉

**Comment by matteobruni** [comment]
Hi @ognjenjevremovic,

First of all thanks! This issue is a little bit tricky but I think it's easy to fix.

The `polygonMask` plugin has some issues with particles bouncing, it's not only related to mouse events with the repulse mode.

You can start from [this](https://github.com/matteobruni/tsparticles/blob/b96799f26166ab360dc75538445ee2d55a4cedd7/plugins/polygonMask/src/Utils.ts#L24) method, it updates the particle velocity for the polygon mask feature. It needs to be fixed since those formulas are not good.

It's used [here](https://github.com/matteobruni/tsparticles/blob/b96799f26166ab360dc75538445ee2d55a4cedd7/plugins/polygonMask/src/PolygonMaskInstance.ts#L103) and as you can see it's used for `inside`/`outside` bounce and for the bounce back the particle when used `inline`.

For `inside`/`outside` the particle should just bounce away from the SVG border (inside or outside depends on the configuration).

The `inline` configuration instead requires a little more work since the particle should be brought back to its initial position.

You can test everything running the `demo/main` folder using the `polygonMask` sample or you can create a new one if you prefer.

Please use the `dev` branch for this feature since the new `2.0.0` structure has changed a lot and I don't want to update the actual `1.x` version more than urgent fixes.

For more help fell free to join the [Slack](https://join.slack.com/t/tsparticles/shared_invite/enQtOTcxNTQxNjQ4NzkxLWE2MTZhZWExMWRmOWI5MTMxNjczOGE1Yjk0MjViYjdkYTUzODM3OTc5MGQ5MjFlODc4MzE0N2Q1OWQxZDc1YzI) so we can discuss easily

**Comment by ognjenjevremovic** [comment]
Thanks for getting back to me in such a short notice.
I'll be sure to start from the methods you have linked.

I have also joined Slack for any further questions I might have, regarding this or any other issue.
I hope I will have the fix ready in the next couple of days.

I'll able to dedicate my time to look into this issue in the greater details in the upcoming weekend.
I'll post some updates when I have some.

**Comment by ognjenjevremovic** [comment]
Hey @matteobit just wanted give an update on this one.

I didn't manage to get a hold of the source.
I am not sure it is related to _PolygonMask_ plugin (after hours of debugging, though I might be completely wrong); or I am looking at the completely unrelated stuff (which is of high possibility).

I compared the code with the latest _v1_ release and couldn't track the issue on the _PolygonMask_ plugin - the code seems pretty much identical (I thought the comparison might give me a better overview).
I see there's some issue with the compiled code (related to TypeScript) when running the demo app locally; not sure if that might be somehow related to this issue.
As it turns out, there seems to be some circularly importing classes in the _Core_ part [TS#20361](https://github.com/Microsoft/TypeScript/issues/20361).

I'm still willing to contribute, although I am not sure if I'll be able to 🙂 .

**Comment by matteobruni** [comment]
The issue I was talking here is existing in v1 as well since the bounce was incorrect. Maybe something else is broken but v2 is under development.
I’d like to discuss these dev things with Slack since they’re just dev issues, not production.
