### ISSUE TITLE
How to debug?

### ISSUE THREAD

**Issue by WouterrV** [tsparticles/tsparticles#1257]
I have this message in my console: `callback - tsparticles config loaded` but I don't see particles in the div with `id` =  `particlets`. How do I debug this?

**Comment by matteobruni** [comment]
Hi @WouterrV, can you share the config? 

It can help me identify the issue and explain it

**Comment by WouterrV** [comment]
Thanks for your reply. The problem turned out a typo in the `id`, a `canvas` element appeared as soon as I fixed that. Maybe it'd be nice for tsparticles to log if it can't find the specified element..
