### ISSUE TITLE
[Security] Where can I report a security issue of this project?

### ISSUE THREAD

**Issue by Ry0taK** [tsparticles/tsparticles#1284]
**Which version are you using?**
N/A

**Is the latest version affected?**

- [x] Yes
- [ ] No

**Which library are you using?**

- [ ] Vanilla JS (`tsparticles`)
- [ ] React (`react-tsparticles`)
- [ ] Vue.js 2.x (`particles.vue`)
- [ ] Vue.js 3.x (`particles.vue3`)
- [ ] Angular (`ng-particles`)
- [ ] Svelte (`svelte-particles`)
- [ ] Preact (`preact-particles`)
- [ ] Inferno (`inferno-particles`)
- [ ] jQuery (`jquery-particles`)

## Question
It looks like [SECURITY.md](https://github.com/matteobruni/tsparticles/blob/935537f7de358b18947cb37f7062305684cf284f/SECURITY.md) doesn't contain any valid contact information.
Since I found a potential security issue, I want to test/report it.
Where can I send a message privately?

**Comment by matteobruni** [comment]
Hi @Ry0taK,

You can use [Slack](https://tsparticles.slack.com/join/shared_invite/enQtOTcxNTQxNjQ4NzkxLWE2MTZhZWExMWRmOWI5MTMxNjczOGE1Yjk0MjViYjdkYTUzODM3OTc5MGQ5MjFlODc4MzE0N2Q1OWQxZDc1YzI) or you can contact me by mail

**Comment by Ry0taK** [comment]
Hi @matteobruni,
Okay, I joined the Slack and sent a message to the DM!
