### ISSUE TITLE
Ng-Particles generates extra div parent of Canvas. How to add a class to that div?

### ISSUE THREAD

**Issue by fredyfx** [tsparticles/tsparticles#1299]
**Which version are you using?**
1.18.12

**Is the latest version affected?**

- [X] Yes
- [ ] No

**Which library are you using?**

- [ ] Vanilla JS (`tsparticles`)
- [ ] React (`react-tsparticles`)
- [ ] Vue.js 2.x (`particles.vue`)
- [ ] Vue.js 3.x (`particles.vue3`)
- [X] Angular (`ng-particles`)
- [ ] Svelte (`svelte-particles`)
- [ ] Preact (`preact-particles`)
- [ ] Inferno (`inferno-particles`)
- [ ] jQuery (`jquery-particles`)

Problem with Angular ng-particles:
It renders just a little part, not the full height and width as I expect.

![image](https://user-images.githubusercontent.com/4960023/107494449-aa5af280-6b43-11eb-86fa-6687bc467c03.png)

Without using Angular, no problem:
Almost the same code, the difference here is the "div"
![image](https://user-images.githubusercontent.com/4960023/107496062-b47df080-6b45-11eb-8cec-8faf54fbe21b.png)

Quick important detail:
.particles contains position absolute and the 100% for width and height.

The class "particles" should be inside the first div.
<Particles [id]="id" class="particles" [options]="particlesOptions" (particlesLoaded)="particlesLoaded($event)"></Particles>

Does anyone know how to handle this situation? 

Thanks!

Fredy

**Comment by matteobruni** [comment]
Hi @fredyfx,

In the demo app I use for testing I used a css file: https://github.com/matteobruni/tsparticles/blob/master/demo/angular/src/styles.css

But if you want to make it full screen you can use the `backgroundMode` options like this:

```
{
    backgroundMode: {
        enable: true,
        zIndex: 0
    },
    /* other options */
}
```

**Comment by fredyfx** [comment]
This is very interesting, the CSS was unused. The only thing I needed to add was the backgroundMode. Thanks Matteo!
