### ISSUE TITLE
Enable particles to "move" in two directions (up and down)

### ISSUE THREAD

**Issue by alexwybraniec** [tsparticles/tsparticles#1323]
**Which version are you using?**
1.18.12

**Is the latest version affected?**

- [X ] Yes
- [ ] No

**Which library are you using?**

- [ X] Vanilla JS (`tsparticles`)
- [ ] React (`react-tsparticles`)
- [ ] Vue.js 2.x (`particles.vue`)
- [ ] Vue.js 3.x (`particles.vue3`)
- [ ] Angular (`ng-particles`)
- [ ] Svelte (`svelte-particles`)
- [ ] Preact (`preact-particles`)
- [ ] Inferno (`inferno-particles`)
- [ ] jQuery (`jquery-particles`)

**Is your feature request related to a problem? Please describe.**
Currently it seems like you can only make particle travel in a single global direction.

**Describe the solution you'd like**
Would it be possible to set direction as an array, so for example 50% of particles could travel up the page, and 50% could travel down.

**Describe alternatives you've considered**
We considered doing this with two canvas elements, but in our use case we are using the "line linking" because particle as an visual indicator.

**Additional context**
Thank you in advance

**Comment by matteobruni** [comment]
Hi @alexwybraniec,

This configuration can be achieved with the `1.18.x` version using a little trick, in the upcoming `2.0.0` it will be easier using particles groups (#1006)

You can try this configuration

```javascript
tsParticles.load("tsparticles", {
  background: {
    color: "#fff"
  },
  backgroundMode: {
    enable: true
  },
  detectRetina: true,
  fpsLimit: 60,
  interactivity: {
    detectsOn: "canvas",
    events: {
      onClick: {
        enable: true,
        mode: "push"
      },
      onHover: {
        enable: true,
        mode: "bubble"
      },
      resize: true
    },
    modes: {
      bubble: {
        distance: 400,
        duration: 2,
        opacity: 1,
        size: 40,
        speed: 3
      },
      push: {
        quantity: 4
      }
    }
  },
  particles: {
    rotate: {
      value: 0,
      random: false,
      direction: "clockwise",
      animation: {
        enable: false,
        speed: 5,
        sync: false
      }
    },
    move: {
      enable: true,
      outMode: "out",
      speed: 2
    },
    number: {
      density: {
        enable: true,
        area: 800
      },
      value: 80
    },
    opacity: {
      value: 0.8
    },
    shape: {
      type: "circle",
      options: {
        circle: [ // this is the workaround
          {
            particles: { // this overrides the main particles section
              color: {
                value: "#f00"
              },
              move: {
                direction: "top"
              }
            }
          },
          {
            particles: {
              color: {
                value: "#00f"
              },
              move: {
                direction: "bottom"
              }
            }
          }
        ]
      }
    },
    size: {
      value: 16
    }
  }
});
```

Working sample: https://codepen.io/matteobruni/pen/JjbJOLz
