### ISSUE TITLE
lineLinked -> opacity as an hover effect

### ISSUE THREAD

**Issue by lorenzofay** [tsparticles/tsparticles#1325]
**Which version are you using?**
Ex. 1.18.12

**Is the latest version affected?**

- [•] Yes
- [ ] No

**Which library are you using?**

- [•] Vanilla JS (`tsparticles`)
- [ ] React (`react-tsparticles`)
- [ ] Vue.js 2.x (`particles.vue`)
- [ ] Vue.js 3.x (`particles.vue3`)
- [ ] Angular (`ng-particles`)
- [ ] Svelte (`svelte-particles`)
- [ ] Preact (`preact-particles`)
- [ ] Inferno (`inferno-particles`)
- [ ] jQuery (`jquery-particles`)

**Is your feature request related to a problem? Please describe.**
There is no way to change lineLinked -> opacity as an hover effect without using connect or grab.

**Describe the solution you'd like**
I think a new mode should be created. Or maybe add lineLinked as an argument of bubble...

**Describe alternatives you've considered**

**Additional context**
[particles and line-linked opacity hover effect.txt](https://github.com/matteobruni/tsparticles/files/6015395/particles.and.line-linked.opacity.hover.effect.txt)

http://casablanca.figura.tech/index.php/constellation/ is my best approach. But im not using this tsparticles.

**Comment by mitalrs** [comment]
Can I contribute in this issue?, Can u assigned this issue?

**Comment by Guzzler** [comment]
I would like to pick this up if it hasn't been done yet @matteobruni

**Comment by matteobruni** [comment]
> I would like to pick this up if it hasn't been done yet @matteobruni

It’s not done yet, have fun
