### ISSUE TITLE
The target entry-point "ng-particles" has missing dependencies:  - tsparticles

### ISSUE THREAD

**Issue by PackageDotJSON** [tsparticles/tsparticles#1337]
I have installed ng-particles using npm and importing it in my app.module.ts file. But, angular app is not running and throwing an error: 
The target entry-point "ng-particles" has missing dependencies:
 - tsparticles
 
 I do not know how to use the tsparticles in my angular app as their official documentation refers to ng-particles for angular framework.

**Comment by matteobruni** [comment]
Hi @kiyani1995,

You need to install `tsparticles` as well, the `ng-particles` is wrapped around the core library.

Once installed `tsparticles` you don't need to do anything else with that, it's just for being correctly included in the project correctly.
