### ISSUE TITLE
Aspect ratio does not update when tsparticles' element changes size, but the window has not changed size

### ISSUE THREAD

**Issue by n8sabes** [tsparticles/tsparticles#1466]
In **Vanilla JS version 1.26.0** if tsparticles' DOM element resizes, the canvas render becomes distorted. I've enabled `resize: true`, and upon manually resizing the window, tsparticles adjusts as expected. This however does not solve when a page reflows happens and all elements in a flexbox update with new widths and heights, one of which children is tsparticles.

**QUESTION:** Is there a way to have tsparticles auto-detect if its element (or parent) has changed size as a result of a reflow without a window resize occurring?

I've temporarily injected a resize event as a result of page changes which corrects the aspect ratio, but this doesn't seem very elegant.

**Comment by matteobruni** [comment]
Hello @n8sabes,

Unfortunately you did the right thing since DOM elements don’t have a resize event so you need to fire it yourself when you know a change has been made.

I could do a resize every frame or something similar, but I think it’s not needed in most cases.

**Comment by n8sabes** [comment]
Hi @matteobit, Thank you for the response, and confirmation the workaround is currently best practice. It would be a nice if `resize` observed both the window and parent element to ensure aspect ratio is always correct in a responsive page.

**tsparticles** is amazing and I'm enjoying working with it!

**Comment by n8sabes** [comment]
@matteobit, I am circling back to revisit this topic. I'm finding in my reactive layout use case (adjacent flex items that can change size), I have to implement observers everywhere tsparticles is used and re-execute `tsparticles.load`.

Would your idea to test for element size-changes on every frame be a reasonable enhancement? If so, a `resizeDebounce` value might be nice to reduce proc load in the event size changes are coming from css or greensock animations.

**Comment by matteobruni** [comment]
I don't know how this could impact to general performances and behaviors. I have some doubts about the `density` option that will increase/decrease particles count based on the available area and the `responsive` options are affected too.

Anyway a valid workaround, if you don't want to reload everything, you can store the particles container like this:

```javascript
var container;

tsParticles.load("div id", { /* your options */ }).then(c => { container = c });

// it works with loadJSON too
```

And you can safely call `container.canvas.windowResize()` when needed. This is the same exact method called when the window is resized.

I'm thinking about a debounce inside that method, but it's only an idea for now.

**Comment by n8sabes** [comment]
Thanks for the snippet to access the canvas resize function. You have a good point about particle density. In my use case, a slider adjusts the size of sibling containers which causes rapid-fire updates, so I think:

1. Calling `canvas.resizeWindow()` will keep aspect ratios correct, and then
2. Defer a full load on debounce to fix density (**ONLY IF** density or other significant attribute has changed to prevent an unnecessary jolting replacement of particles).

This should make it nearly indiscernible to the eye.

Even the simplest things have edge cases to manage!!
