### ISSUE TITLE
tsc error with react-tsparticles

### ISSUE THREAD

**Issue by lensbart** [tsparticles/tsparticles#1472]
**Which version are you using?**
1.26.2

**Is the latest version affected?**
Yes

**Which library are you using?**

- [x] React (`react-tsparticles`)

**Describe the bug**
- TypeScript version 4.2.4

When running `tsc` with `skipLibCheck: false` in `tsconfig.json`, I get the following error:

```
.yarn/cache/react-tsparticles-npm-1.26.2-d48baba4cc-d00b5c043a.zip/node_modules/react-tsparticles/index.d.ts:8:71 - error TS2307: Cannot find module './src/' or its corresponding type declarations.

8 import type { IParticlesProps, IParticlesState, ParticlesProps } from "./src/";
```

The error can be avoided by setting `skipLibCheck: true` in `tsconfig.json`, [as is recommended](https://www.staging-typescript.org/tsconfig#skipLibCheck), but not the default and at the expense of type-system accuracy. A better solution seems to be to make the published package independent of its `src` directory.

**Comment by matteobruni** [comment]
Thanks for this, I never noticed that!

I think this is a high priority activity and will be inspected and fixed ASAP.

This could be an issue on Preact and Inferno packages too since they are almost the same.

**Comment by matteobruni** [comment]
I've just released a new patch version of `react-tsparticles` with this fix
