### ISSUE TITLE
Can’t get it to work with Vue 3 + Vite

### ISSUE THREAD

**Issue by fabz1001** [tsparticles/tsparticles#1473]
Hello, I'm trying to get particles to work in my Vue 3 + Vite project (with poor results)
Could I just ask for a codesandbox with Vue 3 and possibly Vite? Even the most basic configuration would do.

Thanks a lot in advance 

**Which version are you using?**
 1.9.2

**Is the latest version affected?**

*You can checkout latest version [here](https://www.npmjs.com/package/tsparticles)*

- [x] Yes
- [ ] No

**Which library are you using?**

- [ ] Vanilla JS (`tsparticles`)
- [ ] React (`react-tsparticles`)
- [ ] Vue.js 2.x (`particles.vue`)
- [x] Vue.js 3.x (`particles.vue3`)
- [ ] Angular (`ng-particles`)
- [ ] Svelte (`svelte-particles`)
- [ ] Preact (`preact-particles`)
- [ ] Inferno (`inferno-particles`)
- [ ] jQuery (`jquery-particles`)

<details>
 <summary><b>tsParticles Configuration</b></summary>
  
  ```javascript
  /* add your config here */
  ```
</details>

**Comment by matteobruni** [comment]
Can you give more details about how to create a Vite + Vue3 app? So I can start from that.

Have you got any error or it’s just not working?

**Comment by matteobruni** [comment]
I successfully used `particles.vue3` in a Vite project.

Steps:

`npm i particles.vue3`

Edited `main.ts` with this line

`import Particles from "particles.vue3"`

and edited the `createApp` line like this:

`createApp(App).use(Particles).mount('#app')`

Edited `shim-due.d.ts` adding this line

`declare module 'particles.vue3'`

Now the `<Particles>` component is ready to be used like in the samples.

I added this to `App.vue`

```
<Particles
    id="tsparticles"
    :particlesInit="particlesInit"
    :particlesLoaded="particlesLoaded"
    :options="{
      background: {
        color: {
          value: '#0d47a1',
        },
      },
      fullScreen: {
        enable: true
      },
      fpsLimit: 60,
      interactivity: {
        detectsOn: 'canvas',
        events: {
          onClick: {
            enable: true,
            mode: 'push',
          },
          onHover: {
            enable: true,
            mode: 'repulse',
          },
          resize: true,
        },
        modes: {
          bubble: {
            distance: 400,
            duration: 2,
            opacity: 0.8,
            size: 40,
          },
          push: {
            quantity: 4,
          },
          repulse: {
            distance: 200,
            duration: 0.4,
          },
        },
      },
      particles: {
        color: {
          value: '#ffffff',
        },
        links: {
          color: '#ffffff',
          distance: 150,
          enable: true,
          opacity: 0.5,
          width: 1,
        },
        collisions: {
          enable: true,
        },
        move: {
          direction: 'none',
          enable: true,
          outMode: 'bounce',
          random: false,
          speed: 6,
          straight: false,
        },
        number: {
          density: {
            enable: true,
            value_area: 800,
          },
          value: 80,
        },
        opacity: {
          value: 0.5,
        },
        shape: {
          type: 'circle',
        },
        size: {
          random: true,
          value: 5,
        },
      },
      detectRetina: true,
    }"
  />
```

**Comment by fabz1001** [comment]
Thanks for the blazing fast response. It was a stupid mistake. It's now working! :)
