### ISSUE TITLE
Resize problem using Gatsby

### ISSUE THREAD

**Issue by buligadragos** [tsparticles/tsparticles#1477]
**Which version are you using?**
1.26.2

**Is the latest version affected?**

*You can checkout latest version [here](https://www.npmjs.com/package/tsparticles)*

- [x ] Yes
- [ ] No

**Which library are you using?**

- [ ] Vanilla JS (`tsparticles`)
- [x ] React (`react-tsparticles`)
- [ ] Vue.js 2.x (`particles.vue`)
- [ ] Vue.js 3.x (`particles.vue3`)
- [ ] Angular (`ng-particles`)
- [ ] Svelte (`svelte-particles`)
- [ ] Preact (`preact-particles`)
- [ ] Inferno (`inferno-particles`)
- [ ] jQuery (`jquery-particles`)

<details>
 <summary><b>tsParticles Configuration</b></summary>
  
Default Polygon Mask Template

</details>

/* DO NOT DELETE THE TEMPLATE ABOVE, you can safely delete this line */

**Describe the bug**
I'm using Gatsby and when I'm using Polygon Mask if I resize the browser window the particle disappear. I tied even with the Gatsby plugin provided here, but there is the same issue. If in config I use "resize:false" it seems that it works, but it won't resize the SVG anymore.

**To Reproduce**
1. Using Gatsby and tsp articles
2. Use any Polygon Mask.
3. Resize the browser.

**Expected behavior**
To resize properly.

**Screenshots**
https://user-images.githubusercontent.com/29467465/114581068-14992c00-9c88-11eb-9314-c6d8316b1577.mov

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: All of them
 - Version:

**Smartphone (please complete the following information):**
 - Device: -
 - OS: -
 - Browser -
 - Version -

**Additional context**

**Comment by matteobruni** [comment]
Hi @buligadragos,
This issue is not related to React, it's a bug in the core library, thanks for reporting it. It will be inspected ASAP.
