### ISSUE TITLE
replaceColor option on image particle type not working.

### ISSUE THREAD

**Issue by GoldenMaximo** [tsparticles/tsparticles#1519]
**Which version are you using?**
1.26.3

**Is the latest version affected?**
- [x] Yes
- [ ] No

**Which library are you using?**

- [x] React (`react-tsparticles`)

<details>
 <summary><b>tsParticles Configuration:</b></summary>
  
  ```javascript
{
    background: {
        color: {
            value: 'transparent',
        },
        repeat: 'no-repeat',
        size: 'cover',
    },
    fullScreen: {
        enable: true,
        zIndex: 0,
    },
    particles: {
        collisions: {
            enable: true,
        },
        shape: {
            type: 'images',
            fill: true,
        },
        color: {
            value: '#ffffff',
        },
        move: {
            angle: {
                offset: 0,
                value: 0,
            },
            direction: 'bottom',
            enable: true,
            path: {
                clamp: false,
            },
            outModes: {
                bottom: 'out',
                left: 'out',
                right: 'out',
                top: 'out',
            },
            speed: 3.5,
        },
        number: {
            value: 50,
        },
        size: {
            random: {
                enable: true,
            },
            value: {
                min: 14,
                max: 18,
            },
        },
    },
};
  ```
</details>

**Describe the bug**
I'm trying to dynamically render SVGs as particles, I'm able to do so, however I'm having trouble trying to change their color.
I've tried a mix and match of different configurations to no avail. I've read the documentation over @ [particles.js.org](https://particles.js.org/docs/interfaces/_options_interfaces_particles_shape_iimageshape_.iimageshape.html#replacecolor) and also tried the deprecated options with no success.

I also tried the `fill` option that is passed to the image object, I wasn't sure if it was supposed to have the same behavior as `replaceColor` so I tried it as well and had no success.

On the `<Particles />` component imported from `'react-tsparticles'` I passed an `init` function much like so:

```
    const onInit = async Main => {
        if (Main) {
            const logoImgObjs = logoUrls
                .filter(e => e)
                .map(e => {
                    return {
                        src: e,
                        width: 400,
                        height: 400,
                        replaceColor: true,
                        fill: true,
                    };
                });

            const configWithImages = {
                ...tsParticlesConfigObj,
                particles: {
                    ...tsParticlesConfigObj.particles,
                    shape: {
                        ...tsParticlesConfigObj.particles.shape,
                        type: 'images',
                        images: logoImgObjs,
                    },
                },
            };

            const particlesInstance = await Main.load(id, configWithImages);
            particlesInstance?.refresh();
        }
    };
```

The only way I was able to change the color of the SVG was by modifying the `ImageDrawer.ts` file on `\tsparticles\core\main\src\ShapeDrawers\ImageDrawer.ts`

```
    private async loadImageShape(container: Container, imageShape: IImageShape): Promise<void> {
        try {
            let image = imageShape.replaceColor
                ? await Utils.downloadSvgImage(imageShape.src)
                : await Utils.loadImage(imageShape.src);

            if (image) {
                if (imageShape.replaceColor) {
                    image = {
                        ...image,
                        svgData: `${image.svgData?.substring(0, image.svgData.indexOf(">"))} fill="${
                            container.actualOptions.particles.color.value
                        }"${image.svgData?.substring(image.svgData.indexOf(">"))}`,
                    };
                }
                this.addImage(container, image);
            }
        } catch {
            console.warn(`tsParticles error - ${imageShape.src} not found`);
        }
    }
```

This way it works perfectly, but I decided not to open a PR with this fix because I suck at coding and there's probably a better way to do it than gluing strings together with substring.

**To Reproduce**
1. Pretty much just try to render multiple SVGs and try to replace their colors.

**Expected behavior**
Upon passing `fill: true` to the shape configuration and `replaceColor: true` to the configuration of the image shape I expect the SVG color to be replaced with `particles.color.value`.

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser: Brave
 - Version 1.23.75 Chromium: 90.0.4430.93 (Official Build) (64-bit)

**Comment by matteobruni** [comment]
Hi @GoldenMaximo,

Thanks for the report. About the PR feel free to open it even if the code is not the best, it’s a good chance to improve. It helps me see the differences from the original code.
Just a note, target that to branch `v1` since it’s near release that version.
