### ISSUE TITLE
Polygon feature not working in Chrome in ng-particles

### ISSUE THREAD

**Issue by OswaldTheMighty** [tsparticles/tsparticles#1524]
**Which version are you using?**
Ex. 1.26.3

**Is the latest version affected?**
Yes

*You can checkout latest version [here](https://www.npmjs.com/package/tsparticles)*

- [ ] Yes

**Which library are you using?**
- [ ] Angular (`ng-particles`)

**Describe the bug**
The polygon feature in the Angular package is not working in Chrome. This seems to be due to the use of deprecated/removed SVG API `pathSegList`.

`PolygonMaskInstance.ts`
```
        const segments = path.element.pathSegList;
        const len = segments.numberOfItems; // Error happens here cause segments is undefined
```

**To Reproduce**
1. Set up a sample angular project
2. I'm using tsParticles 1.26.3 and ng-particles 2.9.3
3. Set up the ""Hollow Knight" or "Multiple Polygon Mask" (or any other project that uses the polygon tag)
4. Run in Chrome (I'm using 90.0.4430.93 at the moment)
5. Observe particles not working. 
6. In Inspect Windows, you will see the call stack:
```
ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'numberOfItems' of undefined
TypeError: Cannot read property 'numberOfItems' of undefined
    at parsePaths (PolygonMaskInstance.js:49)
    at PolygonMaskInstance.parseSvgPath (PolygonMaskInstance.js:274)
    at PolygonMaskInstance.<anonymous> (PolygonMaskInstance.js:288)
    at Generator.next (<anonymous>)
    at fulfilled (PolygonMaskInstance.js:5)
    at ZoneDelegate.invoke (zone-evergreen.js:372)
    at Object.onInvoke (core.js:28577)
    at ZoneDelegate.invoke (zone-evergreen.js:371)
    at Zone.run (zone-evergreen.js:134)
    at zone-evergreen.js:1276
    at resolvePromise (zone-evergreen.js:1213)
```

**Expected behavior**
The particles should show in the shape of the loaded polygon. 
Note that the same steps do work in e.g. Safari.

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser Chrome
 - Version 90

**Comment by matteobruni** [comment]
Did you added `”pathseg”`? It’s required for Chrome compatibility for that feature

Similar issue:
https://github.com/matteobruni/tsparticles/issues/283

**Comment by OswaldTheMighty** [comment]
Amazing, I googled this for hours so I'm not sure how I didn't find this, but you're right that fixed it. Thanks for the help!
