### ISSUE TITLE
Add React SVGR Support

### ISSUE THREAD

**Issue by utkarshk384** [tsparticles/tsparticles#1636]
**Which version are you using?**
Ex. 1.19.2
1.28.1

**Is the latest version affected?**
Yes

*You can checkout latest version [here](https://www.npmjs.com/package/tsparticles)*

- [x] Yes
- [ ] No

**Which library are you using?**

- [ ] Vanilla JS (`tsparticles`)
- [x] React (`react-tsparticles`)
- [ ] Vue.js 2.x (`particles.vue`)
- [ ] Vue.js 3.x (`particles.vue3`)
- [ ] Angular (`ng-particles`)
- [ ] Svelte (`svelte-particles`)
- [ ] Preact (`preact-particles`)
- [ ] Inferno (`inferno-particles`)
- [ ] jQuery (`jquery-particles`)

<details>
 <summary><b>tsParticles Configuration</b></summary>
  
  ```javascript
const config: RecursivePartial<IOptions> = {
	fpsLimit: 60,
	interactivity: {
		detectsOn: "canvas",
		events: {
			onClick: {
				enable: true,
				mode: "push",
			},
			onHover: {
				enable: true,
				mode: "repulse",
			},
			resize: true,
		},
		modes: {
			bubble: {
				distance: 400,
				duration: 2,
				opacity: 0.8,
				size: 40,
			},
			push: {
				quantity: 2,
			},
			repulse: {
				distance: 200,
				duration: 0.4,
			},
		},
	},
	particles: {
		collisions: {
			enable: false,
		},
		move: {
			direction: "none",
			enable: true,
			outMode: "bounce",
			random: true,
			speed: 8,
			straight: true,
		},
		number: {
			density: {
				enable: true,
				value_area: 800,
			},
			value: 10,
		},
		opacity: {
			value: 0.8,
		},
		shape: {
			type: ["image"],
			image: {
				src: <MyCustomIcon className="text-primary" />,
			},
		},
		size: {
			random: true,
			value: 50,
		},
	},
	detectRetina: true,
}

  ```
</details>

**Is your feature request related to a problem? Please describe.**

The feature that I am requesting is nothing really serious but a great addition to the react-tsparticles library. If react-tsparticles could support SVGR(SVG React) then we can make the particles react to light mode /dark mode toggles.

For example, I have a custom Icon that will change color depending on whether light mode is turned on or dark mode is turned on.

**Describe the solution you'd like**
The solution that I think is doable and easier to develop is to add the type `component`  to `shape.type` and then add a new property to the `shape` called `component` which will take in a `React.FC` as a value.   

**Describe alternatives you've considered**
None as of now

**Additional context**

**Comment by matteobruni** [comment]
tsParticles uses canvas to draw elements and not DOM, also is not a React only library so this should be a feature only for the React component that I find unfair.

Anyway, if you want to have two different configurations based on themes you can checkout this sample with tsParticles themes configuration: https://codepen.io/matteobruni/pen/rNeOaWP
This configuration uses the themes option to customize particles color based on theme name. You can load the right theme to the component on demand with the specified theme like in the sample easily. You can try on your own for now, I’ll create a React sample for that later too.

**Comment by utkarshk384** [comment]
Thank You @matteobruni  for an extremely quick response. Yep, I agree that it would be unfair if this feature is available in react only. But is there any way to get around this issue? I will make  sure to look into the codepen that you provided  to see if it resolves my issue.

Thank you for the help!

**Comment by utkarshk384** [comment]
@matteobruni 
Can you help me with the implementation of the theme system in react? I made a config generator that would generate config depending on the theme(will attach a code snippet below). I tried to use the `useRef` hook to reference the config file and then pass it to the `options` prop. However, the Particles' color aren't being updated as per the theme when the theme is switched.  Here is a small snippet of my code implementation.


```javascript

const baseConfig = {
//...some config
    particles:{
         color: { value: "#000000" } //Dynamically edit this part of the code
    } 
}


const Particles: React.FC = () => {
	const [isDark] = useDarkMode()
	const config = useRef(baseConfig)

	useEffect(() => {
		config.current = genConfig(isDark)
	}, [isDark])

	return <ReactParticles options={config.current} className="absolute h-screen w-full" />
}


//The Config generator
const genConfig = (isDark: boolean): RecursivePartial<IOptions> => {
	const config: RecursivePartial<IOptions> = {
		...baseConfig,
	}

	if (isDark && config.particles?.color) config.particles.color.value = "#466884"
	else if (!isDark && config.particles?.color) config.particles.color.value = "#AFC0D0"
	return config
}


```

Edit:

I used font awesome icons because my end goal is to get the particles to respond to the theme system.

**Comment by matteobruni** [comment]
@Utkarsh-Kumar384 sorry I found a bug in the themes options loading and I had to release the `1.28.2` version.

You can find below a sample with two buttons switching particles themes, you don't have to deal with strange settings or refs. There's a `themes` section inside the options that you can see in the sample.

https://codesandbox.io/s/wonderful-tereshkova-2n6ty?file=/src/App.js

Each theme setting will inherit all settings and override the common ones

**Comment by utkarshk384** [comment]
@matteobruni 
Thank you for the quick fix. Now I am able to theme the particles depending on the theme system.

**Comment by utkarshk384** [comment]
@matteobruni 
Sorry for the partial responses, but I just want to confirm if the library does alter the `light` and `dark` classes in the root `<html>` tag? As when I switch to the page with the ts particles, it seems to change the class automatically without any state changes to the `isDark` state.

```js
const [isDark] = useDarkMode()

useEffect(() => {
        if (isDark) containerRef.current?.loadTheme("dark")
	else if (!isDark) containerRef.current?.loadTheme("light")
}, [isDark])
```
This only happens when I start from light mode and load the particles page. Not when I start from dark mode

**Comment by matteobruni** [comment]
The library doesn’t alter any external tag, it reads the CSS preferred color scheme if default and mode are set in theme, for example if default is true and mode is dark, this theme will be loaded automatically when user has a dark theme set in its device

**Comment by utkarshk384** [comment]
@matteobruni 
Is it possible to disable this behaviour of reading from the color scheme?

**Comment by matteobruni** [comment]
Just set default property in themes to false

**Comment by utkarshk384** [comment]
Oh worked, Thank you
