### ISSUE TITLE
Random move speed range not working

### ISSUE THREAD

**Issue by n8sabes** [tsparticles/tsparticles#1682]
When using `move` random speed, there does not seem to be a way to set the minimum value in the random range. I've tried the configuration below, but still get values below the min. Am I not configuring correctly, is this not supported, or a bug?

**Which version are you using?**
1.29.0
**Is the latest version affected?**
Yes
*You can checkout latest version [here](https://www.npmjs.com/package/tsparticles)*

- [X] Yes
- [ ] No

**Which library are you using?**

- [X] Vanilla JS (`tsparticles`)
- [ ] React (`react-tsparticles`)
- [ ] Vue.js 2.x (`particles.vue`)
- [ ] Vue.js 3.x (`particles.vue3`)
- [ ] Angular (`ng-particles`)
- [ ] Svelte (`svelte-particles`)
- [ ] Preact (`preact-particles`)
- [ ] Inferno (`inferno-particles`)
- [ ] jQuery (`jquery-particles`)

<details>
 <summary><b>tsParticles Configuration</b></summary>

  ```javascript
        move: {
            enable: true,
            random: true,
            speed: {
                "min": 5,
                "max": 3,
            },
            direction: "bottom",
            straight: false,
            out_mode: "out",
            bounce: false,
        }
  ```
</details>

**Comment by matteobruni** [comment]
If you set `random` to `false` it should work fine, if not I’ll investigate further 

Also set correct `min` and `max` values, they’re swapped

**Comment by n8sabes** [comment]
@matteobruni; Indeed, setting `random` to `false` AND correct assignment of `min` and `max` works perfectly.

Thank you -- Closing Issue.
