### ISSUE TITLE
Configure "push" size value

### ISSUE THREAD

**Issue by Kapcash** [tsparticles/tsparticles#1709]
## Which version are you using?
Version 1.29.2

##Which library are you using?

- [ ] Vanilla JS (`tsparticles`)
- [ ] React (`react-tsparticles`)
- [x] Vue.js 2.x (`particles.vue`)
- [ ] Vue.js 3.x (`particles.vue3`)
- [ ] Angular (`ng-particles`)
- [ ] Svelte (`svelte-particles`)
- [ ] Preact (`preact-particles`)
- [ ] Inferno (`inferno-particles`)
- [ ] jQuery (`jquery-particles`)

<details>
 <summary><b>tsParticles Configuration</b></summary>
  
  ```javascript
export default {
  background: {
    color: {
      value: '#ffffff'
    },
    image: "url('/background.jpg')",
    position: '50% 50%',
    repeat: 'no-repeat',
    size: 'cover'
  },
  backgroundMask: {
    cover: {
      color: {
        value: {
          r: 255,
          g: 255,
          b: 255
        }
      }
    },
    enable: true
  },
  fullScreen: {
    enable: false,
    zIndex: 1
  },
  fpsLimit: 45,
  interactivity: {
    events: {
      onClick: {
        enable: true,
        mode: 'push'
      },
      onHover: {
        enable: true,
        mode: 'bubble',
        parallax: {
          force: 60
        }
      }
    },
    modes: {
      bubble: {
        distance: 120,
        duration: 2,
        opacity: 1,
        size: 27
      }
    }
  },
  motion: {
    reduce: {
      value: false
    }
  },
  particles: {
    color: {
      value: '#ffffff'
    },
    links: {
      color: {
        value: '#ffffff'
      },
      distance: 50,
      enable: false
    },
    move: {
      attract: {
        rotate: {
          x: 600,
          y: 1200
        }
      },
      enable: true,
      path: {},
      outModes: {
        bottom: 'out',
        left: 'out',
        right: 'out',
        top: 'out'
      },
      speed: 0.2
    },
    number: {
      limit: 100,
      value: 60
    },
    opacity: {
      animation: {
        speed: 1,
        minimumValue: 0.1
      }
    },
    shadow: {
      blur: 3,
      offset: {
        x: 1,
        y: 1
      }
    },
    size: {
      random: {
        enable: true
      },
      value: {
        min: 4,
        max: 15
      },
      animation: {
        speed: 20,
        minimumValue: 0.1
      }
    }
  }
}
  ```
</details>

## Is your feature request related to a problem? Please describe.

I'd like to be able to add new particles on click **with a random size**, not always the maximum size.

## Describe the solution you'd like

As of now, when using a click event to trigger the `'push'` mode, it **creates a new particle with the maximum size possible**.
From what I see on the [documentation](https://particles.js.org/docs/interfaces/options_interfaces_interactivity_modes_imodes.imodes.html), the only configuration possible for the mode `push` is `quantity`.

**I'd love to have a new attribute like `push.size` with possibles values like `'random'` or a fixed `number` so that new created particles have a size within the possible values** (between the configured `min` and `max`).

**Comment by matteobruni** [comment]
Check out this sample: https://codepen.io/matteobruni/pen/MWmgZxO

Particles have a range size value and when you push them they have a different size.

In your config you have `random: true` and `value` with a range, it's not necessary to use `random` if you specify a range. The random property is deprecated, since the `min/max` it's easier to read and write.

**Comment by Kapcash** [comment]
Nevermind, I'm just stopped my brain for a moment I think.
Actually it's because I use the hover + bubble event, so obviously when I create a new particle from click, it reacts to the hover bubble event and grows to the max bubble size...

Thanks for your very quick anwser! I'm having real fun with your library :)
