### ISSUE TITLE
Can't resolve tsparticle in 'node_modules\react-tsparticles\cjs'

### ISSUE THREAD

**Issue by upasanadeka** [tsparticles/tsparticles#1785]
**Which version are you using?**
^1.30.4

**Is the latest version affected?**

*You can checkout latest version [here](https://www.npmjs.com/package/tsparticles)*

- [x] Yes
- [ ] No

**Which library are you using?**

- [ ] Vanilla JS (`tsparticles`)
- [x] React (`react-tsparticles`)
- [ ] Vue.js 2.x (`particles.vue`)
- [ ] Vue.js 3.x (`particles.vue3`)
- [ ] Angular (`ng-particles`)
- [ ] Svelte (`svelte-particles`)
- [ ] Preact (`preact-particles`)
- [ ] Inferno (`inferno-particles`)
- [ ] jQuery (`jquery-particles`)

<details>
 <summary><b>tsParticles Configuration</b></summary>
  
  ```javascript
  /* add your config here */
  ```
</details>

**Describe the bug**
After running ```npm install react-tsparticles``` command, the following error is occurring: -
``` ./node_modules/react-tsparticles/cjs/particles.js Module not found: Can't resolve 'tsparticles' in '<local path>\node_modules\react-tsparticles\cjs' ```

**To Reproduce**
1. Run command ```npm install react-tsparticles``` 
2. Then run this command ```npm install```
3. Delete "package.lock.json" file
4. Run command ```npm start```
5. Error can be seen in terminal.

**Expected behavior**
The project should run successfully and there should be a Particle JS background on the website.

**Screenshots**
![image](https://user-images.githubusercontent.com/25717722/125104114-a800c280-e0fa-11eb-8b4e-f8fbd765184d.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Brave, Google Schrome
 - Version 1.26.74

**Comment by matteobruni** [comment]
Hi @upasanadeka,

You need to install also the package `tsparticles` since it's a peer dependency now. I'm updating all the READMEs with this additional step.

There's a similar issue #1769 and it's fixed with this extra step so you should be fine too. Let me know if it's not.

**Comment by upasanadeka** [comment]
@matteobruni  Thanks a lot! It is working fine now! 💃🏻
