### ISSUE TITLE
Cannot find module 'vue-property-decorator' - Nuxtjs

### ISSUE THREAD

**Issue by polymer-coder** [tsparticles/tsparticles#1788]
**Which version are you using?**
```
particles.vue": "^2.14.1"
tsparticles": "^1.31.1"
```

**Is the latest version affected?**

- [x] Yes
- [ ] No

**Which library are you using?**

- [ ] Vanilla JS (`tsparticles`)
- [ ] React (`react-tsparticles`)
- [x] Vue.js 2.x (`particles.vue`)
- [ ] Vue.js 3.x (`particles.vue3`)
- [ ] Angular (`ng-particles`)
- [ ] Svelte (`svelte-particles`)
- [ ] Preact (`preact-particles`)
- [ ] Inferno (`inferno-particles`)
- [ ] jQuery (`jquery-particles`)

<details>
 <summary><b>tsParticles Configuration</b></summary>
  
  ```javascript
plugins/particles.js
import Vue from 'vue'
import  Particles  from "particles.vue";

Vue.use(Particles);

  ```
</details>

**Describe the bug**
After upgrading to the latest version I got this error: 
`Cannot find module 'vue-property-decorator'`
Installing tsparticles doesn't seem to fix it

**Expected behavior**
Installing tsparticles and particles.vue works out of the box

**Screenshots**
![image](https://user-images.githubusercontent.com/71771821/125167175-34e46400-e16d-11eb-9b08-5ee6a8be1953.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 91

**Additional context**
Using Nuxtjs

My package.json:
```
{
 ...
  "dependencies": {
    "@googlemaps/js-api-loader": "^1.12.1",
    "@mdi/js": "^5.9.55",
    "@nuxtjs/pwa": "^3.3.5",
    "@nuxtjs/sentry": "^5.1.0",
    "@nuxtjs/sitemap": "^2.4.0",
    "@sentry/browser": "^6.8.0",
    "@sentry/tracing": "^6.8.0",
    "chart.js": "^3.4.1",
    "core-js": "^3.13.1",
    "dayjs": "^1.10.6",
    "firebase": "^8.7.1",
    "nuxt": "^2.15.7",
    "particles.vue": "^2.14.1",
    "tsparticles": "^1.31.1",
    "typeface-roboto": "^1.1.13",
    "vue-property-decorator": "^9.1.2",
    "vuetify": "^2.5.6"
  },
  "devDependencies": {
    "@nuxtjs/vuetify": "^1.12.1",
    "genversion": "^3.0.0",
    "sass": "~1.32.12"
  }
}
```

**Comment by matteobruni** [comment]
Hi @polymer-coder,

These are the peer dependencies of `particles.vue`:

```
"tsparticles": "^1.30.2",
"vue": "<3",
"vue-class-component": "<8",
"vue-property-decorator": "<10"
```

You need to install all of them

**Comment by polymer-coder** [comment]
@matteobruni Thanks! Works perfectly. Would you mind adding that bit to the documentation? It currently says the below: 
![image](https://user-images.githubusercontent.com/71771821/125167688-ce147a00-e16f-11eb-90aa-aa55eae3d043.png)

**Comment by matteobruni** [comment]
Yes, indeed. Thanks for reporting, I didn't notice yesterday when updating docs. I'm reviewing all packages to fix all READMEs
