### ISSUE TITLE
Line flicker at canvas edges

### ISSUE THREAD

**Issue by VagrantAI-c** [tsparticles/tsparticles#1848]
/* DO NOT DELETE THE TEMPLATE BELOW, you can safely delete this line */

**Which version are you using?**
1.31.1

**Is the latest version affected?**

*You can checkout latest version [here](https://www.npmjs.com/package/tsparticles)*

- [X] Yes
- [ ] No

**Which library are you using?**

- [ ] Vanilla JS (`tsparticles`)
- [ ] React (`react-tsparticles`)
- [ ] Vue.js 2.x (`particles.vue`)
- [ ] Vue.js 3.x (`particles.vue3`)
- [X] Angular (`ng-particles`)
- [ ] Svelte (`svelte-particles`)
- [ ] Preact (`preact-particles`)
- [ ] Inferno (`inferno-particles`)
- [ ] jQuery (`jquery-particles`)

<details>
 <summary><b>tsParticles Configuration</b></summary>
  
  ```javascript
{
    particles: {
      number: {
        value: 250,
        density: {
          enable: true,
          value_area: 6894.671861721748
        }
      },
      color: {
        value: '#c0c0c0'
      },
      shape: {
        type: 'circle',
        stroke: {
          width: 0,
          color: '#f1663c'
        },
        polygon: {
          nb_sides: 3
        },
      },
      opacity: {
        value: 1,
        random: false,
        anim: {
          enable: false,
          speed: 1,
          opacity_min: 0.1,
          sync: false
        }
      },
      size: {
        value: 4.008530152163807,
        random: true,
        anim: {
          enable: false,
          speed: 40,
          size_min: 0.1,
          sync: false
        }
      },
      line_linked: {
        enable: true,
        distance: 160.3412060865523,
        color: '#c0c0c0',
        opacity: 0.809723090737089,
        width: 1,
        shadow: {
          enable: false,
          blur: 0,
          color: '',
        },
      },
      move: {
        enable: true,
        speed: 3,
        direction: 'none',
        random: true,
        straight: false,
        out_mode: 'out',
        bounce: false,
        attract: {
          enable: false,
          rotateX: 600,
          rotateY: 1200
        }
      }
    },
    interactivity: {
      detect_on: 'window',
      events: {
        onhover: {
          enable: true,
          mode: 'repulse'
        },
        onclick: {
          enable: true,
          mode: 'push'
        },
        resize: true
      },
    },
}
  ```
</details>

/* DO NOT DELETE THE TEMPLATE ABOVE, you can safely delete this line */

**Describe the bug**
Connected lines are flickering insanely while trying to connect to something behind the screen

**To Reproduce**
1. Go to https://particles.js.org/
2. Look at the edge of the screen
3. See line flickering

**Expected behavior**
No flickering, all lines appearing smoothly

**Screenshots**

https://user-images.githubusercontent.com/3488005/126184400-1e4fca7f-359a-4e1c-9e7e-3ebbe0cc68c2.mp4

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 91

**Smartphone (please complete the following information):**
 - Device: Samsung S9+
 - OS: Android 10
 - Browser: Chrome
 - Version: 91

**Comment by matteobruni** [comment]
Hi @VagrantAI-c,

Thanks for the reporting, I already discussed about this issue in one of the discussions here and a fix is already coming. I'm preparing `1.32` version for the release (PR #1803 if you want to see)

**Comment by VagrantAI-c** [comment]
Thank you for the quick response! I will be looking for it

**Comment by mmilano** [comment]
Thanks for reporting @VagrantAI-c. Am having this issue as well - am reverting to v1.29.2 where the problem does not appear for me

I am using the core tsparticles library (vanilla, not library specific), with Vue2.
