### ISSUE TITLE
particles not loading and TypeError - svelte-particles

### ISSUE THREAD

**Issue by caoash** [tsparticles/tsparticles#1924]
**Which version are you using?**
"svelte": "^3.41.0",
"svelte-particles": "^1.16.1",

**Is the latest version affected?**

*You can checkout latest version [here](https://www.npmjs.com/package/tsparticles)*

- [x] Yes
- [ ] No

**Which library are you using?**

- [ ] Vanilla JS (`tsparticles`)
- [ ] React (`react-tsparticles`)
- [ ] Vue.js 2.x (`particles.vue`)
- [ ] Vue.js 3.x (`particles.vue3`)
- [ ] Angular (`ng-particles`)
- [x] Svelte (`svelte-particles`)
- [ ] Preact (`preact-particles`)
- [ ] Inferno (`inferno-particles`)
- [ ] jQuery (`jquery-particles`)

<details>
 <summary><b>Particles.svelte</b></summary>
  
```javascript
<script>
    import { onMount } from "svelte";
    
    let ParticlesComponent;
    onMount(async () => {
        const module = await import("svelte-particles");
        ParticlesComponent = module.default;
    });
    let particlesConfig = {
        "background": {
            "color": {
            "value": "#232741"
            },
            "position": "50% 50%",
            "repeat": "no-repeat",
            "size": "20%"
        },
        "fullScreen": {
            "enable": true,
            "zIndex": 1
        },
        "interactivity": {
            "events": {
            "onClick": {
                "enable": true,
                "mode": "repulse"
            },
            "onHover": {
                "enable": true,
                "mode": "attract"
            }
            },
            "modes": {
            "attract": {
                "distance": 300,
                "duration": 1
            },
            "bubble": {
                "distance": 250,
                "duration": 2,
                "opacity": 0,
                "size": 0
            },
            "grab": {
                "distance": 400
            },
            "repulse": {
                "duration": 10,
                "factor": 50
            }
            }
        },
        "motion": {
            "disable": true
        },
        "particles": {
            "color": {
                "value": "#ffffff"
            },
            "links": {
                "color": {
                    "value": "#ffffff"
                },
                "distance": 150,
                "opacity": 0.4
            },
            "move": {
                "attract": {
                    "rotate": {
                    "x": 600,
                    "y": 600
                    }
                },
                "enable": true,
                "path": {},
                "outModes": {
                    "bottom": "out",
                    "left": "out",
                    "right": "out",
                    "top": "out"
                },
                "random": true,
                "speed": 1
            },
            "number": {
                "density": {
                    "enable": true
                },
                "value": 160
            },
            "opacity": {
                "random": {
                    "enable": true
                },
                "value": {
                    "min": 0,
                    "max": 1
                },
                "animation": {
                    "enable": true,
                    "speed": 1
                }
            },
            "size": {
                "random": {
                    "enable": true
                },
                "value": {
                    "min": 1,
                    "max": 3
                },
                "animation": {
                    "speed": 4,
                    "minimumValue": 0.3
                }
            }
        }
    }
</script>

<svelte:component 
    this = "{ParticlesComponent}" 
    id = "particles" 
    options = "{particlesConfig}" 
/>

```
</details>

<details>
 <summary><b>index.svelte</b></summary>
  
```javascript
<script>
    import "../styles/tailwind-output.css";
    import Particles from "../lib/Particles.svelte";
</script>



<div class = "bg-blueGray-800">
    <div class="min-h-screen flex flex-col justify-center relative">
        <Particles />
    </div>
</div>

```
</details>

**Describe the bug**

Running the site produces the error `Uncaught (in promise) TypeError: Cannot read property '$$' of undefined` and no particles load. 

**To Reproduce**

1. Run `npm install svelte svelte-particles`
2. Run site with `svelte-kit dev`
3. Open console
4. See error `Uncaught (in promise) TypeError: Cannot read property '$$' of undefined`

**Expected behavior**

Particles should appear with no error.

**Screenshots**

Error:

![image](https://user-images.githubusercontent.com/45920019/127670368-b955f509-d257-4cf5-a9ea-05a1c9ff5967.png)

Line Reference:

![image](https://user-images.githubusercontent.com/45920019/127670524-ae31da88-5f64-47a6-96e4-e4242dcab41b.png)

What shows up on page:

![image](https://user-images.githubusercontent.com/45920019/127670599-f2cdd615-4bd0-47dc-9314-6aba7a97f24a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 OS Version 2009 (Build 19043.1110)
 - Browser: Chrome
 - Version: 92.0.4515.107 (Official Build) (64-bit)

**Additional context**

<details>
<summary> <b> package.json </b> </summary>

```javascript
{
  "name": "~TODO~",
  "version": "0.0.1",
  "devDependencies": {
    "@sveltejs/kit": "next",
    "@tsconfig/svelte": "^2.0.1",
    "concurrently": "^6.2.0",
    "cross-env": "^7.0.3",
    "eslint": "^7.22.0",
    "eslint-config-prettier": "^8.1.0",
    "eslint-plugin-svelte3": "^3.2.0",
    "postcss-cli": "^8.3.1",
    "prettier": "~2.2.1",
    "prettier-plugin-svelte": "^2.2.0",
    "svelte-check": "^2.2.3",
    "svelte-preprocess": "^4.7.4",
    "typescript": "^4.3.5"
  },
  "dependencies": {
    "autoprefixer": "^10.3.1",
    "svelte": "^3.41.0",
    "svelte-particles": "^1.16.1",
    "tailwindcss": "^2.2.7"
  },
  "type": "module"
}
```
</details>

**Comment by matteobruni** [comment]
Thanks for reporting that @caoash,

I didn't tested `1.16` since I haven't done any change there but only in the core library but something with the transpiler is broken and I'm figuring out what.

For now the workaround is not updating to `1.16` and use `1.15`. When I've an update I'll let you know.

**Comment by matteobruni** [comment]
@caoash I tried downgrading svelte in the project and everything is working as expected, an update of the `svelte` package broke the build.

I've just opened an issue to their repository to see if they can find a solution. Maybe I'm going to release an update with `svelte@~3.8.3` since with that version is working.
