### ISSUE TITLE
Issue with resizing SVGs when resolution changes

### ISSUE THREAD

**Issue by shewitt1** [tsparticles/tsparticles#2074]
### Contact Details

kiestoaltoid@gmail.com

### What do you need?

On window resize and devtools responsive mode, changing the resolution with an SVG mask seems to break the positioning.
![particles1](https://user-images.githubusercontent.com/47036029/130766951-c8070cf4-7bff-4a68-8973-b5a96832c42a.PNG)
Seen here is my positioned particles component, where it is centered on my monitor's resolution. This may be an issue with my knowledge of SVGs, it is my first time implementing one and maybe I am doing something wrong, but this is what it looks like on responsive mode 1920x1080.
![particles2](https://user-images.githubusercontent.com/47036029/130767263-7ab05aaf-64e3-4cd2-aca2-6795fd2d5246.PNG)
As you can see the whole svg shifts instead of resizing, and the particles seem to not be aligned correctly either. 

Updated comment with my current particle config, svg is being hosted on a temporary site right now.
`<Particles
        id="tsparticles"
        options={{
          detectRetina: true,
          fpsLimit: 120,
          background: {
            color: "0B0C10"
          },
          interactivity: {
            detectsOn: "canvas",
            events: {
              onHover: {
                enable: true,
                mode: "grab"
              },
              resize: true
            },
            modes: {
              bubble: {
                distance: 150,
                duration: 50,
                opacity: 1,
                size: 4,
                speed: 3
              }
            }
          },
          particles: {
            color: {
              value: "#66FCF1",
              animation: {
                enable: true,
                speed: 4,
                sync: true
              }
            },
            lineLinked: {
              blink: true,
              color: "random",
              consent: false,
              distance: 15,
              enable: false,
              opacity: 1,
              width: 0.2
            },
            move: {
              attract: {
                enable: false
              },
              bounce: false,
              direction: "none",
              enable: true,
              outMode: "bounce",
              random: true,
              speed: 0.15,
              straight: false
            },
            number: {
              density: {
                enable: false,
                area: 1600
              },
              limit: 0,
              value: 1000
            },
            opacity: {
              animation: {
                enable: true,
                minimumValue: 0.7,
                speed: 3,
                sync: false
              },
              random: false,
              value: 1
            },
            shape: {
              type: "triangle"
            },
            size: {
              animation: {
                enable: false,
                minimumValue: 0.4,
                speed: 40,
                sync: false
              },
              random: true,
              value: 1.5
            }
          },
          polygon: {
            draw: {
              enable: true,
              lineColor: "rgba(255,255,255,0)",
              lineWidth: 1
            },
            move: {
              radius: 0.3
            },
            inlineArrangement: "equidistant",
            scale: 0.8,
            type: "inline",
            url: "https://files.catbox.moe/algf55.svg"
          }}} />`

### Version

1.34.0

### Which library are you using?

React.js (react-tsparticles, react-particles-js)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
Hi @shewitt1,

I made some tests with a triangle used locally. I had the same issue but the SVG was responsible of the displacement because it was not centered in its canvas.
I had a 150x200 triangle not centered in a 400x210 canvas, fixing the SVG fixed the issue.

Try open the SVG in Inkscape (it's a good editor for SVG) and see if it's centered there, there's a tool to adapt the canvas size to the image so it will be centered.
Be careful when saving, export it in a SVG 1.1 simplified version, because Inkscape adds a lot of useless tags.
