### ISSUE TITLE
How can l set init position

### ISSUE THREAD

**Issue by renmu123** [tsparticles/tsparticles#2148]
### What do you need?

l want to set particle in one place, when l click play, they start to move. What can l do to complete this.

### Version

1.3.4

### Which library are you using?

Vanilla (tsparticles)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
There are manual particles options described here: https://particles.js.org/docs/interfaces/Options_Interfaces_IOptions.IOptions.html#manualParticles

Working sample here: https://codepen.io/matteobruni/pen/YzpOZpq

**Comment by renmu123** [comment]
l have resloved, thanks for your help
