### ISSUE TITLE
[Bug]: SvelteKit - svelte-particles disappears when re-navigating after hot module reloading in dev

### ISSUE THREAD

**Issue by p-lau** [tsparticles/tsparticles#2230]
### What happened?

First, I changed a portion of other component code (like changing css in a svelte component)

Normally, when navigating within the domain of the app, the canvas does not disappear as it does not need to reload. However, in `npm dev` of SvelteKit , the particles canvas component disappears completely, and does not reinstance. I believe this is partly due to SvelteKit.

Is there a fix for this? This appears only in dev, so a minor issue.

### Version

1.17.1

### Which library are you using?

Svelte (svelte-particles)

### tsParticles Configuration

```json
{
	"autoPlay": true,
	"backgroundMode": {
		"enable": true,
		"zIndex": -9999
	},
	"detectRetina": true,
	"fpsLimit": 60,
	"interactivity": {
		"detectsOn": "window",
		"events": {
			"onHover": {
				"enable": true,
				"mode": "connect"
			},
			"resize": true
		},
		"modes": {
			"connect": {
				"distance": 100,
				"links": {
					"opacity": 0.1
				},
				"radius": 200
			}
		}
	},
	"particles": {
		"color": {
			"value": "#fff"
		},
		"move": {
			"angle": 0,
			"direction": "bottom",
			"distance": 0,
			"enable": true,
			"outModes": {
				"default": "out"
			},
			"random": true,
			"size": true,
			"speed": 0.5,
			"straight": true,
			"warp": false
		},
		"number": {
			"density": {
				"enable": true,
				"area": 100,
				"factor": 4000
			},
			"limit": 50
		},
		"opacity": {
			"random": {
				"enable": true,
				"minimumValue": 0
			},
			"value": 1,
			"animation": {
				"enable": true,
				"minimumValue": 0,
				"speed": 1,
				"sync": false
			}
		},
		"shape": {
			"type": "triangle"
		},
		"size": {
			"random": {
				"enable": true,
				"minimumValue": 0
			},
			"value": 1.5
		},
		"twinkle": {
			"particles": {
				"enable": true,
				"frequency": 0.001,
				"opacity": 1
			}
		}
	},
	"pauseOnBlur": true,
	"pauseOnOutsideViewport": true
}
```

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
Hi @p-lau,

I’ve seen that SvelteKit uses SSR, maybe with the hot reload it uses that feature, which is not compatible with tsParticles, since it’s a client side only component. I need to do some tests with SvelteKit, this is just a thought after reading its docs.
If you have some SSR configuration you can try yourself for now.
Next.js has a similar issue, it needs another kind of import of the component, but with Next.js the issue it never works without that syntax, maybe is something used only the dev command.
