### ISSUE TITLE
[Bug]: Custom typings of built-in libs are in conflict with the libs from TypeScript 4.4

### ISSUE THREAD

**Issue by jvanoostveen** [tsparticles/tsparticles#2231]
### Contact Details

j.vanoostveen@afas.nl

### What happened?

When installing tsparticles in combination with TS4.4+, the lib.dom.d.ts reports an error because of a collision with typings of `Document` within this library.

```
node_modules/typescript/lib/lib.dom.d.ts:4256:11 - error TS2430: Interface 'Document' incorrectly extends interface 'FontFaceSource'.
  Types of property 'fonts' are incompatible.
    Type 'FontFaceSet' is missing the following properties from type 'FontFaceSet': onloading, onloadingdone, onloadingerror, forEach, and 13 more.

4256 interface Document extends Node, DocumentAndElementEventHandlers, DocumentOrShadowRoot, FontFaceSource, GlobalEventHandlers, NonElementParentNode, ParentNode, XPathEvaluatorBase {
```

I don't understand why there are global definition of the DOM in this library, but it would be preferred they are at least compatible with the built-in definitions provided by TypeScript self.

A minimal repro case can be found here: https://github.com/jvanoostveen/tsparticles-ts4.4

### Version

1.19.1

### Which library are you using?

Vanilla (tsparticles)

### tsParticles Configuration

```json
(any configuration will do...)

confetti(`confettiWrapper`, {
  angle: 90,
  count: 5,
  position: { x: 100, y: 100 },
  spread: 100,
  startVelocity: 75,
  decay: 0.8,
  gravity: 2,
  drift: 0,
  ticks: 75,
  colors: ['#ff0000', '#ff8400', '#ffea00', '#00ff00', '#00bbff', '#0000ff', '#ff00ff'],
  shapes: ['circle'],
  scalar: 1.25,
  zIndex: 2000,
  disableForReducedMotion: true
});
```

### Relevant log output

```shell
node_modules/typescript/lib/lib.dom.d.ts:4256:11 - error TS2430: Interface 'Document' incorrectly extends interface 'FontFaceSource'.
  Types of property 'fonts' are incompatible.
    Type 'FontFaceSet' is missing the following properties from type 'FontFaceSet': onloading, onloadingdone, onloadingerror, forEach, and 13 more.

4256 interface Document extends Node, DocumentAndElementEventHandlers, DocumentOrShadowRoot, FontFaceSource, GlobalEventHandlers, NonElementParentNode, ParentNode, XPathEvaluatorBase {
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
A fix for this issue is coming with 1.35.0, TypeScript 4.4 has a lot of breaking changes in types unfortunately.

**Comment by jvanoostveen** [comment]
Great, sorry I didn't see the PR, searched the issue list for TS4.4, but couldn't find any references thus created this issue. Any idea about planning on this version?

**Comment by matteobruni** [comment]
I think it could be released in some days, I need to add the auto theme switch feature and it will be ready

**Comment by matteobruni** [comment]
1.35.0 has been released, closing this.
