### ISSUE TITLE
tsparticles v. 1.35.0 throws an error "window is not defined" with react-particles-js module v. 3.5.3

### ISSUE THREAD

**Issue by Scorpovi4** [tsparticles/tsparticles#2241]
### What happened?

It throws the error "window is not defined" while building on Gatsby.js with `react-particles-js` v. 3.5.3 package. I spent half of day to define what happened and just let you know about it...

### Version

1.35.0

### Which library are you using?

React.js (react-tsparticles, react-particles-js)

### tsParticles Configuration

```json
default
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
Can you tell me how to reproduce it so I can fix it?

**Comment by Scorpovi4** [comment]
@matteobruni sure, here is my project ... change tsparticles version in package.json to 1.35.0 install packages and run `npm run build` then.

**Comment by matteobruni** [comment]
I'm releasing 1.35.1 with the fix (tested)
