### ISSUE TITLE
Can't Have More Than One Particles Container on a Page

### ISSUE THREAD

**Issue by marktiddy** [tsparticles/tsparticles#2251]
### Contact Details

marktiddy@gmail.com

### What do you need?

I'm trying to have a page that has two instances of tsParticles on it (this worked with particlesJs fine) but I get this error in the browser console and only the first instance appears:

Uncaught (in promise) DOMException: Failed to execute 'append' on 'Document': Only one element on document allowed.

Is there a way to have more than one particles instance? 

### Version

1.34.0

### Which library are you using?

Vanilla (tsparticles)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
Hi @marktiddy 

have you used different ids in the tsParticles load parameters?

checkout this sample: https://codepen.io/matteobruni/pen/XWjLOpQ

**Comment by marktiddy** [comment]
Thank you! That's sorted it. Really appreciate your quick response
