### ISSUE TITLE
Why is this limited to just backgrounds?

### ISSUE THREAD

**Issue by Bilge** [tsparticles/tsparticles#2256]
### What do you need?

Is there some technical reason why the scope if this project is bounded to just backgrounds? I was hoping it would be possible to, for example, animate a particle emitter around the edge of a button to create sparks, for example.

### Version

1.34.1

### Which library are you using?

Vanilla (tsparticles)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
It’s not limited to backgrounds, this is the most common usage, but you can place a `div` or a `canvas` anywhere using CSS and use its id with tsParticles.

**Comment by Bilge** [comment]
Sure, but tracing the outline of a button (and especially one with rounded corners), or more generally, the outline of any DOM element; is not a use-case that is actively supported, right?

**Comment by matteobruni** [comment]
Actually isn't, I've recently added shapes to emitters that can be filled or not, but it's not related to HTML elements.

This could be a thing in a future release anyway.

**Comment by Bilge** [comment]
Maybe it's just me, but I feel like this library can take on a whole new life once you can attach emitters to DOM elements.

**Comment by matteobruni** [comment]
I totally agree, this could be a great plugin.

**Comment by matteobruni** [comment]
This is the closest effect you can achieve with the new emitter shapes feature: https://codepen.io/matteobruni/pen/GREBbbX

**Comment by Bilge** [comment]
Looks like a solid foundation. And I suppose there is facility already for particles to trace the edges of shapes, and for particles to emit particles, to create an animated spark effect?

**Comment by matteobruni** [comment]
I created two shapes (ellipse, rectangle) for emitters [here](https://github.com/matteobruni/tsparticles/tree/main/engine/src/Plugins/Emitters/Shapes) so it can be a good point to start for having custom shapes. Actually there's no out direction, the particle spawns in a point and can go anywhere from it, so it could go also inside, but it's a feature I want to add.

About sparks I don't understand what do you mean, you can animate lot of particle statuses, like color, size, opacity. Even the emitter can follow an animation for emitted particles color (like in the sample)

I've updated the sample with more effects, like custom life duration, different sizes, more animations in the spawn color.

**Comment by Bilge** [comment]
Is there any mechanism for an emitter to trace the outline of a shape, e.g. move along the edge of a rectangle?

**Comment by matteobruni** [comment]
No this is one of the missing feature, you can just set it to a rectangle or ellipse shape, and if it's just the outline or the whole shape, and the particles will spawn everywhere randomly (in the border or in all shape).

Another one missing is setting a source to the emitters so they will be positioned above the source element.

**Comment by Guzzler** [comment]
I would like to pick this up @matteobruni any specific functionality you would like to target with the initial release as this seems like a very broad based issue

**Comment by matteobruni** [comment]
> I would like to pick this up @matteobruni any specific functionality you would like to target with the initial release as this seems like a very broad based issue

I have no preferences, any help is appreciated.
