### ISSUE TITLE
Update Readme files

### ISSUE THREAD

**Issue by matteobruni** [tsparticles/tsparticles#2260]
All the README needs updates, this is a good point to start contributing this project.

Some good contributions:

- Fixing broken links
- Adding more samples
- Translate or fix translations
- Improve code samples with other useful samples

**Comment by keivalya** [comment]
I'd like to try fixing this issue. Can you assign it to me, please?

**Comment by ishitaojha** [comment]
Incase @keivalya  isn't working or needs any help , please assign this to me else no issues 👍🏻

**Comment by matteobruni** [comment]
> Incase @keivalya isn't working or needs any help , please assign this to me else no issues 👍🏻

There are a lot of files that needs updates, I think you can work both on the task

**Comment by HariniJeyaraman** [comment]
Would love to work on this issue, if its still open

**Comment by vj-codes** [comment]
Hey I would also like to be assigned for this task, thankss in advance;) @matteobruni

**Comment by Eunit99** [comment]
I would like to work on this issue in order to translate it. If it is still open, please assign to me.

Thanks

**Comment by DeepakKewadia** [comment]
i would like to also work on this, can you assign it to me please ?

**Comment by roshaan005** [comment]
I will also contribute to this one

**Comment by nayan2306** [comment]
I want to work here can you please assigned me?

**Comment by j1gy45u** [comment]
hey, I'd love to work on this, can you please assign me?

**Comment by intragalactic-stranger** [comment]
Hey, Would you like to assign it to me i would like to translate to my regional language Hindi.

**Comment by Enhmunh-E** [comment]
I'm also translating and actually added a pull request can you assign me this issue? I translated all component readmes to Mongolian.

**Comment by MigueMartelo** [comment]
Hi, @matteobruni can you assign me to translate in Spanish, please.

**Comment by sofiacarballo** [comment]
Hi! I´d like to translate it to Catalan. Could you assign me the issue? Thanks!

**Comment by matteobruni** [comment]
@MigueMartelo and @sofiacarballo sorry there's a limit of 10 assignments, but you can work on it anyway, the PR will be accepted once requested.

**Comment by MigueMartelo** [comment]
Perfect @matteobruni I'll work on it!

**Comment by 0xtdey** [comment]
I am a beginner to open source I would like to work if it is still open.

**Comment by matteobruni** [comment]
> I am a beginner to open source I would like to work if it is still open.

Feel free to contribute, this is still open

**Comment by 0xtdey** [comment]
I have submitted a PR on this.

**Comment by 0xtdey** [comment]
@matteobruni Kindly check I did submit a PR on this. Thank you

**Comment by matteobruni** [comment]
> @matteobruni Kindly check I did submit a PR on this. Thank you

I merged everything this morning.

**Comment by 0xtdey** [comment]
Thank you

**Comment by accidental-feature** [comment]
Howdy, I would like to help if possible! I know there is a limit to 10 assignees though if anyone is ahead of me.

**Comment by matteobruni** [comment]
Thank you, every help is welcome
