### ISSUE TITLE
[Bug]: tsParticles 1.35.1 "TypeError: Cannot read property 'prototype' of undefined"

### ISSUE THREAD

**Issue by knirirr** [tsparticles/tsparticles#2264]
### Contact Details

milo.thurston@oerc.ox.ac.uk

### What happened?

When running tests for a Vue.js project tsparticles 1.3.5 causes them all to fail. Here's an example run:
https://github.com/FAIRsharing/fairsharing.github.io/pull/1236/checks?check_run_id=3718631748

It can be seen that version 1.3.5 is installed:

```
> tsparticles@1.35.1 install /home/runner/work/fairsharing.github.io/fairsharing.github.io/node_modules/particles.vue/node_modules/tsparticles
> node ./scripts/install.js
```

Using an earlier version (1.26.3) avoids this, but Github insists upon installing 1.3.5 every time despite what the package.json file says:

https://github.com/FAIRsharing/fairsharing.github.io/blob/broken_homepage_links/package.json#L37

### Version

1.3.5

### Which library are you using?

Vue.js 2.x (particles.vue)

### tsParticles Configuration

```json
background: {
          color: {
            value: 'transparent'
          }
        },
        fpsLimit: 60,
        particles: {
          color: {
            value: '#1F8EBF'
          },
          links: {
            color: '#1F8EBF',
            distance: 100,
            enable: true,
            opacity: 0.5,
            width: 2
          },
          collisions: {
            enable: true
          },
          move: {
            direction: 'none',
            enable: true,
            outMode: 'bounce',
            random: false,
            speed: 1,
            straight: false
          },
          number: {
            density: {
              enable: true,
              value_area: 300
            },
            value: 50
          },
          opacity: {
            value: 0.5
          },
          shape: {
            type: null
          },
          size: {
            random: true,
            value: 5
          }
        },
        detectRetina: true
      }
    }
```

### Relevant log output

```shell
FAIL  tests/unit/components/Clients/RESTClient.spec.js
  ● RESTClient › can process network errors

    TypeError: Cannot read property 'prototype' of undefined

      at node_modules/tsparticles/Plugins/PolygonMask/pathseg.js:974:31
      at Object.<anonymous> (node_modules/tsparticles/Plugins/PolygonMask/pathseg.js:1532:3)
      at node_modules/tsparticles/Plugins/PolygonMask/plugin.js:53:61
      at loadPolygonMaskPlugin (node_modules/tsparticles/Plugins/PolygonMask/plugin.js:53:13)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
Hi @knirirr,

Thanks for reporting that, I'm going to check it since it's breaking when run when not client-side and it's unexpected.

Anyway, this library is client side only, so it's not designed to be run outside that scope (tests, ssr, node commands, other server environments).

**Comment by knirirr** [comment]
Thanks for looking into this. 
We don't need to test the tsParticles code directly, just to check that the component mounts; the test for the component where it's used is simply this:
https://github.com/FAIRsharing/fairsharing.github.io/blob/broken_homepage_links/tests/unit/components/Navigation/Jumbotron.spec.js
All our tests are broken by this, though.

**Comment by matteobruni** [comment]
@knirirr I've released the .2 version, can you check if it's working now?

**Comment by knirirr** [comment]
Thanks. Testing it locally (still waiting for the Github build) I now see warnings instead of a failure:

```
    console.warn node_modules/tsparticles/Plugins/PolygonMask/pathseg.js:1535
      An error occurred in tsParticles pathseg polyfill. If the Polygon Mask is not working, please open an issue here: https://github.com/matteobruni/tsparticles TypeError: Cannot read property 'prototype' of undefined
at Web/fairsharing.github.io/node_modules/tsparticles/Plugins/PolygonMask/pathseg.js:975:35
          at Object.<anonymous> (Web/fairsharing.github.io/node_modules/tsparticles/Plugins/PolygonMask/pathseg.js:1537:3)
          at Runtime._execModule (Web/fairsharing.github.io/node_modules/jest-runtime/build/index.js:867:68)
          at Runtime._loadModule (Web/fairsharing.github.io/node_modules/jest-runtime/build/index.js:577:12)
          at Runtime.requireModule (Web/fairsharing.github.io/node_modules/jest-runtime/build/index.js:433:10)
          at Runtime.requireModuleOrMock (Web/fairsharing.github.io/node_modules/jest-runtime/build/index.js:598:21)
          at /Users/milo/Work/Web/fairsharing.github.io/node_modules/tsparticles/Plugins/PolygonMask/plugin.js:52:57
          at processTicksAndRejections (internal/process/task_queues.js:97:5)
          at loadPolygonMaskPlugin (Web/fairsharing.github.io/node_modules/tsparticles/Plugins/PolygonMask/plugin.js:52:9)
```

The tests pass, though. 

Edit: Passing on Github too, but with warnings: https://github.com/FAIRsharing/fairsharing.github.io/pull/1236/checks?check_run_id=3722280863

**Comment by matteobruni** [comment]
Yes I've added a try/catch with a warning on the catch block, so it's not blocking. Now I can inspect deeply the issue without worrying about time, at least is not blocking anyone server side.
