### ISSUE TITLE
Writing New Tests

### ISSUE THREAD

**Issue by matteobruni** [tsparticles/tsparticles#2272]
The tests weren't updated for a long time, this could be a great opportunity to improve them. New ones can be created, in components or in the core library, others can be improved. Any addition would help finding and fixing bugs, and cover more code.

**Comment by R055A** [comment]
Hi @matteobruni. This looks very interesting. Can I be assigned for Hacktoberfest 2021, please?

**Comment by eshaanagarwal** [comment]
hi @matteobruni I would like to work on this issue. Can you please assign it to me!

**Comment by nmathew98** [comment]
Hi @matteobruni, could I be assigned to this for Hacktoberfest 2021? Thanks!

**Comment by depimomo** [comment]
Hi @matteobruni , I would like to help on this issue 👍  Can you assign it to me?

**Comment by loud-mouth** [comment]
Hi, @matteobruni, I'd like to help write some tests as part of my Hacktoberfest 2021. Can you assign? Thanks

**Comment by roicoroy** [comment]
Hello @matteobruni,
I would like to help on this task for the acktoberfest 2021, if possible, could assign it to me, please? Thanks!
