### ISSUE TITLE
Improving CONTRIBUTING.md

### ISSUE THREAD

**Issue by matteobruni** [tsparticles/tsparticles#2276]
The CONTRIBUTING.md is outdated and needs some updates, for example it's not mentioned anything about building or running the project.

---

For building the first time:

**Unix**

``` shell
yarn && npx lerna bootstrap && npx lerna run build
```

**Windows**

``` shell
yarn
npx lerna bootstrap
npx lerna run build
```

---

For building local packages it's possible to run only

```
yarn build
```

in every folder with a `package.json` file

---

For running demos

```
yarn start
```

or

```
yarn serve
```

where the `start` commands returns an error (this could be another improvement)

**Comment by MidouWebDev** [comment]
@matteobruni i want to work on it

**Comment by nishihere19** [comment]
Can I work on this issue?

**Comment by utkarshhbtu** [comment]
can i work on this issue

**Comment by ainneo** [comment]
is this being worked on? I would like to do it.

**Comment by timscodebase** [comment]
I submitted a PR https://github.com/matteobruni/tsparticles/pull/2333

**Comment by 0xtdey** [comment]
Is this issue still open?

**Comment by matteobruni** [comment]
> Is this issue still open?

Yes

**Comment by 0xtdey** [comment]
I am working on the file. I hope I am able to add something valuable

**Comment by 0xtdey** [comment]
I just submitted a PR.
