### ISSUE TITLE
[Bug]: Can't scroll the preset in the demo page

### ISSUE THREAD

**Issue by rluvaton** [tsparticles/tsparticles#2283]
**I would like to take this**

-------

### What happened?

Just opened the [Demo links](https://particles.js.org/samples/index.html) in the website and clicked Presets

Some presets are hidden

![bug](https://user-images.githubusercontent.com/16746759/135726819-7a217379-4674-4ce9-a230-ee7c8305f972.png)

### Version

I have no idea

### Which library are you using?

Vanilla (tsparticles)

### tsParticles Configuration

```json
None (this is in the website)
```

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
Thanks for reporting it, I didn't tested it in a smaller screen.

**Comment by rluvaton** [comment]
👍🏻 
The website is in the `website` directory? because there is no `start` script, so I used `npx serve .` but styles are and scripts are not loaded 


![bug](https://user-images.githubusercontent.com/16746759/135727350-12a809dc-d2dc-4dcb-8f2b-c20ca2465cc3.png)

**Comment by matteobruni** [comment]
Yes, the website is there, it's published in the GitHub pages, so you can use VSCode live server with `index.html`. I use the live server of WebStorm for testing it, but I think VScode will work too.

**Comment by rluvaton** [comment]
I use WebStorm

**Comment by rluvaton** [comment]
Just needed to build before, fixed...
