### ISSUE TITLE
Website Preset Page

### ISSUE THREAD

**Issue by mukulsinghal407** [tsparticles/tsparticles#2298]
### Contact Details

mukulsinghal407@gmail.com

### What do you need?

Honestly, this is not an issue as such just some enhancement to the present page of the website it was looking way too raw and outdated. 
So, I customized the button aligned it right and added some background color to make it look more neat and presentable.

I hope you like the changes made.

### Version

1.0.0

### Which library are you using?

Vanilla (tsparticles)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mukulsinghal407** [comment]
#2299 please refer to this PR for the same.

**Comment by matteobruni** [comment]
You need to open a Pull Request to submit changes

**Comment by mukulsinghal407** [comment]
@matteobruni  Please add the hacktoberfest-accepted issue to the PR and this issue. I think that is required for the PR to be accepted.

**Comment by mukulsinghal407** [comment]
![image](https://user-images.githubusercontent.com/79706982/136196429-974a4661-be05-4950-9a71-20f6f8dc75aa.png)
This is what my Hacktoberfest Profile says 😅. This is my first time with Hacktoberfest and open source, sorry for the foolish behaviour.

**Comment by matteomessmer** [comment]
Hi I fixed a link and created a PR, hope it's ok to you. 
I see if I can do something more to contribute!
