### ISSUE TITLE
Update TypeDoc to latest version and migrate custom theme to their custom JSX

### ISSUE THREAD

**Issue by matteobruni** [tsparticles/tsparticles#2306]
Update TypeDoc to latest version and migrate custom theme to their custom JSX

More informations can be found here: https://github.com/matteobruni/tsparticles/pull/2178#issuecomment-922477661

The actual theme just overrides the analytics file to add google ads and clarity scripts. For now it's enough migrating that to the new JSX files.

For any help with TypeDoc you can refer to their repository: https://github.com/TypeStrong/typedoc

**Comment by imankur** [comment]
I'm working on this. Can you assign it to me?

**Comment by matteobruni** [comment]
Working with TypeDoc team to fix this, for now it's updated in `v1`
