### ISSUE TITLE
New Presets

### ISSUE THREAD

**Issue by matteobruni** [tsparticles/tsparticles#2354]
There's always space for new tsParticles presets: https://github.com/matteobruni/tsparticles/tree/main/presets

They are all visible here: https://particles.js.org/samples/presets/index.html

Be creative is the only requirement

**Comment by 0xtdey** [comment]
I would love to work on this issue. Does it mean I will have to create presets of tsparticles and share the link?

**Comment by matteobruni** [comment]
> I would love to work on this issue. Does it mean I will have to create presets of tsparticles and share the link?

You have to create tsParticles templates in this project inside the `presets` folder

**Comment by 0xtdey** [comment]
Okay, thank you for the response :)
