### ISSUE TITLE
[Feature Request] React Native support

### ISSUE THREAD

**Issue by adastra-react** [tsparticles/tsparticles#2439]
### Contact Details

sunielengland22@gmail.com

### What is your request?

Can i use this in react native?

### Version

1.37.2

### Which library are you using?

React.js (react-tsparticles, react-particles-js)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
Hi @adastra-react,

Actually is not supported `react-native`. I started trying that some time ago [here](https://github.com/matteobruni/tsparticles/pull/1196) but the canvas on mobile devices is not working and I'm not that specialized about that to know how to fix that.

**Comment by adastra-react** [comment]
Thank you for your the reply

**Comment by princefishthrower** [comment]
@matteobruni - this could potentially be done, but as you said, `canvas` can't be used in React Native. Instead, we'd have to port the existing logic to something like React Native's `Animated` module. Not sure how much in the code is coupled to canvas directly. However, I'm a daily developer in React Native and having this library work there would be very cool indeed :) I will take a look

**Comment by matteobruni** [comment]
This can be reopened on the React repository <https://github.com/tsparticles/react>
