### ISSUE TITLE
[Bug]: style={} not being applied to Canvas

### ISSUE THREAD

**Issue by arianitu** [tsparticles/tsparticles#2731]
### What happened?

The below style is not being applied

        <Particles
          options={particleOptions}
          style={{
            "position": "absolute",
            "zIndex": "-1"
          }}
        />

### Version

1.37.5

### Which library are you using?

React.js (react-tsparticles, react-particles-js)

### tsParticles Configuration

```json
<Particles
          options={particleOptions}
          style={{
            "position": "absolute",
            "zIndex": "-1"
          }}
        />
```

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
I need to see your `particlesOptions`. If you are not disabling the `fullScreen` options, those styles are going to be overridden.

**Comment by arianitu** [comment]
I am not disabling the fullScreen option. I was just migrating from particleJs. If I disable it, the style does get applied. Thank you!

Maybe I should use fullScreen and change the zIndex? Is there a way to also change the background color  of the canvas? In the old particleJs version I used the style property to set zIndex, backgroundColor and width height was set to 100vh and 100vw respectively to get the full screen effect.

**Comment by arianitu** [comment]
I used:

```
  "background": {
    "color": "#fafafa",
  },
  "fullScreen": {
    "enable": true,
    "zIndex": -1,
  },
  ```
  
  Thank you very much!
