### ISSUE TITLE
React docs improvement suggestions(existing CRA projects and JS examples)

### ISSUE THREAD

**Issue by Kykuy** [tsparticles/tsparticles#2768]
I will preface all written below by saying that I'm a newbie in everything both npm and JS ecosphere related.

1. Running the suggested installation command(`npm install react-tsparticles react`) on an existing CRA project(I'm using v5) breaks the scripts for the app(`npm start`, etc.). If you'd like to use tsparticles on an existing CRA app you should `npm install tsparticles`(the default command) instead. Adding this info under "create-react-app" subsection with a header "Adding tsparticles to an existing create-react-app project" would be great.
2. The "How to use" section contains only TS code, adding the JS version might be helpful for those not familiar with TS.

If you'd like, I could submit a PR for both suggestions.

### Version

1.37.6

### Which library are you using?

React.js (react-tsparticles, react-particles-js)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
Thank you, feel free to submit a PR targeting `v1` branch

**Comment by matteobruni** [comment]
I've checked again the React readme in the how to use section, and it's JavaScript code, not TypeScript.

**Comment by Kykuy** [comment]
> I've checked again the React readme in the how to use section, and it's JavaScript code, not TypeScript.

I've re-checked as well and it was due to the fact I used a class component and used 

```
const particlesInit = (main) => {
    console.log(main);

    // you can initialize the tsParticles instance (main) here, adding custom shapes or presets
  };
```

and

```
const particlesLoaded = (container) => {
    console.log(container);
  };
```

in the main body of the component instead of inside the `render()` method.

My bad, sorry for this false alarm.

**Comment by Kykuy** [comment]
Looking at your last commits it seems like you updated the installation instructions for React as well as other libraries, so it seems like the remaining point of this issue is resolved and can it be closed.

Thanks!
