### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by mutheusalmeida** [tsparticles/tsparticles#2815]
### Contact Details

matheusalmeida016@gmail.com

### What happened?

I don't know what happened but in development mode all the effects works like a charm but in production it's way slow. What am I doing wrong?

### Version

1.38.0

### Which library are you using?

React.js (react-tsparticles, react-particles-js)

### tsParticles Configuration

```json
options={{
        fpsLimit: 60,
        interactivity: {
          events: {
            onClick: {
              enable: false,
              mode: 'push',
            },
            onHover: {
              enable: true,
              mode: 'grab',
              parallax: { enable: true, force: 60, smooth: 10 },
            },
            resize: true,
          },
        },
        particles: {
          color: {
            value: '#fff',
          },
          links: {
            color: '#fff',
            distance: 150,
            enable: true,
            opacity: 0.5,
            width: 3,
          },
          collisions: {
            enable: true,
          },
          move: {
            direction: 'none',
            enable: true,
            outMode: 'bounce',
            random: false,
            speed: 2,
            straight: false,
          },
          number: {
            density: {
              enable: true,
              area: 800,
            },
            value: 100,
          },
          opacity: {
            value: 0.5,
          },
          shape: {
            type: 'circle',
          },
          size: {
            random: true,
            value: 5,
          },
        },
        detectRetina: true,
      }}
```

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
Could be a duplicate of #2809, I've made some tests yesterday and I can't replicate the issue

**Comment by mutheusalmeida** [comment]
I've tried everything and still doesn't work as expected. It's weird because it works just fine in development. The project is deployed on Netlify, could it be a problem with the build tool?

**Comment by matteobruni** [comment]
> I've tried everything and still doesn't work as expected. It's weird because it works just fine in development. The project is deployed on Netlify, could it be a problem with the build tool?

I don't know, the other issue was solved using Webpack, but I don't know more than that.
