### ISSUE TITLE
vite build  'Vue' is not exported by

### ISSUE THREAD

**Issue by ZhongHongLi** [tsparticles/tsparticles#2903]
### Contact Details

www.fz948605929@qq.com

### What happened?

import { Options,Vue} from 'vue-class-component'; error 

error during build:
Error: 'Vue' is not exported by node_modules\vue-class-component\dist\vue-class-component.esm-bundler.js, imported by node_modules\particles.vue3\dist\particles.vue.js

### Version

1.22.0

### Which library are you using?

Vue.js 3.x (particles.vue3)

### tsParticles Configuration

```json
background: {
          color: {
            //背景颜色
            value: '#171912',
          },
        },
        fpsLimit: 60,
        interactivity: {
          events: {
            onClick: {
              enable: true,
              mode: 'push',
            },
            onHover: {
              enable: true,
              mode: 'repulse',
            },
            resize: true,
          },
          modes: {
            bubble: {
              distance: 400,
              duration: 2,
              opacity: 0.8,
              size: 40,
            },
            push: {
              quantity: 4,
            },
            repulse: {
              distance: 200,
              duration: 0.4,
            },
          },
        },
        particles: {
          color: {
            value: '#49B896',
          },
          links: {
            color: '#ffffff',
            distance: 150,
            enable: false,
            opacity: 0.5,
            width: 1,
          },
          collisions: {
            enable: true,
          },
          move: {
            direction: 'none',
            enable: true,
            outMode: 'bounce',
            random: false,
            //粒子移动的速度
            speed: 1,
            straight: false,
          },
          number: {
            density: {
              enable: true,
              value_area: 800,
            },
            value: 80,
          },
          opacity: {
            value: 0.5,
          },
          shape: {
            type: 'circle',
          },
          size: {
            random: true,
            value: 3,
          },
        },
        detectRetina: true,
      }"
```

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
Hi, can you give me some instructions on how to reproduce the issue? I don't know how to create a Vite app. If you have a project that you can share or on GitHub is fine as well.

**Comment by ZhongHongLi** [comment]
The project of our company cannot be uploaded to GitHub ， I'll create a new project to test. If there are still the same problems, I'll upload it to my GitHub



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Matteo ***@***.***&gt;; 
发送时间: 2022年1月20日(星期四) 下午4:16
收件人: ***@***.***&gt;; 
抄送: ***@***.******@***.***&gt;; ***@***.***&gt;; 
主题: Re: [matteobruni/tsparticles] vite build  &#39;Vue&#39; is not exported by (Issue #2903)






嗨,你能给我一些如何复制的问题指示?我不知道如何创建访问页如果你有一个项目，你可以分享或者在 GitHub 上也可以。

—
直接回复此邮件，在 GitHub 上查看或者取消订阅.
GitHub Mobile 上的分流通知IOS 系统或机器人. 
你收到了这是因为你是这个线程的作者。留言 ID ***@***.***与&gt;

**Comment by ZhongHongLi** [comment]
> Hi, can you give me some instructions on how to reproduce the issue? I don't know how to create a Vite app. If you have a project that you can share or on GitHub is fine as well.

Sorry, I just downloaded it from the new package and tried it. There was no error. Excuse me

**Comment by ZhongHongLi** [comment]
Turn this off  pr
