### ISSUE TITLE
Console warn thrown for unknown reason

### ISSUE THREAD

**Issue by adamalston** [tsparticles/tsparticles#2925]
### What happened?

Seeing a console warning show up in [CI](https://github.com/adamalston/v2/runs/4914663081?check_suite_focus=true#step:5:8) for my website:
 >  console.warn
    An error occurred in tsParticles pathseg polyfill. If the Polygon Mask is not working, please open an issue here: https://github.com/matteobruni/tsparticles TypeError: Cannot read properties of undefined (reading 'prototype')
        at /home/runner/work/v2/v2/node_modules/tsparticles/Plugins/PolygonMask/pathseg.js:975:35
        at Object.<anonymous> (/home/runner/work/v2/v2/node_modules/tsparticles/Plugins/PolygonMask/pathseg.js:1548:3)
        at Runtime._execModule (/home/runner/work/v2/v2/node_modules/jest-runtime/build/index.js:1646:24)
        at Runtime._loadModule (/home/runner/work/v2/v2/node_modules/jest-runtime/build/index.js:1185:12)
        at Runtime.requireModule (/home/runner/work/v2/v2/node_modules/jest-runtime/build/index.js:1009:12)
        at Runtime.requireModuleOrMock (/home/runner/work/v2/v2/node_modules/jest-runtime/build/index.js:1210:21)
        at /home/runner/work/v2/v2/node_modules/tsparticles/Plugins/PolygonMask/index.js:51:57
        at loadPolygonMaskPlugin (/home/runner/work/v2/v2/node_modules/tsparticles/Plugins/PolygonMask/index.js:51:9)
        at loadFull (/home/runner/work/v2/v2/node_modules/tsparticles/full.js:20:5)

>    at node_modules/tsparticles/Plugins/PolygonMask/pathseg.js:1546:17
    at Object.<anonymous> (node_modules/tsparticles/Plugins/PolygonMask/pathseg.js:1548:3)
    at node_modules/tsparticles/Plugins/PolygonMask/index.js:51:57

I'm not using any Polygon Masks so unsure why this is showing up. Here is my [particles config](https://github.com/adamalston/v2/blob/master/src/themes/Theme.jsx#L19).

### Version

1.39.0

### Which library are you using?

React.js (react-tsparticles, react-particles-js)

### tsParticles Configuration

```json
{
  particles: {
    number: {
      value: 100,
      density: {
        enable: true,
        area: 800,
      },
    },
    color: {
      value: ['c912ed', '00bfff', '22dd22', 'ffd500', 'ff8000', 'ff2600'],
    },
    shape: {
      type: 'circle',
      stroke: {
        width: 0,
        color: '000',
      },
      polygon: {
        nb_sides: 5,
      },
      image: {
        src: 'img/github.svg',
        width: 100,
        height: 100,
      },
    },
    opacity: {
      value: 0.9,
      random: false,
      anim: {
        enable: false,
        speed: 1,
        opacity_min: 0.5,
        sync: false,
      },
    },
    size: {
      value: 4,
      random: {
        enable: true,
        minimumValue: 2,
      },
      anim: {
        enable: false,
        speed: 30,
        size_min: 0.1,
        sync: true,
      },
    },
    links: {
      enable: true,
      distance: 75,
      color: '999',
      opacity: 0.9,
      width: 1,
      consent: false,
      blink: false,
    },
    move: {
      enable: true,
      speed: 2,
      direction: 'none',
      random: false,
      straight: false,
      out_mode: 'bounce',
      bounce: false,
      attract: {
        enable: false,
        rotateX: 600,
        rotateY: 1200,
      },
    },
  },
  interactivity: {
    detect_on: 'canvas',
    events: {
      onhover: {
        enable: true,
        mode: 'repulse',
      },
      onclick: {
        enable: true,
        mode: 'push',
      },
      resize: true,
    },
    modes: {
      attract: {
        distance: 100,
        duration: 1,
        speed: 5,
      },
      bubble: {
        distance: 400,
        size: 40,
        duration: 2,
        opacity: 8,
        speed: 3,
      },
      grab: {
        distance: 400,
        line_linked: {
          opacity: 1,
        },
      },
      push: {
        particles_nb: 3,
      },
      remove: {
        particles_nb: 2,
      },
      repulse: {
        distance: 100,
        duration: 1,
      },
    },
  },
  retina_detect: true,
  fpsLimit: 60,
  fullScreen: {
    enable: false,
  },
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
Thank you, I’ll have a look on that line. Could be a bug in the polyfill

**Comment by matteobruni** [comment]
@adamalston which browser were you using when this error happened?

**Comment by adamalston** [comment]
Edge - although I don't think the error is browser related because it is thrown in [CI](https://github.com/adamalston/v2/runs/4914663081?check_suite_focus=true#step:5:8) or when I run my project locally and run the tests (`npm run test`).

**Comment by matteobruni** [comment]
Ah ok, the server console can have issues since it’s not a browser. The polyfill is included at the beginning when loading all the plugins
