### ISSUE TITLE
[Bug]: Grab mode opacity doesn't work on local but works on online sample 

### ISSUE THREAD

**Issue by mutheusalmeida** [tsparticles/tsparticles#3060]
### Contact Details

matheusalmeida016@gmail.com

### What happened?

I have an issue with `modes: { grab: { links: { opacity: 0.5 } } }`. It works on [the online sample](https://particles.js.org/samples/index.html#default) but do not on my project.

### Version

^1.39.0

### Which library are you using?

React.js (react-tsparticles, react-particles-js)

### tsParticles Configuration

```json
options={{
          bounce: false,
          fullScreen: {
            enable: false,
          },
          fpsLimit: 60,
          interactivity: {
            events: {
              onHover: {
                enable: true,
                mode: 'grab',
                parallax: {
                  enable: true,
                  force: 60,
                  smooth: 10
                },
              },
              resize: true,
            },
          },
          modes: {
            grab: {
              distance: 100,
              links: {
                opacity: 0.7
              }
            }
          },
          particles: {
            color: {
              value: 'rgba(215,183,246,1)',
            },
            links: {
              color: 'rgba(215,183,246,1)',
              distance: 150,
              enable: true,
              width: 5,
            },
            collisions: {
              enable: true,
            },
            move: {
              direction: 'none',
              enable: true,
              outMode: 'bounce',
              random: false,
              speed: 1.5,
              straight: false,
            },
            number: {
              density: {
                enable: true,
                area: 800,
              },
              value: 100,
            },
            opacity: {
              value: 0.7,
            },
            shape: {
              type: 'circle',
            },
            size: {
              random: true,
              value: 8,
            },
          },
          detectRetina: true,
        }}
```

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
Hi @mutheus,

I created a CodeSandbox here: https://codesandbox.io/s/wonderful-fire-ihwgp?file=/src/App.js

The opacity seems fine, what do you mean is not working? Your configuration is behaving the same on the vanilla JavaScript version, I was not expecting anything different.

I've found an issue in your configuration, maybe that is the problem you were talking about. The `modes` section is outside `interactivity`, but it must be inside of it, also `bounce: false` is not valid in the root object, and not a valid value inside `particles` section where it belongs

**Comment by mutheusalmeida** [comment]
Thanks for your reply. You're right about `modes` section being outside `interactivity`. Where should I put `bounce: false` as the opposite seems to cause a bug on the particles speed?

**Comment by matteobruni** [comment]
> Thanks for your reply. You're right about `modes` section being outside `interactivity`. Where should I put `bounce: false` as the opposite seems to cause a bug on the particles speed?

`collisions { enable: false }` disables particles collisions, the `outMode: "bounce"` is responsible for edge bouncing

**Comment by mutheusalmeida** [comment]
Thanks for your time.
