### ISSUE TITLE
[Bug]: seaAnemone preset refreshes shortly after first render

### ISSUE THREAD

**Issue by IgnusG** [tsparticles/tsparticles#3074]
### What happened?

Using the seaAnemone preset, there is a refresh right after the particles start moving.

![particles-bug](https://user-images.githubusercontent.com/6438760/152352391-3fbda886-b3e0-407d-9df1-20afaa5f4e0e.gif)

This also happens on the official seaAnemone preset demo page: https://particles.js.org/samples/presets/seaAnemone

### Version

In my project it's 1.39.2

### Which library are you using?

Vanilla (tsparticles), React.js (react-tsparticles, react-particles-js)

### tsParticles Configuration

```tsx
function ParticleContainer(props: { className?: string; }) {
  const { className} = props;

  const container = useRef<Container | undefined>(undefined);
  const id = `particles-${preset}`;

  const init = useCallback(async () => {
    const { loadSeaAnemonePreset } = await import(
      "tsparticles-preset-sea-anemone"
    );

    loadSeaAnemonePreset(tsParticles);

  }, []);

  useEffect(() => {
    (async () => {
      await init();

      container.current = await tsParticles.load(id, { preset: "seaAnemone" });
    })();

    return () => container.current?.destroy();
  }, []);

  return <div id={id} />;
}
```

### What browsers are you seeing the problem on?

Firefox, Microsoft Edge

### Relevant log output

```shell
No logs available
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
Thank you, I'm aware of this issue but it's not on my priority list since it happens only when starting the animation. During the startup, the emitters have this issue.

**Comment by IgnusG** [comment]
Seems like this regression has returned since 41 I believe

**Comment by matteobruni** [comment]
Yes, it's a known issue. The fix was more breaking than expected, I'm still inspecting this. I'm trying to understand why the *resize* event is raised twice on startup
