### ISSUE TITLE
[Bug]: Trails longer than 10 leave a gray mark on the canvas

### ISSUE THREAD

**Issue by IgnusG** [tsparticles/tsparticles#3078]
### What happened?

Trails that are set to have length 10 or higher leave a gray mark on the canvas that never disappears. This leads to the canvas eventually filling with zig-zags. Trails that have a length of 10 or lower do not have this problem.

Trails with length 11
![image](https://user-images.githubusercontent.com/6438760/152431179-10758281-9155-4838-810f-a0f5fac8b244.png)

Trails with length 10
![image](https://user-images.githubusercontent.com/6438760/152431260-74c77315-3283-431e-b02c-908332285181.png)

This issue appears on the official demo page https://particles.js.org/samples/index.html#trail

### Version

Locally 1.39.2

### Which library are you using?

Vanilla (tsparticles)

### tsParticles Configuration

```json
{
  "fpsLimit": 120,
  "particles": {
    "color": {
      "value": "#fc6c4b",
      "animation": {
        "enable": true,
        "speed": 15
      }
    },
    "move": {
      "attract": {
        "enable": true,
        "rotate": {
          "distance": 100,
          "x": 2000,
          "y": 2000
        }
      },
      "direction": "none",
      "enable": true,
      "outModes": {
        "default": "destroy"
      },
      "path": {
        "clamp": false,
        "enable": true,
        "delay": {
          "value": 0
        },
        "generator": "polygonPathGenerator",
        "options": {
          "sides": 6,
          "turnSteps": 30,
          "angle": 30
        }
      },
      "random": false,
      "speed": 3,
      "straight": false,
      "trail": {
        "fillColor": "#000",
        "length": 15,
        "enable": true
      }
    },
    "number": {
      "density": {
        "enable": true,
        "area": 800
      },
      "value": 0
    },
    "opacity": {
      "value": 1
    },
    "shape": {
      "type": "circle"
    },
    "size": {
      "value": 2
    }
  },
  "background": {
    "color": "#000"
  },
  "fullScreen": {
    "zIndex": -1
  },
  "detectRetina": true,
  "emitters": {
    "direction": "none",
    "rate": {
      "quantity": 1,
      "delay": 0.25
    },
    "size": {
      "width": 10,
      "height": 10
    },
    "position": {
      "x": 50,
      "y": 50
    }
  }
}
```

### What browsers are you seeing the problem on?

Microsoft Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
Thanks @IgnusG, this is a limitation of the canvas APIs, the fill color with small opacity is not stacking well, instead of recreating the right color it creates a trail.
Creating a trail manually without filling the canvas worsen the performance a lot

**Comment by IgnusG** [comment]
Ah I see. As it is a matter of API performance shall we close this issue then?

**Comment by matteobruni** [comment]
Yeah I think, a lot of other devs are complaining about this issue in every browser, it seems that the browsers are messing with integers and floats and this is the result of that.
