### ISSUE TITLE
Component constantly re-renders 

### ISSUE THREAD

**Issue by Placeblock** [tsparticles/tsparticles#3087]
### What do you need?

I just added the ng-particles tag inside my component like this:
`<ng-particles [id]="'particles'" [options]="particlesOptions"></ng-particles>`

In my component i get some data from a service and i noticed that it calls the function in the service really really often
I commented the ng-particles tag out and then my component called the function in my service only once.

Why does the particle system rerender my component like 60 times per second?

Sorry for my bad english :)
Have a great day 😃 

### Version

2.40.0

### Which library are you using?

Angular (ng-particles)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
Can you share an example where I can reproduce the issue?

**Comment by Placeblock** [comment]
I tried to reproduce it on stackblitz but it gives me an error:

Error in /turbo_modules/tsparticles@1.40.0/tsparticles.min.js (2:3030)
Automatic publicPath is not supported in this browser

https://stackblitz.com/edit/angular-ivy-8e2p8d?file=src/app/app.component.ts

**Comment by matteobruni** [comment]
I've tried creating a new angular test project, external from the monorepo.
These are the steps I've made:

- `ng new ng-test-updated`
- `cd ng-test-updated`
- `npm i ng-particles tsparticles`
- implemented `AfterViewChecked` interface in the `AppComponent` with a `console.log("checked")`
- Added `ng-particles`

But the console.log appears only twice.
