### ISSUE TITLE
[Bug]: Confetti preset does not work anymore

### ISSUE THREAD

**Issue by qortex** [tsparticles/tsparticles#3088]
### What happened?

If I use `confetti` preset, nothing shows up. But if I define my own particles config, it works ok.
I tried replicating the preset config in my own code and nothing shows up, so I suspect the actual config of the preset might be broken?

I have the following:
```html
<ng-particles
  [id]="id"
  [options]="particlesOptions"
  (particlesLoaded)="particlesLoaded($event)"
  (particlesInit)="particlesInit($event)"
></ng-particles>
```

```ts
particlesOptions: IParticlesParams = {
  preset: 'confetti',
};

// ...

particlesInit(main: any): void {
    // Using any of this does not work

    // loadConfettiPreset(main);

    // confetti(this.id, {});

    // confetti(this.id, {
    //   angle: 90,
    //   count: 100,
    //   position: {
    //     x: 50,
    //     y: 10,
    //   },
    //   spread: 150,
    //   startVelocity: 100,
    //   decay: 0.9,
    //   gravity: 3,
    //   drift: 0,
    //   ticks: 2000,
    //   colors: ['#1f1459', '#257ff5', '#56dbc5', '#b30b29'],
    //   shapes: ['square', 'circle'],
    //   scalar: 1,
    //   zIndex: 100,
    //   disableForReducedMotion: true,
    // });
  }
```

But putting full options directly (without the `preset` indirection in the config object) works fine.

So I suspect there is something wrong with the preset not being picked up?

I know my code worked on previous versions, but didn't check in a while.

### Version

1.40.0

### Which library are you using?

Angular (ng-particles)

### tsParticles Configuration

```json
{
  preset: 'confetti',
}
```

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
I didn't notice this until now. You can use `1.39.3` for now, I know where the issue is, but I need some time to fix it.

**Comment by qortex** [comment]
Ah thanks! Unfortunately, that doesn't fix it.

After diving a bit, I have seen that putting a non-null `rate` on the emitter makes particles pop, but the `startCount` is ignored. Does that make sense with what you have in mind?

**Comment by qortex** [comment]
adjusting `particles.number.value` to the particules count kind of imitates the right behaviour, but without the starting position being taken into account.
