### ISSUE TITLE
[Bug]: `exports is not defined` with out-of-the-box Svelte project

### ISSUE THREAD

**Issue by longnguyen2004** [tsparticles/tsparticles#3094]
### Contact Details

nguyen.long.908132@gmail.com

### What happened?

Following the [readme for svelte-particles](https://github.com/matteobruni/tsparticles/tree/main/components/svelte#readme), loading the site results in an `exports is not defined` error, even with a fresh project skeleton. Rollup is also complaining about circular dependencies, so it might be the source of the problem. Using https://github.com/sveltejs/template/commit/8d350b693fb4bd8ecf340841eac22a1cb85d7986.

### Version

1.40.1

### Which library are you using?

Svelte (svelte-particles)

### tsParticles Configuration

```json
none needed, it throws immediately on loading the module
```

### What browsers are you seeing the problem on?

Microsoft Edge

### Relevant log output

```shell
(!) Circular dependencies
node_modules\tsparticles\Core\index.js -> node_modules\tsparticles\Core\Canvas.js -> node_modules\tsparticles\Utils\index.js -> node_modules\tsparticles\Utils\CanvasUtils.js -> node_modules\tsparticles\Utils\ColorUtils.js -> node_modules\tsparticles\Utils\NumberUtils.js -> node_modules\tsparticles\Core\index.js
node_modules\tsparticles\Core\index.js -> node_modules\tsparticles\Core\Canvas.js -> node_modules\tsparticles\Utils\index.js -> node_modules\tsparticles\Utils\CanvasUtils.js -> node_modules\tsparticles\Utils\ColorUtils.js -> node_modules\tsparticles\Utils\NumberUtils.js -> G:\Code\tsParticles test\node_modules\tsparticles\Core\index.js?commonjs-proxy -> node_modules\tsparticles\Core\index.js
node_modules\tsparticles\Core\index.js -> node_modules\tsparticles\Core\Canvas.js -> node_modules\tsparticles\Utils\index.js -> node_modules\tsparticles\Utils\CanvasUtils.js -> node_modules\tsparticles\Utils\ColorUtils.js -> node_modules\tsparticles\Core\index.js
node_modules\tsparticles\Core\index.js -> node_modules\tsparticles\Core\Canvas.js -> node_modules\tsparticles\Utils\index.js -> node_modules\tsparticles\Utils\CanvasUtils.js -> node_modules\tsparticles\Utils\ColorUtils.js -> node_modules\tsparticles\Utils\Utils.js -> node_modules\tsparticles\Core\index.js
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
I've tested my Svelte demo project but this error didn't show up. Can you give me more details about how to replicate this?

**Comment by longnguyen2004** [comment]
Are you using SvelteKit? I'm currently not using SvelteKit yet.

Anyway, this is what I did:
1. `npx degit sveltejs/template`
2. `node scripts/setupTypeScript.js`
3. `npm install svelte-particles`
4. Replace the HTML inside `App.svelte` with a single Particles component:
```svelte
<script>
    import Particles from "svelte-particles";
</script>

<Particles />
```
5. `npm run dev`

This causes Rollup to complain about circular dependencies, and upon loading the site, I got an `exports is not defined` error.

**Comment by longnguyen2004** [comment]
SvelteKit works fine, but can you make it work with old school Svelte? If not, I guess I'll migrate to SvelteKit.

**Comment by matteobruni** [comment]
I never used SvelteKit, but I'll investigate the error later, following your steps

**Comment by matteobruni** [comment]
I've tested your steps and the error showed up.
There are no big differences between the demo project (visible [here](https://github.com/matteobruni/tsparticles/tree/main/demo/svelte)) and that works.

So I tried replacing `npm` with `yarn`, and linking this new demo to the locally built versions, and it started working. That's why my local version works (the monorepo links packages).

This is a really annoying issue 😅

What I've seen, the script taken is the one with `commonjs` instead of the `esm` or `umd`. I need to do more output files tests.

**Comment by longnguyen2004** [comment]
So it's either due to `package.json` misconfiguration, or something within Rollup, since I've tested with SvelteKit, which uses Vite, and everything works fine there.

**Comment by longnguyen2004** [comment]
After digging through the `rollup-plugin-node-resolve` docs, I've narrowed the problem down to the `browser` field in the `package.json`. In the Svelte template, [the `browser` setting is set to `true`](https://github.com/sveltejs/template/blob/8d350b693fb4bd8ecf340841eac22a1cb85d7986/rollup.config.js#L56), which means Rollup will use the file specified in the `browser` field. In this case, it is `index.js`, which is the CommonJS version.

Looking through the package content, I found a folder named `browser`, with an `index.js` file inside. This looks pretty similar to the ESM version of the library. Is this the correct one for module bundlers?

**Comment by matteobruni** [comment]
The `browser` folder is used to build the Webpack file, it's really close to TypeScript because I try to don't strip too much TypeScript code so Webpack can do its magic to bundle everything. Maybe the ESM is the better solution. Thank you for the details, I'm going to read more about the `browser` field of `package.json` file, it gave me so many issues.

**Comment by longnguyen2004** [comment]
A quick look at the [`package.json`](https://docs.npmjs.com/cli/v8/configuring-npm/package-json) docs gives me the following:
- `main`: CommonJS (`index.js`)
- `module`: ESM (`esm/index.js`)
- `browser`: Pre-bundled package for browsers (`tsparticles.min.js`)

Apparently webpack incorrectly uses the `browser` field as the entry point by default, which is not what it's intended for. There was [an issue](https://github.com/webpack/webpack/issues/7646) for this in the past, but nothing has been done. So unpkg and jsdelivr have switched to using their own field to specify the entry point.
The proper solution would be to remove the `browser` field entirely, and let module bundlers fall back to the `module` field. If webpack can handle the esm output, this will be the best solution.

**Comment by longnguyen2004** [comment]
Also, for Rollup, outputting to IIFE or UMD will fail due to a dynamic import, unless `inlineDynamicImports` is set to `true`. I think we should document this in the README.

**Comment by matteobruni** [comment]
> Also, for Rollup, outputting to IIFE or UMD will fail due to a dynamic import, unless `inlineDynamicImports` is set to `true`. I think we should document this in the README.

This absolutely.

About the `"browser"` field in the `package.json` the issue is with Parcel, the React demo breaks with a different value, and looking online it seems a common issue (for example: https://github.com/parcel-bundler/parcel/issues/4914)

**Comment by matteobruni** [comment]
I think I'm going to rewrite the React, Inferno.js and Preact modules since they have an `index.js` file exporting things, but I think a better solution can be found.

**Comment by longnguyen2004** [comment]
I think the components are fine as is, but we should remove the `browser` field from `package.json`. There have been problems with it (https://github.com/webpack/webpack/issues/7646, https://github.com/gatsbyjs/gatsby/issues/3192), and other libraries have removed it from their `package.json` (https://github.com/hirosystems/stacks.js/pull/621, https://github.com/adenvt/webauthn-lib/commit/7923129ec8627ef0e9787a717b5ede763254697c), so we should probably do the same.

**Comment by matteobruni** [comment]
I'm trying a build without it, let's see if everything work without it

**Comment by matteobruni** [comment]
It's working, also when using the package without `yarn link`, I've created the package and installed using the file path to the zipped file, and the svelte demo created with these instructions is working.
I'm going to release an update soon so we can see if this issue is solved.
