### ISSUE TITLE
[Bug]: Using particels Hexagons preset (hexagonPath.json) does not work

### ISSUE THREAD

**Issue by hschaefer123** [tsparticles/tsparticles#3102]
### Contact Details

holger.schaefer@gmail.com

### What happened?

Hi,
I tried to use the particles preset Hexagons (hexagonPath.json) inside particles.vue3: 1.40.0.

The results looks like the Sea Anemone demo, but should be look like a path trail following hexagon shape.

Mayber the polygonPath Generator is not supported/working, or particles.js uses a newer lib version?

Would be great to get this running in the great particles.vue3.

Regards
Holger

### Version

1.40.0

### Which library are you using?

Vue.js 3.x (particles.vue3)

### tsParticles Configuration

```json
<Particles
  id="tsparticleshexagon"
  class="ua-particles"
  url="hexagonPath.json"
/>
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
Please, try updating to `1.40.1`. The `1.40.0` had an issue with emitters. (Duplicate of #3088)

**Comment by hschaefer123** [comment]
Hi,
just updated deps to 1.40.1

The second usage is the hexagonPath.json, which is not rendered as expected.

![tsparticles-issue](https://user-images.githubusercontent.com/2110971/152775593-675dd54b-00ca-487d-bf00-5c1311de3e95.png)

BTW: i  also seems, that it is not possible to change the background color to transparent (or here to a hardcoded color). After start, canvas background always turns to black. If this is not controlable, i will/cannot use the new nice preset.

Regards
Holger

**Comment by matteobruni** [comment]
Two things:

1. The Hexagon Path requires an additional package (https://www.npmjs.com/package/tsparticles-path-polygon, sorry the README is not updated, `loadPolygonPath` this function needs to be called:
    - Before calling `tsParticles.load/loadJSON` when using only the core library, like this: `loadPolygonPath(tsParticles)`
    - In any `init/particlesInit` attribute in the components like React, Vue, Angular, passing the parameter of those functions to the `loadPolygonPath` function
2. That configuration uses the particle trail that is achieved not clearing the canvas and can be possible only with a solid background color, so it can't be transparent

**Comment by hschaefer123** [comment]
Hi Matteo,
thanks for the tips.

I got it runnning.

Concerning the color, i am not using transparent!

My Values:
/particles/color/value: #0e4877
/particles/move/trail/fillColor:  #22272e

But the rendered canvas background color differs from body background.

![tsparticles-issue-color](https://user-images.githubusercontent.com/2110971/152789117-4cdb88b8-440a-46e4-9fd0-330979a57939.png)

Are there options to handle it or can i calc the best possible fillColor nearest to background?

Regards Holger

**Comment by matteobruni** [comment]
I've tested your color, and it becomes a dark gray after a few semi-transparent fills, the trail is achieved by filling the canvas with a color with an opacity calculated with the trail length.
