### ISSUE TITLE
Deprecation warning with folder mapping

### ISSUE THREAD

**Issue by p-lau** [tsparticles/tsparticles#3178]
### What do you need?
Would be nice to not see this, but it's nothing to worry.
I am getting this warning whenever I do `npm run dev` or `npm run build` for svelte-kit.
It showed up once I switched from Node 14 to Node 16.
```
(node:16832) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in 
the "exports" field module resolution of the package at C:\...\node_modules\.pnpm\svelte-particles@1.41.0_svelte@3.46.4\node_modules\tslib\package.json.
Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where the warning was created)
```

A small issue for sure.

### Version

1.41.0

### Which library are you using?

Svelte (svelte-particles)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
Fixed in 1.43.x
