### ISSUE TITLE
[Bug]: Fireworks Background Color does not persist

### ISSUE THREAD

**Issue by brakop** [tsparticles/tsparticles#3495]
### Contact Details

brakop@gmail.com

### What happened?

I duplicated your fireworks codePen (https://codepen.io/matteobruni/pen/yLbYWbO?editors=1111)
To one I could show the issue with:
https://codepen.io/steelon169/pen/wvpwQzy

And simply put, I really love the fireworks effect, but I wanted to use a white background. In the demo I tried full green #0F0, and you'll see the background sort of flickers to green, but ends up black in the end. I didn't see any other issues around this, but I assume from the background option definition (https://particles.js.org/docs/interfaces/Options_Interfaces_Background_IBackground.IBackground.html) that this setting should work even with fireworks? I tried setting opacity to 0 as well, but that makes the green flash transparent, not the black background.

FYI, I also randomly tried this with a background image, same thing, it flickers twice and then is back to black.

I presume this is just me overlooking a config, but I'm not finding it. Cheers.

### Version

1.42.1

### Which library are you using?

Vue.js 2.x (particles.vue)

### tsParticles Configuration

```json
:options="{detectRetina:!0,
            background:{
              color:'#FFF'},
            fpsLimit:40,
            emitters:{
              direction:'top',
              life:{count:0,duration:.1,delay:.1},
              rate:{delay:.5,quantity:1},
              size:{width:100,height:0},
              position:{y:100,x:50}
            },
            particles:{
              number:{value:0},
              destroy:{
                mode:'split',
                split:{
                  count:1,
                  factor:{value:.333333},
                  rate:{value:100},
                  particles:{
                    stroke:{width:0},
                    color:{value:['#ff595e','#ffca3a','#8ac926','#1982c4','#6a4c93']},
                    number:{value:0},
                    collisions:{enable:!1},
                    opacity:{
                      value:{min:.1,max:1},
                      animation:{enable:!0,speed:.7,sync:!1,startValue:'max',destroy:'min'}},
                    shape:{type:'circle'},
                    size:{value:2,animation:{enable:!1}},
                    life:{count:1,duration:{value:{min:1,max:2}}},
                    move:{enable:!0,gravity:{enable:!1},speed:2,direction:'none',random:!0,straight:!1,outMode:'destroy'}
                  }
                }
              },
              life:{count:1},
              shape:{type:'line'},
              size:{
                value:{min:.1,max:50},
                animation:{enable:!0,sync:!0,speed:90,startValue:'max',destroy:'min'}
              },
              stroke:{color:{value:'#ffffff'},width:1},
              rotate:{path:!0},
              move:{
                enable:!0,
                gravity:{
                  acceleration:15,
                  enable:!0,
                  inverse:!0,
                  maxSpeed:100},
                speed:{min:10,max:20},
                outModes:{default:'destroy',top:'none'},
                trail:{fillColor:'#000',enable:!0,length:10}
              }
            }
          }"
```

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
> ### Contact Details
> [brakop@gmail.com](mailto:brakop@gmail.com)
> 
> ### What happened?
> I duplicated your fireworks codePen (https://codepen.io/matteobruni/pen/yLbYWbO?editors=1111) To one I could show the issue with: https://codepen.io/steelon169/pen/wvpwQzy
> 
> And simply put, I really love the fireworks effect, but I wanted to use a white background. In the demo I tried full green #0F0, and you'll see the background sort of flickers to green, but ends up black in the end. I didn't see any other issues around this, but I assume from the background option definition (https://particles.js.org/docs/interfaces/Options_Interfaces_Background_IBackground.IBackground.html) that this setting should work even with fireworks? I tried setting opacity to 0 as well, but that makes the green flash transparent, not the black background.
> 
> FYI, I also randomly tried this with a background image, same thing, it flickers twice and then is back to black.
> 
> I presume this is just me overlooking a config, but I'm not finding it. Cheers.
> 
> ### Version
> 1.42.1
> 
> ### Which library are you using?
> Vue.js 2.x (particles.vue)
> 
> ### tsParticles Configuration
> ```json
> :options="{detectRetina:!0,
>             background:{
>               color:'#FFF'},
>             fpsLimit:40,
>             emitters:{
>               direction:'top',
>               life:{count:0,duration:.1,delay:.1},
>               rate:{delay:.5,quantity:1},
>               size:{width:100,height:0},
>               position:{y:100,x:50}
>             },
>             particles:{
>               number:{value:0},
>               destroy:{
>                 mode:'split',
>                 split:{
>                   count:1,
>                   factor:{value:.333333},
>                   rate:{value:100},
>                   particles:{
>                     stroke:{width:0},
>                     color:{value:['#ff595e','#ffca3a','#8ac926','#1982c4','#6a4c93']},
>                     number:{value:0},
>                     collisions:{enable:!1},
>                     opacity:{
>                       value:{min:.1,max:1},
>                       animation:{enable:!0,speed:.7,sync:!1,startValue:'max',destroy:'min'}},
>                     shape:{type:'circle'},
>                     size:{value:2,animation:{enable:!1}},
>                     life:{count:1,duration:{value:{min:1,max:2}}},
>                     move:{enable:!0,gravity:{enable:!1},speed:2,direction:'none',random:!0,straight:!1,outMode:'destroy'}
>                   }
>                 }
>               },
>               life:{count:1},
>               shape:{type:'line'},
>               size:{
>                 value:{min:.1,max:50},
>                 animation:{enable:!0,sync:!0,speed:90,startValue:'max',destroy:'min'}
>               },
>               stroke:{color:{value:'#ffffff'},width:1},
>               rotate:{path:!0},
>               move:{
>                 enable:!0,
>                 gravity:{
>                   acceleration:15,
>                   enable:!0,
>                   inverse:!0,
>                   maxSpeed:100},
>                 speed:{min:10,max:20},
>                 outModes:{default:'destroy',top:'none'},
>                 trail:{fillColor:'#000',enable:!0,length:10}
>               }
>             }
>           }"
> ```
> 
> ### What browsers are you seeing the problem on?
> Chrome
> 
> ### Relevant log output
> _No response_
> 
> ### Code of Conduct
> * [x]  I agree to follow this project's Code of Conduct

Hello,

The fireworks trail uses a different fill color that can be found in `particles.move.trail.fillColor` options. Try setting that to a non-transparent value and you're done.

One thing is really important to know about the fillColor, it's used to create the trail effect so it's filled gradually using a formula for the alpha value, some colors could result in a different background color, but there's nothing I can do about it except create real trails but the performance will worsen, so it's not something I'll fix in the short time.

**Comment by brakop** [comment]
No worries! That settting did what I needed for now, thanks so much for the fast reply!
