### ISSUE TITLE
Generic Issue

### ISSUE THREAD

**Issue by Prasundas99** [tsparticles/tsparticles#3596]
### Contact Details

prasundas115@gmail.com

### What do you need?

There is a `console.log()` in the node modules

The Log is in Canvas.js line number 236

**Issue**
![image](https://user-images.githubusercontent.com/58937669/159502829-29000b93-84b3-4ede-baf6-a9db69e91d1b.png)

### Version

2.0.3

### Which library are you using?

React.js (react-tsparticles, react-particles-js)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
That console.log was already removed also in 2.x branch (1.42.4 fixed it in v1), but v2 has longer release times since it's still in beta.

Since that console.log is not a major issue, it's called only in one init method once, so it's not worth rushing a release.

This is the PR for 2.0.4: #3597
