### ISSUE TITLE
tsParticles Error in log "adding particle"

### ISSUE THREAD

**Issue by Idas86** [tsparticles/tsparticles#3691]
### Contact Details

@Idas86

### What do you need?

Using tsParticles.js I run into this error in the logs with Chrome: "error adding particle: Error: Particle is overlapping and can't be placed".
The canvas is generated correctly, as well as the animation of the particles. If it weren't for the logs, everything would seem fine.

This is my code added in Drupal site:

```
tsParticles.load("tsparticles", {
  fps_limit:

  fullScreen: {
    enable: true,
    zIndex: -1
  },
  background: {
    color: "tansparent"
  },
  interactivity: {
    detect_on: "canvas",
    events: {
      onclick: { enable: false, mode: ["remove", "push"] },
      onhover: {
        enable: false,
        parallax: { enable: true, force: 100, smooth: 120 }
      },
      resize: true
    },
    modes: {
      bubble: { distance: 400, duration: 2, opacity: 0.5, size: 40, speed: 3 },
      grab: { distance: 400, line_linked: { opacity: 0.3 } },
      push: { particles_nb: 4 },
      remove: { particles_nb: 4 },
      repulse: { distance: 200, duration: 0.4 }
    }
  },
  particles: {
    color: { value: "#ffffff" },
    line_linked: {
      color: "#ffffff",
      distance: 230,
      enable: true,
      opacity: 0.1,
      width: 1,
      triangles: {
        enable: true,
        color: "#ffffff",
        opacity: 0.01
      }
    },
    move: {
      attract: { enable: false, rotateX: 600, rotateY: 1200 },
      bounce: false,
      direction: "none",
      enable: true,
      out_mode: "out",
      random: false,
      speed: 0.5,
      straight: false
    },
    collisions: {
      bounce: {
        horizontal: {
          random: {
            enable: false,
            minimumValue: 0.1
          },
          value: 1
        },
        vertical: {
          random: {
            enable: false,
            minimumValue: 0.1
          },
          value: 1
        }
      },
      enable: true,
      mode: "bounce",
      overlap: {
        enable: false,
        retries: 0
      }
    },
    number: {
      value: 300,
      density: {
        enable: true,
        value_area: 1300
      },
      limit: 150
    },
    opacity: {
      anim: { enable: false, opacity_min: 0.1, speed: 1, sync: false },
      random: false,
      value: 0
    },
    shape: {
      type: "cyrcle",
      stroke: { color: "#FFFFFF", width: 0 },
      polygon: { nb_sides: 1 },
    },
    size: {
      anim: { enable: false, size_min: 0.1, speed: 40, sync: false },
      random: false,
      value: 50
    }
  },
  retina_detect: true,
});
```

### Version

1.42.3

### Which library are you using?

Vanilla (tsparticles)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
> ### Contact Details
> @Idas86
> 
> ### What do you need?
> Using tsParticles.js I run into this error in the logs with Chrome: "error adding particle: Error: Particle is overlapping and can't be placed". The canvas is generated correctly, as well as the animation of the particles. If it weren't for the logs, everything would seem fine.
> 
> This is my code added in Drupal site:
> 
> ```
> tsParticles.load("tsparticles", {
>   fps_limit:
> 
>   fullScreen: {
>     enable: true,
>     zIndex: -1
>   },
>   background: {
>     color: "tansparent"
>   },
>   interactivity: {
>     detect_on: "canvas",
>     events: {
>       onclick: { enable: false, mode: ["remove", "push"] },
>       onhover: {
>         enable: false,
>         parallax: { enable: true, force: 100, smooth: 120 }
>       },
>       resize: true
>     },
>     modes: {
>       bubble: { distance: 400, duration: 2, opacity: 0.5, size: 40, speed: 3 },
>       grab: { distance: 400, line_linked: { opacity: 0.3 } },
>       push: { particles_nb: 4 },
>       remove: { particles_nb: 4 },
>       repulse: { distance: 200, duration: 0.4 }
>     }
>   },
>   particles: {
>     color: { value: "#ffffff" },
>     line_linked: {
>       color: "#ffffff",
>       distance: 230,
>       enable: true,
>       opacity: 0.1,
>       width: 1,
>       triangles: {
>         enable: true,
>         color: "#ffffff",
>         opacity: 0.01
>       }
>     },
>     move: {
>       attract: { enable: false, rotateX: 600, rotateY: 1200 },
>       bounce: false,
>       direction: "none",
>       enable: true,
>       out_mode: "out",
>       random: false,
>       speed: 0.5,
>       straight: false
>     },
>     collisions: {
>       bounce: {
>         horizontal: {
>           random: {
>             enable: false,
>             minimumValue: 0.1
>           },
>           value: 1
>         },
>         vertical: {
>           random: {
>             enable: false,
>             minimumValue: 0.1
>           },
>           value: 1
>         }
>       },
>       enable: true,
>       mode: "bounce",
>       overlap: {
>         enable: false,
>         retries: 0
>       }
>     },
>     number: {
>       value: 300,
>       density: {
>         enable: true,
>         value_area: 1300
>       },
>       limit: 150
>     },
>     opacity: {
>       anim: { enable: false, opacity_min: 0.1, speed: 1, sync: false },
>       random: false,
>       value: 0
>     },
>     shape: {
>       type: "cyrcle",
>       stroke: { color: "#FFFFFF", width: 0 },
>       polygon: { nb_sides: 1 },
>     },
>     size: {
>       anim: { enable: false, size_min: 0.1, speed: 40, sync: false },
>       random: false,
>       value: 50
>     }
>   },
>   retina_detect: true,
> });
> ```
> 
> ### Version
> 1.42.3
> 
> ### Which library are you using?
> Vanilla (tsparticles)
> 
> ### Code of Conduct
> * [x]  I agree to follow this project's Code of Conduct

Your configuration has collisions enabled, and you can choose if particles can overlap when placing. If there's no space found the particle won't be added and an error in the console is written.

The `retries` value tries `n` times to place the particle before throwing the error, but in your config `n = 0` so, if the random position is not available the error is thrown immediately.
