### ISSUE TITLE
[Bug]: NextJs Support Broken?

### ISSUE THREAD

**Issue by ItsKodas** [tsparticles/tsparticles#3909]
### Contact Details

koda@horizons.gg

### What happened?

I've been trying to add this package to my NextJs project for half the day following the NextJs Demo in this repository.
After deciding to download the NextJs demo to see if it was me or the package, its the package, I've tried every way I could think of like dynamically importing presets, etc.

For some reason any time you try adding a preset with NextJs and TsParticles you get the same error every time.
_The demo rep gets the exact same error too._

`error - SyntaxError: Cannot use import statement outside a module`

I have searched all day for a way to use tsParticles with NextJs and nothing is working including the demos in this rep...

### Version

1.43.0

### Which library are you using?

React.js (react-tsparticles, react-particles-js)

### tsParticles Configuration

```json
<TsParticles id='tsparticles' options={{
            preset: 'links',
            fullScreen: {
                zIndex: -1
  }
}} init={async (engine) => await loadLinksPreset(engine)} />
```

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Relevant log output

```shell
ready - started server on 0.0.0.0:3001, url: http://localhost:3001
wait  - compiling...
event - compiled client and server successfully in 4.4s (124 modules)
wait  - compiling / (client and server)...
wait  - compiling...
event - compiled client and server successfully in 1090 ms (460 modules)
wait  - compiling /_error (client and server)...
wait  - compiling...
event - compiled client and server successfully in 113 ms (461 modules)
error - SyntaxError: Cannot use import statement outside a module
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
I need to do more tests, I’ve no errors on build in the repository, maybe it’s the monorepo that has no errors because all packages are linked

**Comment by matteobruni** [comment]
I tested now a new Next.js project, with `1.43.1`, and I got no errors and worked as expected, like the demo project in the repository. Do you have a reproducible example where I can see the issue?

**Comment by ItsKodas** [comment]
> I tested now a new Next.js project, with `1.43.1`, and I got no errors and worked as expected, like the demo project in the repository. Do you have a reproducible example where I can see the issue?

I'll get a rep up when I get home for you to test with, I just downloaded the demo, ran npm install, then ran npm run dev.

**Comment by Kadajett** [comment]
I am experiencing this as well, at line10 of tsparticles/index.js
