### ISSUE TITLE
tsParticles stopped working after upgrading from 1.x to 2.x

### ISSUE THREAD

**Issue by n8sabes** [tsparticles/tsparticles#3910]
### What happened?

Upgrading from `tsparticles 1.43.1` to `tsparticles-engine 2.0.5` isn't working. Are there any migration notes? Also, links to examples in the documentation are broken.

Thanks for the amazing work on this project and for any help get it back up and running.

### Version

2.0.5

### Which library are you using?

Vanilla (tsparticles)

### tsParticles Configuration

```json
const defaultParticles: SingleOrMultiple<RecursivePartial<IOptions>> = {
    "particles": {
        "number": {
            "value": 200,
            "density": {
                "enable": true,
                "value_area": 1000
            }
        },
        "color": {
            "value": "#ffffff"
        },
        "shape": {
            "type": "image",
            "stroke": {
                "width": 3,
                "color": "#fff"
            },
            "polygon": {
                "nb_sides": 5
            },
            "image": {
                "src": SnowflakeImage,
                "width": 512,
                "height": 512
            }
        },
        "opacity": {
            "value": 0.5,
            "random": false,
            "anim": {
                "enable": false,
                "speed": 1,
                "opacity_min": 0.1,
                "sync": false
            }
        },
        "size": {
            "value": 5,
            "random": true,
            "anim": {
                "enable": false,
                "speed": 20,
                "size_min": 0.1,
                "sync": false
            }
        },
        "line_linked": {
            "enable": false,
            "distance": 50,
            "color": "#ffffff",
            "opacity": 0.5,
            "width": 1
        },
        "move": {
            "enable": true,
            "random": false,
            // speed: 5,
            "speed": {
                "min": 2,
                "max": 6
            },
            "direction": "bottom",
            "straight": false,
            "out_mode": "out",
            "bounce": false
        }
    },
    "interactivity": {
        "detectsOn": "window" /* this disables the pointer events on canvas */
    },
    "retina_detect": true
}
```

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
no particles rendering. no error log.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
Have you read this article? https://dev.to/matteobruni/tsparticles-205-is-out-breaking-changes-ahead-keeping-the-1x-support-2n63

I’m updating all the documentation for this migration, these notes will be available in the upcoming GH release

**Comment by n8sabes** [comment]
@matteobruni Thank you so much for the migration articles: [tsParticles2 Releases Series' Articles](https://dev.to/matteobruni/series/16974)

I was able to quickly get my `1.x` code up and running under `2.x` following the [**Migration Steps**](https://dev.to/matteobruni/tsparticles-202-is-out-breaking-changes-ahead-but-keeping-the-1x-support-for-now-f72) steps in Part-1. I will work on optimizing for 2.x as it seems you've made some great steps forward.

You've likely already considered it, but a reference at the **top** of the documentation to this migration serious would be of value until the docs are fully updated.

_I'll leave this issue open for others and may also hit additional bumps while migrating to `2.x`. If you prefer to close this issue, please feel free to do so._

**Comment by matteobruni** [comment]
I'll pin this issue, and I'll close it once the documentation is completed.

**Comment by matteobruni** [comment]
I've created the `2.0.6` release here (https://github.com/matteobruni/tsparticles/releases/tag/tsparticles-engine%402.0.6) where I copied the full [dev.to](https://dev.to/matteobruni/tsparticles-205-is-out-breaking-changes-ahead-keeping-the-1x-support-2n63) article

**Comment by matteobruni** [comment]
The website is being updated soon with some video tutorials, and the documentation is fine for 2.0, closing this reminder

**Comment by steve-taylor** [comment]
If anyone came here from Google trying to upgrade `react-tsparticles` from v1 to v2, here's what worked for me:

1. `npm i react-tsparticles@latest tsparticles@latest`
2. In the module that uses the `Particles` component:
   ```ts
   import {loadFull} from 'tsparticles';
   ```
3. Change
   ```tsx
   <Particles options={options} />
   ```
   to
   ```tsx
   <Particles options={options} init={loadFull} />
   ```

Coming from `1.36.0`, I also had to add the following to my config:
```ts
fullScreen: {
    enable: false
}
```
