### ISSUE TITLE
"Unexpected token" - Svelte TypeScript issue

### ISSUE THREAD

**Issue by JuliaBonita** [tsparticles/tsparticles#3963]
### What happened?

I've been trying to get this to work all day. I think this is related to the fact that I'm using SvelteKit, which has SSR on by default. I already tried installing `svelte-particles` using the suggested dynamic import method, but I still get the error below.

Has anybody actually made this work with SvelteKit? If so, please help.

### Version

2.0.6

### Which library are you using?

Svelte (svelte-particles)

### tsParticles Configuration

```json
/* particles.json */
{
  "links": {
    "enable": true
  },
  "move": {
    "enable": true
  },
  "size": {
    "value": 2
  }
}

/* Particles.svelte component */

<script>
  import { onMount } from "svelte";
  import { loadFull } from "tsparticles";

  let ParticlesComponent;

  onMount(async () => {
    const module = await import("svelte-particles");

    ParticlesComponent = module.default;
  });

  let particlesConfig = 'src/particles.json';

  let onParticlesLoaded = (event) => {
    const particlesContainer = event.detail.particles;

    // you can use particlesContainer to call all the Container class
    // (from the core library) methods like play, pause, refresh, start, stop
  };

  let particlesInit = async (main) => {
    // you can use main to customize the tsParticles instance adding presets or custom shapes
    // this loads the tsparticles package bundle, it's the easiest method for getting everything ready
    // starting from v2 you can add only the features you need reducing the bundle size
    await loadFull(main);
  };
</script>

<svelte:component
  this="{ParticlesComponent}"
  id="tsparticles"
  options="{particlesConfig}"
  on:particlesLoaded="{onParticlesLoaded}"
  particlesInit="{particlesInit}"
/>
```

### What browsers are you seeing the problem on?

Firefox, Chrome

### Relevant log output

```shell
[plugin:vite-plugin-svelte] <path>/node_modules/svelte-particles/src/Particles.svelte: 3:16 Unexpected token
<path>/node_modules/svelte-particles/src/Particles.svelte:3:16
1 |  <script lang="ts">
 2 |      import { afterUpdate, createEventDispatcher } from "svelte";
 3 |      import type { ISourceOptions } from "tsparticles-engine";
                      ^
 4 |      import { tsParticles } from "tsparticles-engine";
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
That error depends on your TypeScript configuration, it's not transpiling TypeScript correctly.

`import type` is a TypeScript 3.7 (or 3.8, I don't remember) syntax.

If you are not using TypeScript, you can remove that line and `lang="ts"` from the script tag

**Comment by JuliaBonita** [comment]
Thank you for your quick reply. I removed those items, but I still get the same error:

```
[plugin:vite-plugin-svelte] <path>/node_modules/svelte-particles/src/Particles.svelte:7:22 Unexpected token
<path>/node_modules/svelte-particles/src/Particles.svelte:7:22
5 |      import { tsParticles } from "tsparticles-engine";
  6 |  
  7 |      export let options: ISourceOptions = {};
                             ^
  8 |      export let url = "";
  9 |      export let id = "tsparticles";
```

To confirm I did exactly what you suggested, here is what the `Particles.svelte` file looks like after I made the modification:

```
<script>
    import { afterUpdate, createEventDispatcher } from "svelte";
    import { tsParticles } from "tsparticles-engine";

    export let options: ISourceOptions = {};
    export let url = "";
    export let id = "tsparticles";
    export let particlesInit;
....
```

Can you think of any other potential causes?

**Comment by matteobruni** [comment]
> 

Same issue, `: ISourceOptions` is TypeScript syntax

**Comment by JuliaBonita** [comment]
Ok, thank you. That resolved the loading issue. I can see the particles now, but they don't move. I saw a similar problem earlier and the only way I could resolve it was to use the CDN version and downgrade to the 1.4x version. But then I can't control the placement of the particles within the component tree. 

This is probably something simple, but is there something more that needs to be configured to make the particles move?

**Comment by matteobruni** [comment]
> 

Can you share a sample project with the same issue? I don't know why particles are not moving

**Comment by JuliaBonita** [comment]
Sure, you can download the "temp" project I created for you at the link below. 
https://drive.google.com/file/d/18yVhg5CwuTfij7bviuJMj1Z4N2ugGiJy/view?usp=sharing

In that project, I stripped out all the irrelevant files and deleted all the Node modules except the `svelte-particles` module. That way you shouldn't need to re-edit the files I edited above. I tested it just before zipping it up for you and the particles still don't move.

Thank you for trying to figure out the problem.

**Comment by matteobruni** [comment]
Ok I found the issue, but I tought the first issue was in your code, instead it was in `svelte-particles` that requires `TypeScript` first, and I've taken note about that, I need to document that better.

This is the working project: https://we.tl/t-HLX3thvCnS

These are the steps made:

- I removed `node_modules` since I wanted a fresh install, and I got your first error and there I noticed the documentation lack. I did some changes to your project as explained here: https://github.com/ivanhofer/sveltekit-typescript-showcase (installing `typescript`, `svelte-preprocess`) and adding a `tsconfig.json` file
- I fixed the configuration import, you were using a `particlesConfig` variable assigning it a `string` with the path, instead you should've imported it (the updated project has the right syntax)
- Ran the project to check that everything was fine, and everything's fixed now

Sorry for the first changes, I tought it was something you made, but was something I need to fix in the documentation.

**Comment by JuliaBonita** [comment]
Thank you. Your updated files have resolved this issue. I really appreciate your help.
