### ISSUE TITLE
[Bug]: Tsparticles glitchy and laggy on firefox

### ISSUE THREAD

**Issue by jodusan** [tsparticles/tsparticles#3976]
### What happened?

None of the examples (eg https://particles.js.org/samples/index.html#chars) work as smooth as on chrome. I use firefox 99.0 on Ubuntu and its all glitchy and laggy. Also the same happens for my react app

### Version

2.0.6

### Which library are you using?

React.js (react-tsparticles, react-particles-js)

### What browsers are you seeing the problem on?

Firefox 99.0 on Ubuntu 20.04

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
Hi @jodusan,
I don't have any Ubuntu installed, what are the PC specs or screen resolution? I tested it on Firefox on my Mac and it works fine (and it's not the only app running).

**Comment by jodusan** [comment]
I7-8700, 1080ti nvidia, 4k screen its also laggy on firefox ubuntu 22.04 dell 9570 laptop

**Comment by RandomTrickster** [comment]
It works perfectly fine for me on Arch Linux Firefox.
