### ISSUE TITLE
New package naming

### ISSUE THREAD

**Issue by matteobruni** [tsparticles/tsparticles#3977]
Version 2.x introduced a lot of new packages, almost every feature has a plugin package now but the component packages have some different versions and names.

Since I'd like to have the same version for the whole project, and a better naming, all packages, except `"tsparticles"` will be moved to the `@tsparticles\` npm group.

This is what is going to be with version 3:

`tsparticles-engine` -> `@tsparticles/engine`
`react-tsparticles` -> `@tsparticles/react`
`particles.vue` -> `@tsparticles/vue2`
`vue2-particles` -> `@tsparticles/vue2` (no more double package)
`particles.vue3` -> `@tsparticles/vue3`
`vue3-particles` -> `@tsparticles/vue3`
`svelte-particles` -> `@tsparticles/svelte`
`solid-particles` -> `@tsparticles/solid`
`tsparticles-preset-confetti` -> `@tsparticles/preset-confetti`
`tsparticles-shape-circle` -> `@tsparticles/shape-circle`
`tsparticles-plugin-emitters` -> `@tsparticles/plugin-emitters`

This is a huge breaking change, and that's why `tsparticles` will move to version 3. I planned an options review to remove some of the obsolete properties, but that will be rescheduled to version 4.

**Comment by steve-taylor** [comment]
Would you mind not rushing to deprecate npm packages this time? I still can't figure out how to get `react-tsparticles` v2 working. (I was using v1 without any issues.)

**Comment by danielrs95** [comment]
@matteobruni I'm a new comer and I would like to start helping with this library! (I already im using it on my portfolio page)

**Comment by matteobruni** [comment]
> @matteobruni I'm a new comer and I would like to start helping with this library! (I already im using it on my portfolio page)

This issue is something that will be worked when 3.0 will be planned.

There's a new website project still in progress if you want to help, I don't have time to work on that actually. You can work on that, this is the PR started, you can continue from here https://github.com/matteobruni/tsparticles/pull/4360

If you have discord or slack or telegram you can join there so we can talk easily.
