### ISSUE TITLE
Migrate away from Lerna, that project is officially abandoned

### ISSUE THREAD

**Issue by matteobruni** [tsparticles/tsparticles#3986]
Lerna is officially deprecated, a new monorepo tool is needed. NX looks good, but I need to look if it suits this project perfectly or if other tools are needed. Also, RushJS seems a good alternative, I tried it once but with all these projects it may take forever to configure since there were no globs when I tried it.

Any external help is welcome, I've only used Lerna with this project.

**Comment by longnguyen2004** [comment]
Lerna is now under stewardship of Nrwl, so it's not abandoned anymore?

**Comment by matteobruni** [comment]
> Lerna is now under stewardship of Nrwl, so it's not abandoned anymore?

I've read that news, but I don't know if they're going to maintain that as well or port it inside NX

**Comment by matteobruni** [comment]
I'm adding the new NX integration in Lerna, closing this.
