### ISSUE TITLE
[Bug]: tsparticles lagging when navigating through components in reactjs

### ISSUE THREAD

**Issue by salek3** [tsparticles/tsparticles#4019]
### Contact Details

sashe.angelovski@aucta.dev

### What happened?

At first init/load the particles are working smooth, but when navigating through components they are getting laggy more and more as I navigate trough components.

### Version

17.0.0

### Which library are you using?

React.js (react-tsparticles, react-particles-js)

### tsParticles Configuration

```json
export default function ParticlesBg() {
  useEffect(() => {
    console.log("mounting particles");
    return () => {
      console.log("unmounting particles");
    };
  }, []);

  const theme = useTheme();

  const particlesInit = async (main) => {
    console.log(main);
    // you can initialize the tsParticles instance (main) here, adding custom shapes or presets
    // this loads the tsparticles package bundle, it's the easiest method for getting everything ready
    // starting from v2 you can add only the features you need reducing the bundle size
    await loadFull(main);
  };

  const particlesLoaded = (container) => {
    console.log(container);
  };

  return (
    <React.Fragment>
      <Particles
        id="tsparticles"
        init={particlesInit}
        loaded={particlesLoaded}
        options={{
          background: {
            color: {
              value: theme?.palette?.background?.default,
            },
          },
          fpsLimit: 30,
          fullScreen: { enable: true, zIndex: -1 },
          interactivity: {
            events: {
              // onClick: {
              //   enable: true,
              //   mode: "push",
              // },
              onHover: {
                enable: true,
                mode: "repulse",
              },
              resize: true,
            },
            modes: {
              push: {
                quantity: 4,
              },
              repulse: {
                distance: 200,
                duration: 0.4,
              },
            },
          },
          particles: {
            color: {
              value: "#acacac",
            },
            links: {
              color: "#acacac",
              distance: 150,
              enable: true,
              opacity: 0.15,
              width: 1,
            },
            collisions: {
              enable: true,
            },
            move: {
              direction: "none",
              enable: true,
              outModes: {
                default: "bounce",
              },
              random: false,
              speed: 1,
              straight: false,
            },
            number: {
              density: {
                enable: true,
                area: 600,
              },
              value: 35,
            },
            opacity: {
              value: 0.15,
            },
            shape: {
              type: "circle",
            },
            size: {
              value: { min: 1, max: 4 },
            },
          },
          detectRetina: true,
        }}
      />
    </React.Fragment>
  );
}

function App() {
  return (
    <>
     /......
              <ParticlesBg></ParticlesBg>
             ....../
  );
}
export default App;
```

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
> ### Contact Details
> [sashe.angelovski@aucta.dev](mailto:sashe.angelovski@aucta.dev)
> 
> ### What happened?
> At first init/load the particles are working smooth, but when navigating through components they are getting laggy more and more as I navigate trough components.
> 
> ### Version
> 17.0.0
> 
> ### Which library are you using?
> React.js (react-tsparticles, react-particles-js)
> 
> ### tsParticles Configuration
> ```json
> export default function ParticlesBg() {
>   useEffect(() => {
>     console.log("mounting particles");
>     return () => {
>       console.log("unmounting particles");
>     };
>   }, []);
> 
>   const theme = useTheme();
> 
>   const particlesInit = async (main) => {
>     console.log(main);
>     // you can initialize the tsParticles instance (main) here, adding custom shapes or presets
>     // this loads the tsparticles package bundle, it's the easiest method for getting everything ready
>     // starting from v2 you can add only the features you need reducing the bundle size
>     await loadFull(main);
>   };
> 
>   const particlesLoaded = (container) => {
>     console.log(container);
>   };
> 
>   return (
>     <React.Fragment>
>       <Particles
>         id="tsparticles"
>         init={particlesInit}
>         loaded={particlesLoaded}
>         options={{
>           background: {
>             color: {
>               value: theme?.palette?.background?.default,
>             },
>           },
>           fpsLimit: 30,
>           fullScreen: { enable: true, zIndex: -1 },
>           interactivity: {
>             events: {
>               // onClick: {
>               //   enable: true,
>               //   mode: "push",
>               // },
>               onHover: {
>                 enable: true,
>                 mode: "repulse",
>               },
>               resize: true,
>             },
>             modes: {
>               push: {
>                 quantity: 4,
>               },
>               repulse: {
>                 distance: 200,
>                 duration: 0.4,
>               },
>             },
>           },
>           particles: {
>             color: {
>               value: "#acacac",
>             },
>             links: {
>               color: "#acacac",
>               distance: 150,
>               enable: true,
>               opacity: 0.15,
>               width: 1,
>             },
>             collisions: {
>               enable: true,
>             },
>             move: {
>               direction: "none",
>               enable: true,
>               outModes: {
>                 default: "bounce",
>               },
>               random: false,
>               speed: 1,
>               straight: false,
>             },
>             number: {
>               density: {
>                 enable: true,
>                 area: 600,
>               },
>               value: 35,
>             },
>             opacity: {
>               value: 0.15,
>             },
>             shape: {
>               type: "circle",
>             },
>             size: {
>               value: { min: 1, max: 4 },
>             },
>           },
>           detectRetina: true,
>         }}
>       />
>     </React.Fragment>
>   );
> }
> 
> function App() {
>   return (
>     <>
>      /......
>               <ParticlesBg></ParticlesBg>
>              ....../
>   );
> }
> export default App;
> ```
> 
> ### What browsers are you seeing the problem on?
> Firefox, Chrome, Safari, Microsoft Edge
> 
> ### Relevant log output
> _No response_
> 
> ### Code of Conduct
> * [x]  I agree to follow this project's Code of Conduct

Please, fill the `Version` field with the `tsParticles` version.

Do you have a reproducible sample? You can create one in CodeSandbox or StackBlitz if you don't want to send files.
