### ISSUE TITLE
"particles.vue": "^3.0.6" empty canvas in Nuxt

### ISSUE THREAD

**Issue by alejosky** [tsparticles/tsparticles#4042]
### What happened?

Ciao!

I saw [your post on dev.to](https://dev.to/matteobruni/how-to-create-beautiful-particles-effect-in-vue-js-2-x-and-3-x-27d8), then decided to adapt your [Codepen example](https://codesandbox.io/s/particlesvue-20-kwsl6) into Nuxt.

So I ran...

```
npx create-nuxt-app nuxt-particles
cd nuxt-particles
npm i particles.vue
```

(the last bit installs particles.vue v3.0.6)

then I created the plugins folder, created there the particles.js file and added the code as shown

```
import Vue from "vue";
import Particles from "particles.vue";

Vue.use(Particles);
```
Finally, I added the plugin into the nuxt.config.js file.

```
  plugins: [{ src: "~/plugins/particles.js", ssr: false }],
```
Now, when I modify the index.vue file with code in App.vue from your Codepen, it just doesn't run as is it supposed to. The output is just an empty canvas. Luckily, when I downgrade particles.vue to v2.11.6 (as in your Codepen), it runs as it should.

Also, there is the same problem with particles.vue3.

No errors were displayed either in the console nor devTools.

package.json
```
  "dependencies": {
    "core-js": "^3.19.3",
    "nuxt": "^2.15.8",
    "particles.vue": "^3.0.6",
    "vue": "^2.6.14",
    "vue-server-renderer": "^2.6.14",
    "vue-template-compiler": "^2.6.14",
    "webpack": "^4.46.0"
  }
```

### tsParticles Version

-

### Which library are you using?

Vue.js 2.x (particles.vue)

### tsParticles Configuration

```json
-
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
Read this: https://dev.to/matteobruni/tsparticles-205-is-out-breaking-changes-ahead-keeping-the-1x-support-2n63

tsParticles 2.x has changes (particles.vue 3.x is using that)

**Comment by alejosky** [comment]
Ah, OK. I get it.

I think it would be a good idea to mention that in their correspondent NPM and Github pages.

Grazie mille!

**Comment by matteobruni** [comment]
> Ah, OK. I get it.
> 
> I think it would be a good idea to mention that in their correspondent NPM and Github pages.
> 
> Grazie mille!

The Vue readme was updated some days ago with all the needed code, on NPM is still old but I'm working on an update https://github.com/matteobruni/tsparticles/tree/main/components/vue
