### ISSUE TITLE
Generic Issue

### ISSUE THREAD

**Issue by zyonglove** [tsparticles/tsparticles#4073]
### Contact Details

1747069516@qq.com

### What do you need?

I need help!
From vue/cli4.5 to vite2.0, the particle effect is gone and there is no error.

"particles.vue3": "^2.0.6",

### tsParticles Version

2.0.6

### Which library are you using?

Vue.js 3.x (particles.vue3)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
Hi @zyonglove,

I need a reproducible sample or some code to replicate the issue.

Have you seen the readme? https://github.com/matteobruni/tsparticles/tree/main/components/vue3#readme

**Comment by favourwright** [comment]
I have exact same issue,
using Nuxt3 and installed the tsparticles.vue3 package...

no errors after defining plugin, but no particles

**Comment by matteobruni** [comment]
> I have exact same issue, using Nuxt3 and installed the tsparticles.vue3 package...
> 
> no errors after defining plugin, but no particles

Hi @favourwright, as I said to @favourwright I need some code to reproduce the issue. The code in the Readme is working as expected

There's another issue here https://github.com/matteobruni/tsparticles/issues/4042 that could be the same as yours

**Comment by favourwright** [comment]
@matteobruni for my case, you can reproduce from https://github.com/favourwright/portfolio-nuxt3

**Comment by matteobruni** [comment]
> @matteobruni for my case, you can reproduce from https://github.com/favourwright/portfolio-nuxt3

https://github.com/matteobruni/tsparticles/tree/main/components/vue3#readme

Read this readme please, you are missing some code. It's the same answer given to #4042 linked in my previous message.

**Comment by zyonglove** [comment]
In the same code, the project created with vuecli is normal, but in the project created by vite, there are exceptions, no errors and no particles

**Comment by matteobruni** [comment]
> In the same code, the project created with vuecli is normal, but in the project created by vite, there are exceptions, no errors and no particles

Share the other project, if it uses the same particles.vue3 version it shouldn’t work since in the sample you sent it’s missing some code

**Comment by matteobruni** [comment]
Nuxt2 example: <https://github.com/tsparticles/nuxt2-particles-demo>
Nuxt3 example: <https://github.com/tsparticles/nuxt3-particles-demo>
