### ISSUE TITLE
`tsparticles-move-base` README is for `tsparticles-light-interaction`

### ISSUE THREAD

**Issue by longnguyen2004** [tsparticles/tsparticles#4135]
### Contact Details

nguyen.long.908132@gmail.com

### What do you need?

The README for `tsparticles-move-base` is wrong, and is referring to `tsparticles-interaction-light` instead.

### tsParticles Version

2.0.6

### Which library are you using?

Vanilla (tsparticles), Svelte (svelte-particles)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
Already fixed in dev branch
