### ISSUE TITLE
Add Border radius to images in shape options

### ISSUE THREAD

**Issue by rudevdr** [tsparticles/tsparticles#4184]
### Contact Details

gudayschief@gmail.com

### What is your request?

Currently the object in `particles.shape.options.images` uses `src`, `width` and `height`

I wanted to know what if we can have more css attributes like `border-radius`.

Is there any workaround to add `border-radius` in images for now?

### tsParticles Version

2.0.6

### Which library are you using?

React.js (react-tsparticles, react-particles-js)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
It's not actually possible to apply styles to images drawn inside a canvas, you can try it yourself here: https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_canvas_drawimage

If you find a way, you can create a custom shape yourself like this rounded rectangle: https://github.com/matteobruni/tsparticles/tree/main/shapes/rounded-rect

**Comment by rudevdr** [comment]
Thanks, that is informative!

Is there any way to make background gradient? I can't find options for it. @matteobruni

**Comment by matteobruni** [comment]
> Thanks, that is informative!
> 
> Is there any way to make background gradient? I can't find options for it. @matteobruni

You can set it using the `image` property of the `background` section using CSS, like this tutorial is explaining: https://www.tutorialkart.com/css/css-background-image-linear-gradient/#:~:text=To%20display%20a%20linear%20gradient%20of%20colors%20as,is%20background-image%3A%20linear-gradient%20%28direction%2C%20color1%20stop1%2C%20color2%20stop2%2C...%29%3B
