### ISSUE TITLE
[Bug]: particles.vue3 does not work in the new version of Vue3

### ISSUE THREAD

**Issue by qmzzmzmn** [tsparticles/tsparticles#4203]
### What happened?

particles.vue3@1.11.0 work 

### tsParticles Version

particles.vue3@2.0.6

### Which library are you using?

Vue.js 3.x (particles.vue3)

### tsParticles Configuration

```json
https://codesandbox.io/s/wonderful-gates-hl4jm6?file=/src/App.vue
```

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
Please read the README here: https://github.com/matteobruni/tsparticles/tree/main/components/vue3

You are missing the `particlesInit` method

**Comment by qmzzmzmn** [comment]
Now it works, thks
