### ISSUE TITLE
Problems after V2

### ISSUE THREAD

**Issue by finnie2006** [tsparticles/tsparticles#4320]
### What do you need?

Hello guys,
i made a addon for a gaming panel to add a particle background to the login page, but since V2 off tsparticles it broke, its not really clear to me how to update it, is there someone that can make a pull request or can guide me how to do it? thanks in advance

https://github.com/finnie2006/PteroFreeStuffinstaller/tree/V2/resources/login

### tsParticles Version

latest

### Which library are you using?

React.js (react-tsparticles, react-particles-js)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
Try reading here: https://github.com/matteobruni/tsparticles/issues/3910
