### ISSUE TITLE
Feature Request: Consider updating the docs to support TypeScript

### ISSUE THREAD

**Issue by AlphaByte-RedTeam** [tsparticles/tsparticles#4468]
### Contact Details

andrew.avv03@gmail.com

### What is your request?

On this [documentation](https://github.com/matteobruni/tsparticles/blob/main/components/react/README.md), the docs is still in JavaScript instead of TypeScript. Please consider to update the documentation using full TypeScript support. Thank you.

### tsParticles Version

v2.1.3

### Which library are you using?

React.js (react-tsparticles, react-particles-js)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
If you want, you can open a Pull Request with the missing documentation

**Comment by AlphaByte-RedTeam** [comment]
Ok. I've already opened a PR in PR number #4479
