### ISSUE TITLE
Feature Request - Image Mask Plugin

### ISSUE THREAD

**Issue by Squitch1** [tsparticles/tsparticles#4492]
### What is your request?

Add an option to display an image with particle and interactivity like this [https://codesandbox.io/s/react-particle-image-complex-pbzo9](https://codesandbox.io/s/react-particle-image-complex-pbzo9)

### tsParticles Version

nothing

### Which library are you using?

Vanilla (tsparticles)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
This feature is cool, but it's not something that I'm going to add soon since the polygon mask plugin have a similar effect.

**Comment by jewel109** [comment]
@matteobruni can i work on this ?

**Comment by matteobruni** [comment]
> @matteobruni can i work on this ?

Yeah sure

**Comment by matteobruni** [comment]
@SquitchYT here you can find demo configs:
- Image input: https://github.com/matteobruni/tsparticles/blob/main/demo/vanilla/public/presets/imageMask.json
- Text input: https://github.com/matteobruni/tsparticles/blob/main/demo/vanilla/public/presets/textMask.json
