### ISSUE TITLE
[Bug]: svelte-particles, component doesn't get destroyed properly

### ISSUE THREAD

**Issue by JeremyMoeglich** [tsparticles/tsparticles#4534]
### Contact Details

jeremy.moeglich@gmail.com or just ask in this issue

### What happened?

Destroying the Particles Component (svelte), results in a page slowdown if reinitialized often enough and has even caused the Website to stop because it's out of memory
![image](https://user-images.githubusercontent.com/60170474/181310629-9c19e4eb-ae03-4fa2-8b8a-783302c9016c.png)

What could cause this issue?
DevTools shows that reinitializing the component results in more and more Event listeners, so they might not get destroyed properly.

When do you need to reinitialize the component multiple times?
When you have an SPA, you simply destroy and reinitialize components when switching pages. I also noticed this a lot when working with a dev server as the page slowed down every time I made a change and I had to reload so it's fast again

### tsParticles Version

2.1.3

### Which library are you using?

Svelte (svelte-particles)

### tsParticles Configuration

```json
{
  "particles": {
    "color": {
      "value": "#fff"
    },
    "links": {
      "enable": true,
      "color": "#fff"
    },
    "move": {
      "enable": true
    }
  },
  "fullScreen": {
    "enable": false
  }
}
```

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
It's the same bug of #4385, it will be fixed in `2.2.0` (PR #4341)
