### ISSUE TITLE
Not able to replace particles.vue3 1.41.6 through vue3-particles 2.1.4 using hexagons

### ISSUE THREAD

**Issue by hschaefer123** [tsparticles/tsparticles#4576]
### Contact Details

holger.schaefer@gmail.com

### What happened?

Hi, 
i am not able to replace my particles.vue3 1.41.6 through vue3-particles 2.1.4.

Also a litle bit irritated by package names (renamed?).

Using it this way

```
<template>
  <Particles
    id="tsparticleshexagon"    
    class="ua-particles-hexagon"
    url="/particles/ParticlesHexagon.json"
    :particlesInit="particlesInit"
  />
</template>

<script>
import { defineComponent } from "vue";
import { loadPolygonPath } from "tsparticles-path-polygon";

export default defineComponent({
  name: "ParticlesHexagon",
  methods: {
    particlesInit: function (tsParticles) {
      loadPolygonPath(tsParticles)
    },
  }
});
</script>
```
It is working fine with 1.x but i am not able to upgrade.

Any Ideas?

I just see, that BackgroundColor is fading a little bit, but hex pathes are not drawn.
There is also no error in console.

Regards
Holger

### tsParticles Version

vue3-particles 2.1.4

### Which library are you using?

Vue.js 3.x (vue3-particles, particles.vue3)

### tsParticles Configuration

```json
{
    "fpsLimit": 120,
    "particles": {
        "color": {
            "value": "#0287d0",
            "animation": {
                "enable": true,
                "speed": 10
            }
        },
        "move": {
            "attract": {
                "enable": true,
                "rotate": {
                    "distance": 100,
                    "x": 2000,
                    "y": 2000
                }
            },
            "direction": "none",
            "enable": true,
            "outModes": {
                "default": "destroy"
            },
            "path": {
                "clamp": false,
                "enable": true,
                "delay": {
                    "value": 0
                },
                "generator": "polygonPathGenerator",
                "options": {
                    "sides": 6,
                    "turnSteps": 30,
                    "angle": 30
                }
            },
            "random": false,
            "speed": 3,
            "straight": false,
            "trail": {
                "fillColor": "#0c4878",
                "length": 20,
                "enable": true
            }
        },
        "number": {
            "density": {
                "enable": true,
                "area": 800
            },
            "value": 0
        },
        "shape": {
            "type": "circle"
        },
        "size": {
            "value": 2
        }
    },
    "fullScreen": {
        "enable": false,
        "zIndex": 0
    },
    "detectRetina": true,
    "emitters": {
        "direction": "none",
        "rate": {
            "quantity": 1,
            "delay": 0.25
        },
        "size": {
            "width": 0,
            "height": 0
        },
        "position": {
            "x": 50,
            "y": 50
        }
    }
}
```

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
Have you read the updated readme file of the component? <https://github.com/matteobruni/tsparticles/tree/main/components/vue3#demo-config>

It works both for `particles.vue3` and `vue3-particles`, they're still both supported.

This is the article on the upgrade from v1 to v2: <https://dev.to/matteobruni/tsparticles-205-is-out-breaking-changes-ahead-keeping-the-1x-support-2n63>

Basically, you need to add a bundle or add only the desired packages and load them where you are loading the hexagon path.

I've created a sample for a Discord user few days ago here: https://codesandbox.io/s/loving-monad-8ku465?file=/App.svelte
It's Svelte but the `particlesInit` function is the same, the `loadFull` loads the package `tsparticles` which contains the old `tsparticles` plugins bundled, there's also a `tsparticles-slim` which strips down some plugins so it's smaller in size.

**Comment by hschaefer123** [comment]
Hi Matteo,
sorry, have not catched the upgrade docs.

It is now working adding separated packages:

"tsparticles": "^2.1.4",
"tsparticles-engine": "^2.1.4",
"tsparticles-path-polygon": "^2.1.4",
"vue3-particles": "^2.1.4",


There is still one vue3 issus:

Trying to use
`import Particles from "vue3-particles";`
and
`components: { Particles },`

is throwing an error:
`
vue3-particles.es.js?87b9:5690 Uncaught (in promise) TypeError: app.component is not a function
    at VueParticles (vue3-particles.es.js?87b9:5690:1)
`

This is working for other components, so do i need something addionally?

Regards
Holger

**Comment by matteobruni** [comment]
I've tried launching the demo project now (https://github.com/matteobruni/tsparticles/tree/main/demo/vue3) but I got no errors and it's working as expected. Can you create a reproducible sample on CodeSandbox or StackBlitz? Or share a zip file with the issue.
