### ISSUE TITLE
How to make particles interact with an external div?

### ISSUE THREAD

**Issue by Wollivan** [tsparticles/tsparticles#4654]
### Contact Details

@Wollivan on GitHub

### What is your request?

An option to have the particles interact with another element in the same way they do the mouse.

For example, if the particles are set to move out of the way of the cursor, have them ALSO move out of the way of a div that is moving across the because of a css animation.

### tsParticles Version

2.2.3

### Which library are you using?

React.js (react-particles, react-tsparticles, react-particles-js)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
It's something that already exists, you can see a sample here: https://codepen.io/matteobruni/pen/mdVdPKj

**Comment by Wollivan** [comment]
> It's something that already exists, you can see a sample here: https://codepen.io/matteobruni/pen/mdVdPKj

Oh incredible thanks! I will have a go at implementing this at some point then!
