### ISSUE TITLE
How to start, pause, stop animation in particles.Vue3

### ISSUE THREAD

**Issue by titusdecali** [tsparticles/tsparticles#4697]
### Contact Details

titusdecali@gmail.com

### What do you need?

I have looked everything to figure out how to simply `start` and `pause` the animation in `particle.vue3` and haven't figured out where to fire the methods on.

I am also using the `shape-confetti` plugin.

I've added a ref to the `<Particles>` element, but using that specific ref like: `refName.start()`, `refName.pause` or even `refName.current.start()` says "properties of undefined", which means it's not even the correct element to begin with. 

It's by far the best at particles out there, but is also one of the most difficult to follow libraries I've ever used.

It seems strange to me that all the different versions for each framework don't have their own docs as the Vanilla JS does not translate well into all frameworks.

Sorry for my ignorance on this library, but I want to do a simple thing and don't have time to become an expert on it.

**VERSIONS:**    
"particles.vue3": "1.5.1",     
"tsparticles": "1.22.1",     
"tsparticles-shape-confetti": "1.7.1",

### tsParticles Version

    "particles.vue3": "1.5.1",     "tsparticles": "1.22.1",     "tsparticles-shape-confetti": "1.7.1",

### Which library are you using?

Vue.js 3.x (vue3-particles, particles.vue3)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
Please update to the latest version, `shape-confetti` was deprecated to have a more realistic and configurable effect few months ago.

The object inside the `particlesLoaded` function is the container which can be stored and has `play`/`pause`/`start`/`stop`/`refresh` methods.

**Comment by titusdecali** [comment]
@matteobruni thank you for the quick reply.

I'm able to access the methods directly inside of `particlesLoaded`, but not when returning the inner container.

This makes it extremely hard to use dynamically. Can you please explain the following two issues for me?

I also tried to bind the container to a data() variable and reference the actions from there, but it says `cannot access a class outside of the one that called it` or something similar.

1. How do I use separate methods to fire functions within the container (from outside of it)
2. When the methods are finally working, how do I let the particles keep falling but stop emitting? I tried to use `pause()` but it just froze them in place and they stopped falling.


### TEMPLATE
```
<template>
  <Particles
    id="tsparticles"
    class="confetti"
    :options="options"
    :particles-init="particlesInit"
    :particles-loaded="particlesLoaded"
  />
</template>
```


### SCRIPT
```
<script>
import { mapGetters } from 'vuex'
import { loadFull } from 'tsparticles'

const particlesInit = async (engine) => {
  await loadFull(engine)
}

const particlesLoaded = async (container) => {
  return container
}


export default {
  name: 'CONFETTI',

  data() {
    return {
      options: ...{options here}
  },

  computed: {
    ...mapGetters(['getFireConfetti'])
  },

  watch: {
    getFireConfetti() {
      this.getFireConfetti === true ? this.fireConfetti() : null
    }
  },

  created() {
    setTimeout(() => {
      this.$store.commit('fireConfetti', true) // <-- testing global state-based trigger for 'getFireConfetti' getter above
    }, 6000)
  },

  methods: {
    fireConfetti() {
      console.log('PLAY')
      particlesLoaded.play()

      setTimeout(() => {
        console.log('PAUSE')
        particlesLoaded.play()
      }, 5000)

      setTimeout(() => {
        console.log('STOP')
        this.stopConfetti()
      }, 12000)
    },

    stopConfetti() {
      particlesLoaded.stop()
    }
  }
}
</script>
```



### In case you want to look at my `options`
      options: {
        fullScreen: {
          zIndex: 1
        },
        emitters: [
          {
            position: {
              x: 0,
              y: 30
            },
            rate: {
              quantity: 5,
              delay: 0.15
            },
            particles: {
              move: {
                direction: 'top-right',
                outModes: {
                  top: 'none',
                  left: 'none',
                  default: 'destroy'
                }
              }
            }
          },
          {
            position: {
              x: 100,
              y: 30
            },
            rate: {
              quantity: 5,
              delay: 0.15
            },
            particles: {
              move: {
                direction: 'top-left',
                outModes: {
                  top: 'none',
                  right: 'none',
                  default: 'destroy'
                }
              }
            }
          }
        ],
        particles: {
          color: {
            value: ['#ffffff', '#FF0000']
          },
          move: {
            decay: 0.05,
            direction: 'top',
            enable: true,
            gravity: {
              enable: true
            },
            outModes: {
              top: 'none',
              default: 'destroy'
            },
            speed: {
              min: 10,
              max: 50
            }
          },
          number: {
            value: 0
          },
          opacity: {
            value: 1
          },
          rotate: {
            value: {
              min: 0,
              max: 360
            },
            direction: 'random',
            animation: {
              enable: true,
              speed: 30
            }
          },
          tilt: {
            direction: 'random',
            enable: true,
            value: {
              min: 0,
              max: 360
            },
            animation: {
              enable: true,
              speed: 30
            }
          },
          size: {
            value: {
              min: 0,
              max: 2
            },
            animation: {
              enable: true,
              startValue: 'min',
              count: 1,
              speed: 16,
              sync: true
            }
          },
          roll: {
            darken: {
              enable: true,
              value: 25
            },
            enable: true,
            speed: {
              min: 5,
              max: 15
            }
          },
          wobble: {
            distance: 30,
            enable: true,
            speed: {
              min: -7,
              max: 7
            }
          },
          shape: {
            type: ['circle', 'square', 'image'],
            options: {
              image: [
                {
                  src: 'https://particles.js.org/images/fruits/apple.png',
                  width: 32,
                  height: 32,
                  particles: {
                    size: {
                      value: 16
                    }
                  }
                },
                {
                  src: 'https://particles.js.org/images/fruits/avocado.png',
                  width: 32,
                  height: 32,
                  particles: {
                    size: {
                      value: 16
                    }
                  }
                },
                }
              ]
            }
          }
        }
      }






### On a side note
The guide for [particles.vue3](https://www.npmjs.com/package/particles.vue3) makes zero sense to me.

It shows using `{ fullLoad }` from tsparticles, but shows no import of tsparticles.
It doesn't show how to use particles.vue3 in either the options API or the composition API.

Each version for a different framework should have a separate guide that outlines how to actually use this library.

These really need to be updated.

**Comment by matteobruni** [comment]
Checkout this demo, it shows how to access the `start` method, but it's the same for `play`/`pause`/`stop`/`refresh`: https://codesandbox.io/s/eager-shadow-9bkmsr?file=/src/App.vue

Anyway, the npm link you sent has the import for the `loadFull` (not `fullLoad`) and the functions that need to be exposed from Vue. There are a few different modes of exposing properties, from composition APIs to the old-fashioned `data`/`methods` coming directly from Vue2 that's why it's not specified. A minimum Vue.js knowledge is required. As said many other times `loadFull` is not mandatory, since you could prefer `loadSlim` from `tsparticles-slim` package, or any preset that can be found here, or even loading only some of the available plugins manually. I don't want to force users to install the full library if they don't need it.

**Comment by titusdecali** [comment]
@matteobruni I've updated my previous comment (was hoping to edit it before you looked, but you're too fast! 😂

I've been using Vue for 5 years, and I am VERY familiar with how it works. How this library works... is a different matter entirely. I've never had such difficulty.

My point with `loadFull` above (my bad, didn't see it due to my dark screen reader), was that new devs coming in to use the library need more guidance to quickly understand how to utilize it, and the vast lack of that guidance causes a lot of frustration and doesn't help to spread the use of this cool thing you've created. I've already spent hours on this when (in my opinion) to accomplish the simple task I'm going for I should be able to understand how to access and utilize things within 5-10 minutes of looking at the docs and complete the task. Better docs = more stars, and I think it would have 10k+ if the docs were updated with better examples for each specific framework.

**Comment by matteobruni** [comment]
@titusdecali in your updated code you are using a `function` as an `object`.

```
const particlesLoaded = async (container) => {
  return container
}
```

```
    fireConfetti() {
      console.log('PLAY')
      particlesLoaded.play()

      setTimeout(() => {
        console.log('PAUSE')
        particlesLoaded.play()
      }, 5000)

      setTimeout(() => {
        console.log('STOP')
        this.stopConfetti()
      }, 12000)
    },

    stopConfetti() {
      particlesLoaded.stop()
    }
```

Here you are using `particlesLoaded` without parameters and trying to call a method out of a function. At least you should have used brackets before the dot, but that function is used by the library and it's called every time the `container` object is updated. You must store that object in another variable and you use that instead of the `particlesLoaded`. Consider `particlesLoaded` as an event called every time the particles are updated, events are always `void` functions, like `onClick`.

I've updated my sample so you can see how to store the container and use it outside the `particlesLoaded` function. At the bottom of the page there are two buttons, `start` and `stop` that are using the `myContainer` variable to start and stop the animation.

**Comment by titusdecali** [comment]
@matteobruni Thanks for helping me understand the flow of logic and answering my dumb questions. 

**As a meaningful thankyou, I just sent you a sponsor donation 🤑.** 
For a library of this size, I'm surprised you don't have more sponsors!

I've got it triggering now using a Vuex getter, but I still have the issue I mentioned above about the particles disappearing when I used `pause()`. How can I pause the emits, but still let the particles fall down past the browser fold before using `stop()` ?

![quick particle death](https://user-images.githubusercontent.com/4532534/187853030-68428780-1af9-4006-9dc9-86b70f114029.gif)

**Comment by matteobruni** [comment]
You can see the answers given here: https://github.com/matteobruni/tsparticles/issues/1184#issuecomment-1233153193

You can achieve this with only emitters options as explained there. You can skip the `duration` option if you want to `start`/`stop` the particles programmatically.
