### ISSUE TITLE
New Website Design

### ISSUE THREAD

**Issue by matteobruni** [tsparticles/tsparticles#4725]
The website needs some improvements, there's already a PR (#1262) that I started working on. Any help is welcome. I don't have guidelines about that, be creative and we'll review ideas together.

You can find a forum post on the Discord here: https://discord.com/channels/872061157379301416/1022815383209660447

**This is an open-source library with almost no revenues, all the work here is done for free. There's no way to pay anyone for their contribution for the moment.**

**Comment by Anurag607** [comment]
I would like to work on this issue

**Comment by matteobruni** [comment]
> I would like to work on this issue

You’re free to work on it

**Comment by Mohamed-Ayaan358** [comment]
Could I potentially work on this?

And if you get any information on how you wish to improve the website?

![image](https://user-images.githubusercontent.com/72858215/193384327-1879f914-f0e3-4230-b561-1b466d8e0939.png)

**Comment by matteobruni** [comment]
> Could I potentially work on this?
> 
> And if you get any information on how you wish to improve the website?
> 
> ![image](https://user-images.githubusercontent.com/72858215/193384327-1879f914-f0e3-4230-b561-1b466d8e0939.png)

Yes you can, there is a PR with a new website that needs to be filled with text and samples here #4360 , you can start from that

**Comment by Yash-RajSingh** [comment]
> The website needs some improvements, there's already a PR (#1262) that I started working on. Any help is welcome. I don't have guidelines about that, be creative and we'll review ideas together.
> 
> You can find a forum post on the Discord here: https://discord.com/channels/872061157379301416/1022815383209660447
> 
> **This is an open-source library with almost no revenues, all the work here is done for free. There's no way to pay anyone for their contribution for the moment.**

Hey can you please guide me on how I can contribute to this? I'm a bit new to open source but I have a decent knowledge of Js and web dev.

**Comment by matteobruni** [comment]
Closing this, the website has its own repository now: https://github.com/tsparticles/website
