### ISSUE TITLE
Improve Readme files and documentation

### ISSUE THREAD

**Issue by krupalitrivedi** [tsparticles/tsparticles#4731]
### Contact Details

krupalitrivedi2002@gmail.com

### What do you need?

Greetings,

During Hacktoberfest, I would love to work on making changes in the ReadMe/documentation files present in the repository. These changes can help make the repository look better! I would like if you can assign this issue to me!

### tsParticles Version

v2

### Which library are you using?

Vanilla (tsparticles)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
This could be linked to #1228

**Comment by krupalitrivedi** [comment]
Which one shall I comment on to get it assigned to me? This one or 1228

**Comment by matteobruni** [comment]
This one, just keep in mind #1228 when you work on that

**Comment by OjashKush** [comment]
Issue is still open. Can you tell what need to be added or modified.

**Comment by 0xtdey** [comment]
Is this issue still open? If yes can you kindly assign it to me?

**Comment by yashviradia** [comment]
While using this without `tsparticles` installed, it didn't work for me. Also later in section **How to use** there is line `import { loadFull } from "tsparticles";`. 

So **Installation** section, after `npm install react-particles`, _there must be step of_ `npm install tsparticles`.

**Comment by matteobruni** [comment]
> While using this without `tsparticles` installed, it didn't work for me. Also later in section **How to use** there is line `import { loadFull } from "tsparticles";`.
> 
> So **Installation** section, after `npm install react-particles`, _there must be step of_ `npm install tsparticles`.

You can use `tsparticles-slim`, or any other preset or install plugins manually. This was already discussed, and the installation of `tsparticles` package remain optional and out of documentation
