### ISSUE TITLE
Improve WordPress Plugin

### ISSUE THREAD

**Issue by matteobruni** [tsparticles/tsparticles#4732]
The WordPress plugin actually is just a Gutenberg block, but I think it could fit also as a shortcode, and an Elementor plugin as well.

**Comment by SaarthakMaini** [comment]
Hello @matteobruni ,👋

I would like to contribute to the repository under Hacktoberfest

I have researched what a WordPress plugin, Gutenberg block, shortcode, etc is.

If possible, could you please give some more context on the issue? 

I'll do my research and create a Pull Request in October

Thank You!😁

**Comment by matteobruni** [comment]
> Hello @matteobruni ,👋
> 
> I would like to contribute to the repository under Hacktoberfest
> 
> I have researched what a WordPress plugin, Gutenberg block, shortcode, etc is.
> 
> If possible, could you please give some more context on the issue?
> 
> I'll do my research and create a Pull Request in October
> 
> Thank You!😁

Hi @SaarthakMaini, since not everyone uses Gutenberg for editing their pages, I'd like to add a shortcode (for examples [tsparticles-block]) that can be used by advanced users who prefers using the texteditor instead of the graphical one.

Creating a more complex plugin gives also the possibility to edit default values or to preload plugins instead of the standard `loadFull` function from `tsparticles` package.

Anyway, if you are not familiar with Wordpress, you can try other tasks, like the website redesign.

**Comment by matteobruni** [comment]
Moved to the WordPress repository <https://github.com/tsparticles/wordpress>
