### ISSUE TITLE
[Bug]: Trying to contribute, `lerna bootstrap` fails

### ISSUE THREAD

**Issue by princefishthrower** [tsparticles/tsparticles#4745]
### What happened?

As mentioned in https://github.com/matteobruni/tsparticles/blob/main/CONTRIBUTING.md, a `lerna bootstrap` is required, but I get this:

```shell
lerna bootstrap
lerna notice cli v4.0.0
lerna info versioning independent
lerna ERR! EWORKSPACES Yarn workspaces need to be defined in the root package.json.
lerna ERR! EWORKSPACES See: https://github.com/lerna/lerna/blob/master/commands/bootstrap/README.md#--use-workspaces
```

EDIT: Looking, here: https://github.com/lerna/lerna/blob/main/commands/bootstrap/README.md#--use-workspaces it seems we also need a 

```json
"workspaces": ["packages/*"]
```

in the root `package.json` ? Not sure, I'm not proficient with `lerna`

### tsParticles Version

N/A

### Which library are you using?

Vanilla (tsparticles)

### tsParticles Configuration

```json
N/A
```

### Relevant log output

```shell
lerna bootstrap
lerna notice cli v4.0.0
lerna info versioning independent
lerna ERR! EWORKSPACES Yarn workspaces need to be defined in the root package.json.
lerna ERR! EWORKSPACES See: https://github.com/lerna/lerna/blob/master/commands/bootstrap/README.md#--use-workspaces
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
I need to update the CONTRIBUTING.md, instead of `lerna bootstrap` you should run `pnpm install`

**Comment by princefishthrower** [comment]
Ah perfect. Yes, `pnpm install` works fine! But is the build command then different? Or is it still `npx lerna run build`?

**Comment by matteobruni** [comment]
> Ah perfect. Yes, `pnpm install` works fine! But is the build command then different? Or is it still `npx lerna run build`?

The build is the same, `npx lerna run build` or `lerna run build` are the same. For running without `npx` I think `lerna` should be installed globally.

**Comment by princefishthrower** [comment]
Ok, I still get the workspace issue:

```shell
npx lerna run build
lerna notice cli v4.0.0
lerna info versioning independent
lerna ERR! EWORKSPACES Yarn workspaces need to be defined in the root package.json.
lerna ERR! EWORKSPACES See: https://github.com/lerna/lerna/blob/master/commands/bootstrap/README.md#--use-workspaces
```

**Comment by matteobruni** [comment]
> Ok, I still get the workspace issue:
> 
> ```shell
> npx lerna run build
> lerna notice cli v4.0.0
> lerna info versioning independent
> lerna ERR! EWORKSPACES Yarn workspaces need to be defined in the root package.json.
> lerna ERR! EWORKSPACES See: https://github.com/lerna/lerna/blob/master/commands/bootstrap/README.md#--use-workspaces
> ```

Did you do any changes to the project files? The CI is working with those steps.

You can see steps here: https://github.com/matteobruni/tsparticles/blob/82f6c1bad70dc2dc514ef94d34f92e52d4e95182/.github/workflows/nodejs.yml#L59 (don't worry about the `--no-frozen-lockfile` flag, it's just for the CI, also the `build:ci` command is only for the CI, the standard `build` command fixes some of the linting errors

**Comment by princefishthrower** [comment]
Haven't changed anything yet:

```shell
% git status
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
```

**Comment by matteobruni** [comment]
> Ok, I still get the workspace issue:
> 
> ```shell
> npx lerna run build
> lerna notice cli v4.0.0
> lerna info versioning independent
> lerna ERR! EWORKSPACES Yarn workspaces need to be defined in the root package.json.
> lerna ERR! EWORKSPACES See: https://github.com/lerna/lerna/blob/master/commands/bootstrap/README.md#--use-workspaces
> ```

I don't know why it says `Yarn` workspaces, I'm using `pnpm`. I cloned the repository in another PC some days ago and with `pnpm install` and `npx lerna run build` it worked.

Can you try `pnpx lerna run build`, it uses `pnpm` for `npx` commands, maybe it will work.

**Comment by matteobruni** [comment]
@princefishthrower I completely forgot, there's a bug in `pnpm` `7.12`, use the version `7.11.0` instead
