### ISSUE TITLE
Update Dependency Charts

### ISSUE THREAD

**Issue by matteobruni** [tsparticles/tsparticles#4763]
Many packages have a dependency chart, but they are not updated to their `package.json` files.

To update that, follow the existing format and check every `package.json` file (`dependencies` only)

**Comment by ztjhz** [comment]
I can do this, please assign it to me.

**Comment by ztjhz** [comment]
Can you elaborate on what you mean by packages having a dependency chart but they are not updated to their package.json?

**Comment by matteobruni** [comment]
For example check this readme file: https://github.com/matteobruni/tsparticles/tree/main/presets/stars

At the end of the file, there’s a chart that displays the dependencies. Some charts are outdated or missing. They need to be displayed only in presets, bundles or any other package with multiple tsparticles dependencies
