### ISSUE TITLE
Feature Request: "delay for animation to start" or "delay for first emitter to start"

### ISSUE THREAD

**Issue by ghost** [tsparticles/tsparticles#4766]
### What is your request?

Good morning.

I use the firework preset.
Currently I need to set in JavaScript a command to await 8 seconds before the first firework explosion ever starts to be emitted.
After the first explosion, subsequent explosions follow shortly after, less than a second later.

Is it possible to set just with tsParticles, this initial delay for the first emitter/firework explosion to start? That is, the possibility of set a delay time for the start of tsParticles?

if this option doesn't exist, please consider developing it as "delay for animation to start" or "delay for first emitter to start" as it allows control over starting animations in sequence with other animations.

I migrated all tsParticles from JavaScript to the WordPress block, successfully, thanks to your nice Gutenberg block. This 8 second delay before the fireworks preset is the only preset that I'm not able to migrate.    I'm not experienced in JavaScript. So I'm not able to apply the addeventlistener in the WordPress block.

```
<script>
(async () => {
    const container = await tsParticles.load("tsparticles", {

        /*some options omitted*/

	"duration": 0,
	"emitters": {
		"autoPlay": false,
		"fill": true,
		"life": {
			"wait": false,
			"count": 0,
			"delay": 0.1,
			"duration": 0.1
		},
		"rate": {
			"quantity": 1,
			"delay": 0.25
		},
		"shape": "circle",
		"startCount": 4,
		"size": {
			"mode": "percent",
			"height": 0.1,
			"width": 0.1
		},
		"direction": "top-center",
		"position": {
			"x": 48.75,
			"y": 77.75
		}
	}
    });

    document.addEventListener("DOMContentLoaded", () => {
        setTimeout(() => {
	    container.playEmitter();
        }, 8000);
    });

})();
</script>
```

### tsParticles Version

2.3.1

### Which library are you using?

Vanilla (tsparticles)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
It's something I never thought about, a different initial delay. It will be implemented in the upcoming 2.4.0

**Comment by Cor4zon** [comment]
I can take it. Please assign it to me

**Comment by tomandjerry36** [comment]
I can help you to solve this issue. Please assign me. @marceloaof

**Comment by tomandjerry36** [comment]
I think adding a delay will sort out this issue.
Have you tried..?

**Comment by matteobruni** [comment]
> I think adding a delay will sort out this issue.
> Have you tried..?

The resolution for this issue is to create two options: delay for the root options, and delay for the emitter options. Both must delay the animation for the given number of seconds.

**Comment by tomandjerry36** [comment]
> > I think adding a delay will sort out this issue.
> > Have you tried..?
> 
> The resolution for this issue is to create two options: delay for the root options, and delay for the emitter options. Both must delay the animation for the given number of seconds.

Yes exactly

**Comment by tomandjerry36** [comment]
https://www.freecodecamp.org/news/javascript-settimeout-js-timer-to-delay-n-seconds/

https://www.npmjs.com/package/event-emitter-es6

These Links might help

**Comment by matteobruni** [comment]
> https://www.freecodecamp.org/news/javascript-settimeout-js-timer-to-delay-n-seconds/
> 
> https://www.npmjs.com/package/event-emitter-es6
> 
> These Links might help

There's no need for additional packages, The engine must be kept dependency free. Also, the `setTimeout` for these features is useless, there's already an internal timer using the `requestAnimationFrame` which is more performant.

It's a feature request, this issue requires some code to be implemented in the engine and in the emitters plugin.

I know that it can be achieved using other functions or JS functions or other packages, but adding options for controlling easily the animations is the main topic of this issue. There are other delays in other options, but the two requested are missing and must be added.

If you want to create this, you're welcome to submit a PR. Using `setTimeout`, other packages, or everything that requires the final user to write more code is not the desired solution.

**Comment by matteobruni** [comment]
I'm working on this, and emitters already have this feature, but I forgot about that.

This is a sample config:

```javascript
const config = {
  particles: {
    color: {
      value:"#000"
    },
    move: {
      enable: true,
      outModes: "destroy",
      speed: 5
    },
    number: {
      value: 0
    }
  },
  emitters: {
    life: {
      count: 10, // life count, how many times the emitters will respawn after duration completed
      duration: 5, // duration of the life (not necessary, it's just for showing how life options work)
      delay: 5, // seconds to wait between each life, when wait is true is the initial delay
      wait: true // waits the delay on the first emitter start
    }
  }
}
```

@marceloaof this should help you achieving this. The delay option in the root object will be available starting from `2.4.0` (PR: #4753)

**Comment by ghost** [comment]
To the people who got involved in this issue and especially @matteobruni

Thank you

**Comment by matteobruni** [comment]
Let's make it clear:

## Life

Contains options for the creation of the emitter

## Rate

Contains options for the particles emitting rate/speed

---

You can see sample here: https://codepen.io/matteobruni/pen/zYarqVX

It waits 8 seconds to spawn the emitter, but every particle spawns after 0.1 seconds. Is that what you meant @marceloaof?

**Comment by marceloaof** [comment]
Thank you again.

Oh, the sample in codepen is exactly what I meant. You achieve it so simply and you explain very well the options available. I don't know where I am getting it wrong.
I am going to leave my full sample here while I try to solve it.

{
	"autoPlay": true,
	"fullScreen": {
		"enable": false,
		"zIndex": 0
	},
	"detectRetina": true,
	"duration": 0,
	"fpsLimit": 25,
	"interactivity": {
		"detectsOn": "window",
		"events": {
			"onClick": {
				"enable": true,
				"mode": "push"
			},
			"resize": true
		},
		"modes": {
			"push": {
				"default": true,
				"groups": [],
				"quantity": 1
			}
		}
	},
	"motion": {
		"disable": false,
		"reduce": {
			"factor": 4,
			"value": true
		}
	},
	"particles": {
		"color": {
			"value": "#fff"
		},
		"destroy": {
			"mode": "split",
			"split": {
				"count": 1,
				"factor": {
					"value": 0.333333
				},
				"rate": {
					"value": 100
				},
				"sizeOffset": true,
				"particles": {
					"stroke": {
						"width": 0
					},
					"color": {
						"value": [
							"#1982c4",
							"#3cafdd",
							"#3cddd5",
							"#8ac926",
							"#ffca3a",
							"#dd9a3c",
							"#ff595e",
							"#dd3ca7",
							"#6a4c93",
							"#ffffff",
							"#ffffff",
							"#ffffff",
							"#ffffff"
						]
					},
					"opacity": {
						"value": {
							"min": 0.1,
							"max": 1
						},
						"animation": {
							"enable": true,
							"speed": 0.7,
							"sync": false,
							"startValue": "max",
							"destroy": "min"
						}
					},
					"shape": {
						"type": "circle"
					},
					"size": {
						"value": {
							"min": 1,
							"max": 2
						},
						"animation": {
							"enable": true,
							"speed": 5,
							"count": 1,
							"sync": false,
							"startValue": "min",
							"destroy": "none"
						}
					},
					"life": {
						"count": 1,
						"duration": {
							"value": {
								"min": 1,
								"max": 2
							}
						}
					},
					"move": {
						"decay": 0.05,
						"enable": true,
						"gravity": {
							"enable": true,
							"inverse": false,
							"acceleration": 5
						},
						"speed": {
							"min": 2,
							"max": 5
						},
						"direction": "none",
						"outMode": "destroy"
					}
				}
			}
		},
		"life": {
			"count": 1
		},
		"move": {
			"angle": {
				"offset": 0,
				"value": 90
			},
			"center": {
				"x": 50,
				"y": 50,
				"radius": 0
			},
			"decay": 0,
			"direction": "none",
			"drift": 0,
			"enable": true,
			"gravity": {
				"acceleration": 15,
				"enable": true,
				"inverse": true,
				"maxSpeed": 100
			},
			"path": {
				"clamp": true,
				"delay": {
					"value": 0
				},
				"enable": false
			},
			"outModes": {
				"default": "destroy",
				"bottom": "destroy",
				"left": "destroy",
				"right": "destroy",
				"top": "none"
			},
			"speed": {
				"min": 10,
				"max": 20
			}
		},
		"number": {
			"density": {
				"enable": false,
				"area": 800,
				"factor": 1000
			},
			"limit": 0,
			"value": 0
		},
		"opacity": {
			"value": 1
		},
		"reduceDuplicates": false,
		"rotate": {
			"value": 0,
			"direction": "clockwise",
			"path": true
		},
		"shadow": {
			"blur": 5,
			"color": {
				"value": "#ffffff"
			},
			"enable": false,
			"offset": {
				"x": 0,
				"y": 0
			}
		},
		"shape": {
			"type": "line"
		},
		"size": {
			"value": {
				"min": 0.1,
				"max": 50
			},
			"animation": {
				"count": 0,
				"enable": true,
				"speed": 90,
				"sync": true,
				"destroy": "min",
				"startValue": "max"
			}
		},
		"stroke": {
			"width": 1.5,
			"color": {
				"value": "#6e6e73"
			}
		},
		"zIndex": {
			"value": 0,
			"opacityRate": 1,
			"sizeRate": 1,
			"velocityRate": 1
		}
	},
	"pauseOnBlur": true,
	"pauseOnOutsideViewport": true,
	"zLayers": 100,
	"emitters": {
		"autoPlay": true,
		"fill": true,
		"life": {
			"wait": false,
			"count": 0,
			"delay": 8,
			"duration": 0.1
		},
		"rate": {
			"quantity": 1,
			"delay": 0.25
		},
		"shape": "circle",
		"startCount": 0,
		"size": {
			"mode": "percent",
			"height": 0.1,
			"width": 0.1
		},
		"direction": "top-center",
		"position": {
			"x": 50,
			"y": 80.8
		}
	}
}

**Comment by matteobruni** [comment]
> Thank you again.
> 
> Oh, the sample in codepen is exactly what I meant. You achieve it so simply and you explain very well the options available. I don't know where I am getting it wrong. I am going to leave my full sample here while I try to solve it.
> 
> ```
> {
> 	"autoPlay": true,
> 	"fullScreen": {
> 		"enable": false,
> 		"zIndex": 0
> 	},
> 	"detectRetina": true,
> 	"duration": 0,
> 	"fpsLimit": 25,
> 	"interactivity": {
> 		"detectsOn": "window",
> 		"events": {
> 			"onClick": {
> 				"enable": true,
> 				"mode": "push"
> 			},
> 			"resize": true
> 		},
> 		"modes": {
> 			"push": {
> 				"default": true,
> 				"groups": [],
> 				"quantity": 1
> 			}
> 		}
> 	},
> 	"motion": {
> 		"disable": false,
> 		"reduce": {
> 			"factor": 4,
> 			"value": true
> 		}
> 	},
> 	"particles": {
> 		"color": {
> 			"value": "#fff"
> 		},
> 		"destroy": {
> 			"mode": "split",
> 			"split": {
> 				"count": 1,
> 				"factor": {
> 					"value": 0.333333
> 				},
> 				"rate": {
> 					"value": 100
> 				},
> 				"sizeOffset": true,
> 				"particles": {
> 					"stroke": {
> 						"width": 0
> 					},
> 					"color": {
> 						"value": [
> 							"#1982c4",
> 							"#3cafdd",
> 							"#3cddd5",
> 							"#8ac926",
> 							"#ffca3a",
> 							"#dd9a3c",
> 							"#ff595e",
> 							"#dd3ca7",
> 							"#6a4c93",
> 							"#ffffff",
> 							"#ffffff",
> 							"#ffffff",
> 							"#ffffff"
> 						]
> 					},
> 					"opacity": {
> 						"value": {
> 							"min": 0.1,
> 							"max": 1
> 						},
> 						"animation": {
> 							"enable": true,
> 							"speed": 0.7,
> 							"sync": false,
> 							"startValue": "max",
> 							"destroy": "min"
> 						}
> 					},
> 					"shape": {
> 						"type": "circle"
> 					},
> 					"size": {
> 						"value": {
> 							"min": 1,
> 							"max": 2
> 						},
> 						"animation": {
> 							"enable": true,
> 							"speed": 5,
> 							"count": 1,
> 							"sync": false,
> 							"startValue": "min",
> 							"destroy": "none"
> 						}
> 					},
> 					"life": {
> 						"count": 1,
> 						"duration": {
> 							"value": {
> 								"min": 1,
> 								"max": 2
> 							}
> 						}
> 					},
> 					"move": {
> 						"decay": 0.05,
> 						"enable": true,
> 						"gravity": {
> 							"enable": true,
> 							"inverse": false,
> 							"acceleration": 5
> 						},
> 						"speed": {
> 							"min": 2,
> 							"max": 5
> 						},
> 						"direction": "none",
> 						"outMode": "destroy"
> 					}
> 				}
> 			}
> 		},
> 		"life": {
> 			"count": 1
> 		},
> 		"move": {
> 			"angle": {
> 				"offset": 0,
> 				"value": 90
> 			},
> 			"center": {
> 				"x": 50,
> 				"y": 50,
> 				"radius": 0
> 			},
> 			"decay": 0,
> 			"direction": "none",
> 			"drift": 0,
> 			"enable": true,
> 			"gravity": {
> 				"acceleration": 15,
> 				"enable": true,
> 				"inverse": true,
> 				"maxSpeed": 100
> 			},
> 			"path": {
> 				"clamp": true,
> 				"delay": {
> 					"value": 0
> 				},
> 				"enable": false
> 			},
> 			"outModes": {
> 				"default": "destroy",
> 				"bottom": "destroy",
> 				"left": "destroy",
> 				"right": "destroy",
> 				"top": "none"
> 			},
> 			"speed": {
> 				"min": 10,
> 				"max": 20
> 			}
> 		},
> 		"number": {
> 			"density": {
> 				"enable": false,
> 				"area": 800,
> 				"factor": 1000
> 			},
> 			"limit": 0,
> 			"value": 0
> 		},
> 		"opacity": {
> 			"value": 1
> 		},
> 		"reduceDuplicates": false,
> 		"rotate": {
> 			"value": 0,
> 			"direction": "clockwise",
> 			"path": true
> 		},
> 		"shadow": {
> 			"blur": 5,
> 			"color": {
> 				"value": "#ffffff"
> 			},
> 			"enable": false,
> 			"offset": {
> 				"x": 0,
> 				"y": 0
> 			}
> 		},
> 		"shape": {
> 			"type": "line"
> 		},
> 		"size": {
> 			"value": {
> 				"min": 0.1,
> 				"max": 50
> 			},
> 			"animation": {
> 				"count": 0,
> 				"enable": true,
> 				"speed": 90,
> 				"sync": true,
> 				"destroy": "min",
> 				"startValue": "max"
> 			}
> 		},
> 		"stroke": {
> 			"width": 1.5,
> 			"color": {
> 				"value": "#6e6e73"
> 			}
> 		},
> 		"zIndex": {
> 			"value": 0,
> 			"opacityRate": 1,
> 			"sizeRate": 1,
> 			"velocityRate": 1
> 		}
> 	},
> 	"pauseOnBlur": true,
> 	"pauseOnOutsideViewport": true,
> 	"zLayers": 100,
> 	"emitters": {
> 		"autoPlay": true,
> 		"fill": true,
> 		"life": {
> 			"wait": false,
> 			"count": 0,
> 			"delay": 8,
> 			"duration": 0.1
> 		},
> 		"rate": {
> 			"quantity": 1,
> 			"delay": 0.25
> 		},
> 		"shape": "circle",
> 		"startCount": 0,
> 		"size": {
> 			"mode": "percent",
> 			"height": 0.1,
> 			"width": 0.1
> 		},
> 		"direction": "top-center",
> 		"position": {
> 			"x": 50,
> 			"y": 80.8
> 		}
> 	}
> }
> ```

Ok, I've understood the problem now, you'd like to replicate the fireworks preset with custom options.

I'll break it down into 3 parts:

- Initial delay: achievable with `life` options of the emitters, `duration` and `count` are not needed
- Lines emission: achievable with `rate`, `quantity` determines how many particles spawn every `delay` seconds
- Explosion: achievable with `particles.life` options (main `particles` sections, or can be added to `emitters` as well, it overrides properties from the main config).

You can see all these properties here: https://codepen.io/matteobruni/pen/abJQrbK (it's an old sample, but you can try the `particles.life` options.

In this sample also the `particles.size.animation` destroys the particles when reaching it's maximum size (like the fireworks preset)

**Comment by marceloaof** [comment]
As you said, `duration` and `count` are not needed on the `life` options of the `emitters`. Erasing them allowed  ✔️ the initial delay to happen and  ✔️ subsequent explosions to be faster than the initial delay.

Truly grateful for your detailed answers and efforts to help. 🙇 Sorry for spam. Have a nice day.
