### ISSUE TITLE
Cannot find "tsparticles" to import loadFull

### ISSUE THREAD

**Issue by leobartowski** [tsparticles/tsparticles#4784]
### What do you need?

I cannot find: 

### tsParticles Version

2.3.3

### Which library are you using?

Angular (ng-particles)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
Have you installed the package `"tsparticles"`?

**Comment by leobartowski** [comment]
Hi, I've installed `:ng-particles tsparticles-engine` as reported here: https://www.npmjs.com/package/ng-particles

**Comment by matteobruni** [comment]
If you want to use `loadFull` you must install `tsparticles`, it's not mandatory since you can use `loadSlim` from `tsparticles-slim` or any other preset, or custom configuration including manually the plugins you prefer
