### ISSUE TITLE
[Bug]: Can't deploy with tsParticles...

### ISSUE THREAD

**Issue by jbarone96** [tsparticles/tsparticles#4786]
### Contact Details

j.barone024@gmail.com

### What happened?

I am trying to deploy my React app through Vercel and I keep getting an error when install dependencies and it gets to tsparticles and can't complete the build. Everything works properly if I just 'npm start' the application but it doesn't deploy properly.. I would love to have particles on my portfolio but it seems like I am getting an error every time npm gets to installing react-tspartciles. I've even tried re-installing tspartciles and I get this error: 

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/react-tspartciles - Not found
npm ERR! 404 
npm ERR! 404  'react-tspartciles@*' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

Here's a screenshot of the error when trying to deploy..please help...

<img width="1680" alt="Screen Shot 2022-10-23 at 17 08 39" src="https://user-images.githubusercontent.com/98679275/197418573-f671e0c1-2198-44ab-861a-34e4e13891f2.png">

Thanks

### tsParticles Version

tsParticles Version (2.3.3)

### Which library are you using?

React.js (react-particles, react-tsparticles, react-particles-js)

### tsParticles Configuration

```json
import React from "react";
import Particles from "react-tsparticles";
import { loadFull } from "tsparticles";
import { useCallback } from "react";

const Particle = () => {
  const particlesInit = useCallback(async (engine) => {
    await loadFull(engine);
  }, []);

  const particlesLoaded = useCallback(async (container) => {
    console.log(container);
  }, []);
  return (
    <Particles
      id="tsparticles"
      init={particlesInit}
      loaded={particlesLoaded}
      params={{
        particles: {
          number: {
            value: 175,
            density: {
              enable: true,
              value_area: 1500,
            },
          },
          line_linked: {
            enable: false,
            opacity: 0.03,
          },
          move: {
            direction: "right",
            speed: 0.1,
          },
          size: {
            value: 1.25,
          },
          opacity: {
            anim: {
              enable: true,
              speed: 1.25,
              opacity_min: 0.05,
            },
          },
        },
        interactivity: {
          events: {
            onclick: {
              enable: true,
              mode: "push",
            },
          },
          modes: {
            push: {
              particles_nb: 1,
            },
          },
        },
        retina_detect: true,
        fullscreen: { enable: true },
      }}
    />
  );
};

export default Particle;
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by redgianttechnologies** [comment]
Particles is spelled wrong in your npm error. 
react-tspartciles@*

**Comment by jbarone96** [comment]
Fixed that and reinstalled. Still getting the error in the screenshot when deploying.

**Comment by matteobruni** [comment]
> Fixed that and reinstalled. Still getting the error in the screenshot when deploying.

Same error with same package name? The error you posted was 404 not found but there are two packages available.

- https://www.npmjs.com/package/react-particles
- https://www.npmjs.com/package/react-tsparticles

Re-check your config files and search for the typo. A 404 error is a typo you made.

**Comment by jbarone96** [comment]
No more 404 error. I still get the deployment error.

**Comment by matteobruni** [comment]
It’s nothing related to tsParticles that error, it says also `react-scripts` not found. You should try asking that to Vercel support.
