### ISSUE TITLE
Please consider removing custom `install` script

### ISSUE THREAD

**Issue by lensbart** [tsparticles/tsparticles#4794]
### What do you need?

I previously filed [issue ](https://github.com/matteobruni/tsparticles/issues/3502) which is closed as “completed”, but the custom `install` script only seems to be removed from `tsparticles`, not `react-tsparticles` or `tsparticles-engine`.

(I would have commented on that issue, but it’s locked now.)

More information can be found in the linked ticket.

Thanks!

### tsParticles Version

latest

### Which library are you using?

Vanilla (tsparticles), React.js (react-particles, react-tsparticles, react-particles-js)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
This is not a planned change in the near future. There are still many tutorials using `react-particles-js` for showing particles in a React environment.
Maybe in the future, these scripts will be removed, keeping this open is not necessary.
