### ISSUE TITLE
[Bug]: Particles skewed when changing device orientation 

### ISSUE THREAD

**Issue by maniS001** [tsparticles/tsparticles#4803]
### What happened?

I  tried to make butterfly   animation  in my game using tsparticles. when I change the device's orientation the butterfly particle was skewed for a second and normalized then. This was fine in  versions lower than 1.15. This is happening in the  above versions 2.How can I fix this issue?

### tsParticles Version

v2.5.1

### Which library are you using?

Vanilla (tsparticles)

### tsParticles Configuration

```json
<script src="https://cdn.jsdelivr.net/npm/tsparticles@2.5.1/tsparticles.bundle.min.js"></script>

    <script type="text/javascript">
      
     tsParticles.load("bgdiv",{
       particles:{
         move:{
           enable:true,
 
         },
         links:{
         enable : false
         },
          density:{
           number:{
            
             value:10

           },
          },

          shape: {
            type: "image",
            options: {
                images: [{
                    src: "image/butterlfy_img.png",

                }],
            }
           },
           size:{
            value:20
          },
          number:{
            value:15
          }
           
       },
 
     }
     )
    </script>
```

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
I recommend using `responsive` properties, since the window resize event tries to keep particles in the same place when resizing the window. It will refresh the particles when switching to the right configuration depending on screen width, but at least they will be showed correctly. You can also try to disable the `resize` event, but I don't recommend it.

Before `1.15` there was a bug in the window resize event, since it wasn't working correctly in a lot of configurations. Maybe the previous version was working fine in your case, but there were a lot of different issues with that.

**Comment by maniS001** [comment]
I have not used any resize  property on particles , even if  I not used any  resize property on entire project this causes the same thing.  I feel that there is a settimeout problem in the source code at below mentioned function:

  handleWindowResize() {
    if (this.resizeTimeout) {
      clearTimeout(this.resizeTimeout);
      delete this.resizeTimeout;
    }
    this.resizeTimeout = setTimeout(async () => {
      var _a;
      return (_a = this.container.canvas) === null || _a === void 0 ? void 0 : _a.windowResize();
    }, 500);
  }

If I gave the time out 0 instead of 500 the problem was solved. But I need a clarification , is there any problem by changing timeout value from 500 to 0 ( or removing the timeout)?

**Comment by maniS001** [comment]
And I have some more questions : 
1. can we create particles animation using sprite sheets (example :  making the butterflies as fly ).Because  now the butterflies looks do nothing (in my case) but moving on sky.

2. Another important one is , how to destroy the particles after it crossed the screen (outside the screen). If I use destroy property , there after no more particles created. so please let me know how to destroy individual particle after went from screen.

**Comment by matteobruni** [comment]
> I have not used any resize property on particles , even if I not used any resize property on entire project this causes the same thing. I feel that there is a settimeout problem in the source code at below mentioned function:
> 
> handleWindowResize() { if (this.resizeTimeout) { clearTimeout(this.resizeTimeout); delete this.resizeTimeout; } this.resizeTimeout = setTimeout(async () => { var _a; return (_a = this.container.canvas) === null || _a === void 0 ? void 0 : _a.windowResize(); }, 500); }
> 
> If I gave the time out 0 instead of 500 the problem was solved. But I need a clarification , is there any problem by changing timeout value from 500 to 0 ( or removing the timeout)?

The `setTimeout` used there is just a debounce to avoid multiple consequent calls, for example when resizing the browser window on desktop environments, since there will be a lot of avoidable flickers and refreshes. I could make that timeout value configurable, it could help in similar situations.

The `resize` event in the `interactivity` section is active by default, you must disable it manually if you don't need it.

**Comment by matteobruni** [comment]
> And I have some more questions :
> 
> 1. can we create particles animation using sprite sheets (example :  making the butterflies as fly ).Because  now the butterflies looks do nothing (in my case) but moving on sky.
> 2. Another important one is , how to destroy the particles after it crossed the screen (outside the screen). If I use destroy property , there after no more particles created. so please let me know how to destroy individual particle after went from screen.

1. I didn't understand the request, do you need animated images as shapes?
2. `particles.move.outModes: "destroy"

**Comment by maniS001** [comment]
> > I have not used any resize property on particles , even if I not used any resize property on entire project this causes the same thing. I feel that there is a settimeout problem in the source code at below mentioned function:
> > handleWindowResize() { if (this.resizeTimeout) { clearTimeout(this.resizeTimeout); delete this.resizeTimeout; } this.resizeTimeout = setTimeout(async () => { var _a; return (_a = this.container.canvas) === null || _a === void 0 ? void 0 : _a.windowResize(); }, 500); }
> > If I gave the time out 0 instead of 500 the problem was solved. But I need a clarification , is there any problem by changing timeout value from 500 to 0 ( or removing the timeout)?
> 
> The `setTimeout` used there is just a debounce to avoid multiple consequent calls, for example when resizing the browser window on desktop environments, since there will be a lot of avoidable flickers and refreshes. **I could make that timeout value configurable, it could help in similar situations.**

Ok my friend, I understood.

**Comment by maniS001** [comment]
> > And I have some more questions :
> > 
> > 1. can we create particles animation using sprite sheets (example :  making the butterflies as fly ).Because  now the butterflies looks do nothing (in my case) but moving on sky.
> > 2. Another important one is , how to destroy the particles after it crossed the screen (outside the screen). If I use destroy property , there after no more particles created. so please let me know how to destroy individual particle after went from screen.
> 
> 1. I didn't understand the request, do you need animated images as shapes?
> 2. particles.move.outModes: "destroy"

1. yes. that's what I need. can you do anything for that ?

2. Ok. I am at the situation to keep the particles moving left only inside a div element, But unfortunately some particles getting cut when I tried to move inside div. So I have used verticleBounce for outmode property. But I am also in the situation to destroy the particle after they crossed the viewport. So how can I achieve the both in same time ?

**Comment by matteobruni** [comment]
> > > And I have some more questions :
> > > 
> > > 1. can we create particles animation using sprite sheets (example :  making the butterflies as fly ).Because  now the butterflies looks do nothing (in my case) but moving on sky.
> > > 2. Another important one is , how to destroy the particles after it crossed the screen (outside the screen). If I use destroy property , there after no more particles created. so please let me know how to destroy individual particle after went from screen.
> > 
> > 
> > 
> > 1. I didn't understand the request, do you need animated images as shapes?
> > 2. particles.move.outModes: "destroy"
> 
> 1. yes. that's what I need. can you do anything for that ?
> 2. Ok. I am at the situation to keep the particles moving left only inside a div element, But unfortunately some particles getting cut when I tried to move inside div. So I have used verticleBounce for outmode property. But I am also in the situation to destroy the particle after they crossed the viewport. So how can I achieve the both in same time ?

1. Is not something you can achieve with standard tsParticles, you can create a custom shape that changes shape for every frame. It's not something that will be implemented in the library for now.
2. Instead of `verticalBounce` you can customize every bound in the `outModes` value like this:

```
outModes: {
  default: "out", // used when a value is not specified, optional if all are specified
  top: "bounce",
  bottom: "bounce",
  left: "destroy",
  right: "destroy"
}
```
