### ISSUE TITLE
[Bug]: Vuejs Version is not working

### ISSUE THREAD

**Issue by artrayd** [tsparticles/tsparticles#4804]
### What happened?

Getting this error:
"Uncaught SyntaxError: Cannot use import statement outside a module"

### tsParticles Version

2.5.1

### Which library are you using?

Vue.js 2.x (vue2-particles, particles.vue)

### tsParticles Configuration

```json
<Particles
      id="tsparticles"
      :particlesInit="particlesInit"
      :particlesLoaded="particlesLoaded"
      :options="{
        background: {
          color: {
            value: '#0d47a1',
          },
        },
        fpsLimit: 120,
        interactivity: {
          events: {
            onClick: {
              enable: true,
              mode: 'push',
            },
            onHover: {
              enable: true,
              mode: 'repulse',
            },
            resize: true,
          },
          modes: {
            bubble: {
              distance: 400,
              duration: 2,
              opacity: 0.8,
              size: 40,
            },
            push: {
              quantity: 4,
            },
            repulse: {
              distance: 200,
              duration: 0.4,
            },
          },
        },
        particles: {
          color: {
            value: '#ffffff',
          },
          links: {
            color: '#ffffff',
            distance: 150,
            enable: true,
            opacity: 0.5,
            width: 1,
          },
          collisions: {
            enable: true,
          },
          move: {
            direction: 'none',
            enable: true,
            outMode: 'bounce',
            random: false,
            speed: 6,
            straight: false,
          },
          number: {
            density: {
              enable: true,
              area: 800,
            },
            value: 80,
          },
          opacity: {
            value: 0.5,
          },
          shape: {
            type: 'circle',
          },
          size: {
            random: true,
            value: 5,
          },
        },
        detectRetina: true,
      }"
    />
```

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
This is the demo project for Vue 2.x version: https://github.com/matteobruni/tsparticles/tree/main/demo/vue

It works as expected, can you please share a way to reproduce the bug?

**Comment by artrayd** [comment]
Thank you for answering @matteobruni I checked at provided example and found that it requires to install more packages 

tsparticles-engine
tsparticles

So vue2-particles is just tip of the iceberg  =)  Also everything is written at TS. Maybe you should mention it in docs? Seems like this package is too advanced for me..

I couldn't even run demo example, it throws following error:
`Cannot find module 'tsparticles-engine' or its corresponding type declarations.`

**Comment by matteobruni** [comment]
> Thank you for answering @matteobruni I checked at provided example and found that it requires to install more packages
> 
> tsparticles-engine tsparticles
> 
> So vue2-particles is just tip of the iceberg =) Also everything is written at TS. Maybe you should mention it in docs? Seems like this package is too advanced for me..
> 
> I couldn't even run demo example, it throws following error: `Cannot find module 'tsparticles-engine' or its corresponding type declarations.`

TS is the language used for building, the output is standard JavaScript. `tsparticles-engine` is required only for TypeScript projects or for advanced uses.

You can see a CodeSandbox project using JavaScript: https://codesandbox.io/s/quizzical-chandrasekhar-pxy59o?file=/src/App.vue

You need at least two packages: `vue2-particles` and one of these (`tsparticles`, `tsparticles-slim`, or any `tsparticles-preset-` package) or you can configure all plugins by yourself.

**Comment by artrayd** [comment]
Thank you a lot @matteobruni
