### ISSUE TITLE
[WordPress] Localize plugin editor

### ISSUE THREAD

**Issue by alexclassroom** [tsparticles/tsparticles#4807]
### What do you need?

Please make the meta box of plugin settings in the block editor localizable, this is much more friendly for users.

### tsParticles Version

2.5.3

### Which library are you using?

WordPress

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
Sorry, but I didn't understand the request

**Comment by alexclassroom** [comment]
The following screenshots are captured from this plugin. All UI strings of this plugin are not translatable. If they can be translatable like Automattic official plugins, it will be much more friendly for users.
![tsparticles-block-001](https://user-images.githubusercontent.com/11472643/200425900-955373f0-5c94-451c-bc96-863086e60286.png)
![tsparticles-block-002](https://user-images.githubusercontent.com/11472643/200425899-5eb0143c-a657-4364-bebd-6d597f66c427.png)
![tsparticles-block-003](https://user-images.githubusercontent.com/11472643/200425897-e9485da4-0418-44fe-a85e-ccd23c4d6589.png)
![tsparticles-block-004](https://user-images.githubusercontent.com/11472643/200425896-99aa8cbb-e91f-40cf-94f7-96f8465610b2.png)
![tsparticles-block-005](https://user-images.githubusercontent.com/11472643/200425894-73400da0-be02-459a-b0e5-78deb3a2eeb6.png)
![tsparticles-block-006](https://user-images.githubusercontent.com/11472643/200425892-098748de-25d5-4f29-bc7b-61c81802105d.png)
![tsparticles-block-007](https://user-images.githubusercontent.com/11472643/200425888-8e7c6865-2b8e-4c44-b41e-90c7f87e45dd.png)

**Comment by matteobruni** [comment]
The fix for this will be available soon
