### ISSUE TITLE
how to avoid moving dom element

### ISSUE THREAD

**Issue by Mohsen-Khakbiz** [tsparticles/tsparticles#4829]
### What do you need?

hey there
currently when initiating tsparticles, it's duplicating/moving the dom element and appending to `document`
how I can prevent this behavior?
I need the dom element to stay on its place

### tsParticles Version

2.5.3

### Which library are you using?

Vanilla (tsparticles)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
Please share your code

**Comment by Mohsen-Khakbiz** [comment]
nothing special with the code. just using the initiator `tsParticles.load("tsparticles");` using a preset config to test.
but I couldn't find any option that avoids moving the dom element

**Comment by matteobruni** [comment]
> nothing special with the code. just using the initiator `tsParticles.load("tsparticles");` using a preset config to test.
> but I couldn't find any option that avoids moving the dom element

I don't understand what do you mean with `moving the dom element` but I need your code to replicate the issue in my local environment

**Comment by Mohsen-Khakbiz** [comment]
sorry my bad.
I entered a wrong element id, and tsparticles automatically creating a dom element in the doc.

but now I have another question. how I can preserve the canvas size? let's say I don't want it to be fullscreen
`fullscreen.enable` didn't work here https://codepen.io/Mohsen-Khakbiz/pen/gOKoqVN

**Comment by munkacsimark** [comment]
> sorry my bad. I entered a wrong element id, and tsparticles automatically creating a dom element in the doc.
> 
> but now I have another question. how I can preserve the canvas size? let's say I don't want it to be fullscreen `fullscreen.enable` didn't work here https://codepen.io/Mohsen-Khakbiz/pen/gOKoqVN

Hey, I checked your code. Don't add `<canvas>` manually, the package will create it for you. Just define the `div` element like: `<div id="particles-container"></div>`. Related to your question, `fullscreen` should be `fullScreen` with camelCase.

**Comment by Mohsen-Khakbiz** [comment]
silly me. that's working as expected now.
thanks for helping guys!
