### ISSUE TITLE
[Bug]: Type 'Engine' is missing the following properties from type 'Engine': _domArray, _eventDispatcher, _initialized, _loader

### ISSUE THREAD

**Issue by Blankeos** [tsparticles/tsparticles#4830]
### What happened?

This exact line of code from the documentation is causing an error message:
```ts
  const particlesInit = useCallback(async (engine: Engine) => {
    console.log(engine);

    // you can initialize the tsParticles instance (engine) here, adding custom shapes or presets
    // this loads the tsparticles package bundle, it's the easiest method for getting everything ready
    // starting from v2 you can add only the features you need reducing the bundle size
    await loadFull(engine);
}, []);
```

Error Message:
```
Argument of type 
'import("d:/project_name/node_modules/tsparticles-engine/types/engine").Engine'
is not assignable to parameter of type 
'import("D:/project_name/node_modules/.pnpm/tsparticles-engine@2.5.2/node_modules/tsparticles-engine/types/engine").Engine'.

Type 'Engine' is missing the following properties from type 'Engine': _domArray, _eventDispatcher, _initialized, _loader
```

### tsParticles Version

^2.5.3

### Which library are you using?

React.js (react-particles, react-tsparticles, react-particles-js)

### tsParticles Configuration

```json
Config doesn't cause an issue
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
@Blankeos can you share the full code of your imports and particles usage?

**Comment by Blankeos** [comment]
### Screenshot: The code:
![image](https://user-images.githubusercontent.com/38070918/203620039-9d90e285-1ebf-4226-95a1-68f01ce5a7c2.png)

### Screenshot: The error message:
![image](https://user-images.githubusercontent.com/38070918/203620432-3643676b-fd36-40b8-907f-156b9aac78a5.png)

### The code:
```tsx
// ParticlesBackground.tsx
import { useCallback } from "react";
import Particles from "react-tsparticles";
import { loadFull } from "tsparticles";
import particlesConfig from "../particles/particles.json";
import type { Engine, Container, ISourceOptions } from "tsparticles-engine";

const ParticlesBackground: React.FC = () => {
  const particlesInit = useCallback(async (engine: Engine) => {
    console.log(engine);

    // you can initialize the tsParticles instance (engine) here, adding custom shapes or presets
    // this loads the tsparticles package bundle, it's the easiest method for getting everything ready
    // starting from v2 you can add only the features you need reducing the bundle size
    await loadFull(engine);
  }, []);

  // const particlesLoaded = useCallback(async (container: Container) => {
  //   await console.log(container);
  // }, []);

  return (
    <Particles
      className="h-full object-cover absolute w-full"
      canvasClassName="will-change-auto h-full"
      options={particlesConfig as any}
      init={particlesInit}
    />
  );
};

export default ParticlesBackground;
```

**Comment by matteobruni** [comment]
https://codesandbox.io/s/staging-flower-72is51?file=/src/ParticlesBackground.tsx

I've created this CodeSandbox but it works as expected, can you replicate the issue there?

**Comment by Blankeos** [comment]
Hi @matteobruni! Thanks for the code sandbox, that helped me figure it out. I think the error was caused by the fact that `tsparticles-engine` was inside my `node_modules` folder but not in my `package.json`? It's a huge facepalm moment 🤦‍♂️ I know...

Possible Cause:
- I migrated from using `yarn` to `pnpm` months ago. It wasn't causing issues before... only until now. Or maybe I just haven't opened the file ever since because it wasn't really causing issues on deployment when type-checking with `tsc` when it should have. Does installing `tsparticles` also install `tsparticles-engine` as an included package? I assumed it was because intellisense shows that it found the module, so I never really opted to `pnpm add tsparticles-engine` to see if that was the fix.

 In any case, an error message of "module not found" could have been more straightforward to help me solve it. I think the `yarn` to `pnpm` migration is the strongest cause here.

Thanks again! I'll just go ahead and close this issue.

**Comment by matteobruni** [comment]
`tsparticles-engine` is a dependency of both `react-tsparticles` and `tsparticles`, I had some issues with PNPM in the past and they were solved by their team in newer versions 😅

`tsparticles-engine` for both packages are required only when using TypeScript
