### ISSUE TITLE
Vue3 can't get particles working

### ISSUE THREAD

**Issue by patbsh** [tsparticles/tsparticles#4833]
### Contact Details

patryk@gustomania.pl

### What do you need?

Hi, I can't get past the initial setup. I installed both vue3-particles and tsparticles libraries using npm. I imported vue3-particles in the app.js and added app.use(Particles).

I copied the example code exactly like in the github's readme and only got the background colour from the configuration to the website.

Having looked into the console I get these warnings (it seems like the loadFull is not correctly imported)

"[Vue warn]: Property "particlesInit" was accessed during render but is not defined on instance. "

"[Vue warn]: Property "particlesLoaded" was accessed during render but is not defined on instance.".

### tsParticles Version

2.5.3

### Which library are you using?

Vue.js 3.x (vue3-particles, particles.vue3)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
I need the code for helping you about that. You can checkout the working demo here: https://github.com/matteobruni/tsparticles/tree/main/demo/vue3/src

**Comment by patbsh** [comment]
I used the working demo <script> and it worked. Seems like it does not work without typescript?

**Comment by matteobruni** [comment]
https://codesandbox.io/s/muddy-water-0lqn46?file=/src/main.js It works also in JavaScript as you can see here

**Comment by patbsh** [comment]
Thank you very much! I appreciate your prompt responses and help.
