### ISSUE TITLE
Multitouch support

### ISSUE THREAD

**Issue by magikarp28** [tsparticles/tsparticles#4839]
### Contact Details

filip@omnivor.hr

### What is your request?

Currently only a single touch event works at one time for events, it would be nice if all available touch events would be handled.

### tsParticles Version

2.5.1

### Which library are you using?

React.js (react-particles, react-tsparticles, react-particles-js)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
Closes this for using a more detailed issue #4965
