### ISSUE TITLE
vue3 implements use(Particles); anomaly

### ISSUE THREAD

**Issue by seechangan** [tsparticles/tsparticles#4917]
### Contact Details

1071175587@qq.com

### What do you need?

Particle effects can be displayed normally on the page, and the console is error-free.

const app = createApp(App).use(Particles); A red wavy line error message is displayed. The following error message is displayed when hovering:

(alias) const Particles: (app: App, options: unknown) => void
import Particles
Arguments of type "(app: App<any>, options: unknown) => void" cannot be assigned to arguments of type "Plugin_2<[]>".
Cannot assign type "(app: App<any>, options: unknown) => void" to type "((app: App<any>) => any) & {install? : ((app: App<any>) => any) | undefined;  } ".
Cannot assign type "(app: App<any>, options: unknown) => void" to type "(app: App<any>) => any".

### tsParticles Version

2.9.3

### Which library are you using?

Vue.js 3.x (vue3-particles, particles.vue3)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
There’s a specific repository for Vue3 component, please open the issue [here](https://github.com/tsparticles/vue3) and provide the full code with imports
