### ISSUE TITLE
[Bug]: tsparticles links presetn nto working

### ISSUE THREAD

**Issue by windmillcode0** [tsparticles/tsparticles#4971]
### Contact Details

shieldmousetower734@gmail.com

### What happened?

I follow the instructions according to the site
https://github.com/tsparticles/presets/tree/main/presets/links/#readme
but it does not work 

### tsParticles Version

2.9.3

### tsParticles Configuration

```json
(async () => {
  await loadLinksPreset(tsParticles); // this is required only if you are not using the bundle script

  await tsParticles.load("tsparticles", {
    preset: "links",
  });
})();
```

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
N/A
but look at this repo
https://github.com/WindMillCode/tsparticles-issue
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
It's an issue already solved in the upcoming `2.10` (PR #4912), a workaround is set a particles number because the default is `0` since `2.9.0`.

For example:

```
(async () => {
  await loadLinksPreset(tsParticles); // this is required only if you are not using the bundle script

  await tsParticles.load("tsparticles", {
    preset: "links",
    particles: { number: { value: 100 } }
  });
})();
```

**Comment by windmillcode0** [comment]
Ok also in v 1.26.e the particles resizes with the container now  2.9.3 it takes the whole screen instead of the target container how do I resolve this  also the bundle size is crazy at 446 kb for the cpnt thats using is 2.9.3 using esm modules?

**Comment by matteobruni** [comment]
About the fullScreen: https://www.reddit.com/r/tsParticles/comments/w8luvb/why_my_particles_are_full_screen_i_want_them_to/

About the bundle size you can load only the plugins needed to reduce the size instead of using the `tsparticles` bundle package

**Comment by matteobruni** [comment]
Since this issue refers to the presets, it should be reopened in the [presets repository](https://github.com/tsparticles/presets) if needed.
