### ISSUE TITLE
Confetti bundle makes the particles disappear abruptly instead of fading

### ISSUE THREAD

**Issue by hellokingdom** [tsparticles/tsparticles#4978]
### Contact Details

james.hyatt@outlook.com

### What do you need?

Hi, thanks firstly for this great library.

I am looking at your examples using the code found here: https://confetti.js.org/more.html

Taking a look at your basic example the confetti does not fade out as it falls but disappears abruptly. Is it possible to configure this effect so that each particle fades to opacity 0 as it falls?

### tsParticles Version

2.9.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
It's possible with standard `tsParticles` APIs, those options are an easy alternative. I'll review them to see how it can be achieved without breaking too much.
