### ISSUE TITLE
[Bug]:  Demo Page Broken

### ISSUE THREAD

**Issue by pascal-mueller** [tsparticles/tsparticles#4981]
### What happened?

Hey, so the demo page of the homepage is broken. There's a syntax error:

Uncaught SyntaxError: unexpected token: '{'[demo.min.js:1:929](https://particles.js.org/js/demo.min.js)

### tsParticles Version

whatever is hosted on the homepage

### tsParticles Configuration

```json
whatever the homepage uses
```

### What browsers are you seeing the problem on?

Firefox

### Relevant log output

```shell
Uncaught SyntaxError: unexpected token: '{'demo.min.js:1:929
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
Thanks for reporting this, I'll cose this here since it belongs to the [website repository](https://github.com/tsparticles/website)
