### ISSUE TITLE
[Bug]: Confetti presets not working anymore

### ISSUE THREAD

**Issue by Webrow** [tsparticles/tsparticles#4989]
### Contact Details

rowandegraaf@gmail.com

### What happened?

I checked out our repo and saw that the confetti was just "falling down" in an arc. 
Then I wanted to debug what caused it, cause it was configureed to use the realistic look, but alle examples on the website show the same. 
Website behaviour
![chrome_AwlOAbvWxz](https://github.com/matteobruni/tsparticles/assets/3177853/13125a89-3688-403b-80c2-79402ef60f81)

App behaviour 
![firefox_HEQeuuZB8A](https://github.com/matteobruni/tsparticles/assets/3177853/9517c89f-16d1-4404-8e7e-f59ff7de6176)

![image](https://github.com/matteobruni/tsparticles/assets/3177853/d2813462-60a4-433b-b537-d0282a499149)

### tsParticles Version

2.9.3

### tsParticles Configuration

```json
particlesOptions = {
    fullScreen: {
      zIndex: 1,
    },
    preset: 'confetti',
    emitters: [
      {
        life: {
          duration: 5,
          count: 1,
        },
        position: {
          x: 0,
          y: 30,
        },
        particles: {
          move: {
            direction: 'top-right',
          },
        },
      },
      {
        life: {
          duration: 5,
          count: 1,
        },
        position: {
          x: 100,
          y: 30,
        },
        particles: {
          move: {
            direction: 'top-left',
          },
        },
      },
    ],
  };


showConfetti(): void {
    (async () => {
      const count = 200,
        defaults = {
          origin: { y: 0.9 },
        };

      console.log(confetti);

      function fire(particleRatio, opts) {
        confetti(
          Object.assign({}, defaults, opts, {
            particleCount: Math.floor(count * particleRatio),
          })
        );
      }

      fire(0.25, {
        spread: 26,
        startVelocity: 55,
      });

      fire(0.2, {
        spread: 60,
      });

      fire(0.35, {
        spread: 100,
        decay: 0.91,
        scalar: 0.8,
      });

      fire(0.1, {
        spread: 120,
        startVelocity: 25,
        decay: 0.92,
        scalar: 1.2,
      });

      fire(0.1, {
        spread: 120,
        startVelocity: 45,
      });
    })();
  }
```

### What browsers are you seeing the problem on?

Firefox, Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
I tested the url https://confetti.js.org/more.html and it works as expected. Can you share a full repro sample?

**Comment by Webrow** [comment]
Ill close this, and see if i can consitantly rule out my pc self.

**Comment by kslstn** [comment]
I'm experiencing a similar problem. I was experiencing the following issue: when I don't run `loadFull(tsParticles);` upon page load, my options don't work; it's like the speed is ignored or set to 0 or something. To make sure it wasn't something specific to my project, I've done the following and reproduced this issue:

1. Fork the Astro Basics repo
2. Install [astro-particles](https://github.com/tsparticles/astro#readme)
3. Create a component, add the code from 'How to use'
4. Copy the explosions options [from the homepage](https://confetti.js.org/#)

I've done the above [in this Stackblitz](https://stackblitz.com/edit/github-sdffqm?file=src%2Fcomponents%2FMyParticles.astro). If you now click the button with the 'Start particles' label, you'll get the same weird effect as in the screenshots from Webrow.

If you uncomment line 139 from `./src/components/MyParticles.astro`, you'll see that the particles are rendered as intended. If you then press the 'Start particles' button again, they're also rendered correctly.
