### ISSUE TITLE
[Bug]: Custom SVG Particles Do Not Load Firefox

### ISSUE THREAD

**Issue by liamlows** [tsparticles/tsparticles#4997]
### What happened?

When attempting to use a custom svg image as the particle, the svg fails to load in firefox. I tried using a png instead and that worked fine. SVGs work in chrome,

See the following config for reproduction or visit https://codesandbox.io/s/fast-architecture-0k91qq?file=/src/App.js:921-1750 

### tsParticles Version

2.9.3

### tsParticles Configuration

```json
{
        fpsLimit: 120,
        background: {
          color: "#000"
        },
        particles: {
          color: { value: "#ffffff" },
          move: {
            direction: "none",
            enable: true,
            outModes: "out",
            random: false,
            speed: 2,
            straight: false
          },
          number: { density: { enable: true, area: 800 }, value: 80 },
          opacity: {
            value: 0.9
          },
          shape: {
            type: "image",
            image: {
              // swap this to use png or svg image, png will work svg will not
              // src: "/iwc-logo-transparent-box.png"
              src: "/iwc-logo-transparent-box.svg"
            }
          },
          size: {
            value: { min: 10, max: 25 }
          }
        }
      }
```

### What browsers are you seeing the problem on?

Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
Your SVG is missing the `width` and `height` attribute. I've updated your SVG file here: https://codesandbox.io/s/heuristic-architecture-x3su5z?file=/src/App.js and it works as expected.

**Comment by liamlows** [comment]
> Your SVG is missing the `width` and `height` attribute. I've updated your SVG file here: https://codesandbox.io/s/heuristic-architecture-x3su5z?file=/src/App.js and it works as expected.

Ahhhh I feel so stupid, I never noticed that the SVG I was working with did not have the width and height set on it itself. I thought that the properties in the options configuration would pass down to the SVG as well. My bad. Thank you this works!
