### ISSUE TITLE
there is a left over console log in the EmitterInstance

### ISSUE THREAD

**Issue by rowanfuchs** [tsparticles/tsparticles#5003]
### What do you need?

 it can be found here, while its not an issue it's cluttering within debugging. 
 
https://github.com/matteobruni/tsparticles/blob/492ec449e7199c62fad01a9e38e4623e34772edd/plugins/emitters/src/EmitterInstance.ts#L79

### tsParticles Version

latest

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rkyslyy** [comment]
@matteobruni I found another log, any chance to remove that too? It's version `2.10.1`:

<img width="587" alt="Screenshot 2023-06-07 at 21 47 28" src="https://github.com/matteobruni/tsparticles/assets/33093275/01a1f29f-9f3c-46dc-b38e-ee1705f3eadc">

<img width="351" alt="Screenshot 2023-06-07 at 21 50 25" src="https://github.com/matteobruni/tsparticles/assets/33093275/4d52e3b0-2fbf-4d4b-bb30-f50846ce914a">

**Comment by matteobruni** [comment]
For sure, I've seen that it's only in the `react-particles` package, if it's annoying you can switch to `react-tsparticles` instead. They are the same package, with a different name.

**Comment by rkyslyy** [comment]
Ah cool, thanks
