### ISSUE TITLE
[Bug]: Speed/distance options are wrongly applied when particles are not immediately rendered upon page load

### ISSUE THREAD

**Issue by kslstn** [tsparticles/tsparticles#5010]
### Contact Details

webform@kooslooijesteijn.net

### What happened?

When I don't run `loadFull(tsParticles)` upon page load, my options don't work; it's like the speed is ignored or set to 0 or the size of the viewport is wrongly calculated as tiny or something. To make sure it wasn't something specific to my project, I've done the following and reproduced this issue:

- Fork the Astro Basics repo
- Install [astro-particles](https://github.com/tsparticles/astro#readme)
- Create a component, add the code from 'How to use'
- Copy the explosions options [from the homepage](https://confetti.js.org/#)

I've done the above [in this Stackblitz](https://stackblitz.com/edit/github-sdffqm?file=src%2Fcomponents%2FMyParticles.astro). If you now click the button with the 'Start particles' label, you'll get the same weird effect as in [the screenshots in bug 4989](https://github.com/matteobruni/tsparticles/issues/4989).

If you uncomment line 139 from ./src/components/MyParticles.astro, you'll see that the particles are rendered as intended. If you then press the 'Start particles' button again, they're also rendered correctly.

(I've posted a similar comment under bug 4989, which was marked as off-topic. I'm assuming it's better to open this more generic bug report. Considering I'm not doing much beyond applying the most basic example in the docs, this looks like a real issue to me and I want to make sure that anyone who'd care and can do something about it can see it).

### tsParticles Version

2.10.1

### tsParticles Configuration

```json
"astro-particles": "^2.9.3",
"tsparticles": "^2.10.1",
"tsparticles-engine": "^2.10.1"
```

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
Please use the [Astro repository](https://github.com/tsparticles/astro) for issue with that component
