### ISSUE TITLE
Snow particle animation resets when calling loadConfettiPreset after loadSnowPreset

### ISSUE THREAD

**Issue by viktorb1** [tsparticles/tsparticles#5122]
### What happened?

When calling loadConfettiPreset() after loadSnowPreset(), the snow animation resets and reloads. 

I created a jsfiddle of the issue here: https://jsfiddle.net/rht7gzjv/ (I used v1.42.2 because v2.12.0 doesn't work in jsfiddle, but the same issue exists in v2.12.0)

Notice how after 1 second when the setTimeout is triggered, the snow animation also resets. Is it possible to make the snow continuous throughout the load_ function calls?

### tsParticles Version

2.12.0

### tsParticles Configuration

```json
https://jsfiddle.net/rht7gzjv/
```

### What browsers are you seeing the problem on?

Chrome Version 115.0.5790.170 (Official Build) (arm64)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
Not a bug, the `load` function *MUST* be called once, it loads all the necessary for the preset. Every time you call it, it refresh the whole engine, reloading all loaded instances too. `tsParticles.load` can be called multiple times, it reloads the instance only, and if you place that in a setTimeout, it will trigger a refresh too.

Here's the updated jsFiddle: https://jsfiddle.net/dzmp2yn3/

The jsFiddle is fixed loading all the presets correctly and using the async/await to every awaitable function

**Comment by viktorb1** [comment]
So I am using this wrong? What would be the correct way to do this then?

**Comment by viktorb1** [comment]
> https://jsfiddle.net/dzmp2yn3/

Oh I see, thank you!!
