### ISSUE TITLE
[Bug]:  tsParticles - Error in animation loop TypeError: Cannot read properties of undefined (reading 'circleRange')

### ISSUE THREAD

**Issue by tieucoctu** [tsparticles/tsparticles#5282]
### What happened?

/* eslint-disable import/no-extraneous-dependencies */
import { type Container, type ISourceOptions, MoveDirection, OutMode, loadFont } from '@tsparticles/engine';
import Particles, { initParticlesEngine } from '@tsparticles/react';
import React, { useEffect, useMemo, useState } from 'react';

import { loadSlim } from 'tsparticles-slim';
// eslint-disable-next-line import/no-extraneous-dependencies
const ParticlesComponent = () => {
  const [init, setInit] = useState(false);
  console.log('init :', init);

  // this should be run only once per application lifetime
  useEffect(() => {
    initParticlesEngine(async (engine: any) => {
      // you can initiate the tsParticles instance (engine) here, adding custom shapes or presets
      // this loads the tsparticles package bundle, it's the easiest method for getting everything ready
      // starting from v2 you can add only the features you need reducing the bundle size
      //await loadAll(engine);
      //await loadFull(engine);
      await loadSlim(engine);
      //await loadBasic(engine);
    }).then(() => {
      setInit(true);
    });
  }, []);

  

  return <Particles id="tsparticles" options={options} />;
};
export default ParticlesComponent;

### tsParticles Version

3.0.0

### tsParticles Configuration

```json
const options: ISourceOptions = useMemo(
    () => ({
      background: {
        color: {
          value: '#0d47a1',
        },
      },
      fpsLimit: 120,
      interactivity: {
        events: {
          onClick: {
            enable: true,
            mode: 'push',
          },
          onHover: {
            enable: true,
            mode: 'repulse',
          },
        },
        modes: {
          push: {
            quantity: 4,
          },
          repulse: {
            distance: 200,
            duration: 0.4,
          },
        },
      },
      particles: {
        color: {
          value: '#ffffff',
        },
        links: {
          color: '#ffffff',
          distance: 150,
          enable: true,
          opacity: 0.5,
          width: 1,
        },
        move: {
          direction: 'none',
          enable: true,
          outModes: {
            default: 'out',
          },
          random: false,
          speed: 6,
          straight: false,
        },
        number: {
          density: {
            enable: true,
          },
          value: 80,
        },
        opacity: {
          value: 0.5,
        },
        shape: {
          type: 'circle',
        },
        size: {
          value: { min: 1, max: 5 },
        },
      },
      detectRetina: true,
    }),
    []
  );
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
`tsparticles-slim` is not compatible with v3, use `@tsparticles/slim` instead. Check also that all packages are 3.0.x and not 2.12.0. All `tsparticles-` packages are deprecated, they have a `@tsparticles/` name, except `tsparticles` which is the only one with both version.
