### ISSUE TITLE
Help me, display the particles in only one area and wherever the hover goes, it will follow.

### ISSUE THREAD

**Issue by tieucoctu** [tsparticles/tsparticles#5283]
### What is your request?

display the particles in only one area and wherever the hover goes, it will follow.
![Screenshot 2024-01-03 174245](https://github.com/tsparticles/tsparticles/assets/88695612/ab21cd80-a35e-4e6a-bb4d-73b3b315996c)

### tsParticles Version

v-3.0.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
https://github.com/tsparticles/tsparticles/blob/main/utils/configs/src/m/mouseFollow.ts this should be something similar to what you asked

**Comment by matteobruni** [comment]
Closing this since it's not an issue, please open a discussion if further help is needed.

**Comment by tieucoctu** [comment]
thanks
