### ISSUE TITLE
[Bug]: Class extends value undefined is not a constructor or null

### ISSUE THREAD

**Issue by humanusdeus** [tsparticles/tsparticles#5305]
### What happened?

I cant get tsParticles to work on any environment, I was building a project just using vite and typescript when I started getting this error "Class extends value undefined is not a constructor or null", after hours of debugging with the bundler I decided to switch to Astro for an easier implementation but I get the same output. Im not running any extra code, I create a new astro project and copy paste the example. It doesnt work with neither Bun or Node.

### tsParticles Version

3.2.1

### tsParticles Configuration

```json
const options: ISourceOptions = {
	background: {
		color: "#000"
	},
	fullscreen: {
		zIndex: -1
	},
	particles: {
		number: {
			value: 100
		},
		move: {
			enable: true
		}
	}
}
```

### Relevant log output

```shell
Uncaught (in promise) TypeError: Class extends value undefined is not a constructor or null
    at
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
Already known issue, discussed here: https://github.com/tsparticles/vue3/issues/57#issue-2116764096
