### ISSUE TITLE
Canvas position is stuck on fixed

### ISSUE THREAD

**Issue by Drey766** [tsparticles/tsparticles#5321]
### Contact Details

andrewkimani766@gmail.com

### What do you need?

The position of the canvas is stuck on fixed. I wanted to use the particles canvas on a single div in my website but it's stuck on the entire document. The canvas has a position: fixed! important style that cannot be overwritten. I've tried changing it using position: relative !important in the style prop and in a css file that but nothing worked. I even tried changing it using useRef but still nothing. How can I change the position of the canvas? 

### tsParticles Version

3.0.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
https://github.com/tsparticles/tsparticles/issues/5319#issuecomment-1994577498
