### ISSUE TITLE
[Bug]: 'z-index' is not work

### ISSUE THREAD

**Issue by AlaJ97** [tsparticles/tsparticles#5322]
### Contact Details

ala.jaber@taqneensoft.com

### What happened?

static particlesOptions = {
    style:{
        zIndex: '10'
    },
}
The property zIndex does not work. However, if I replace it with 'z-index', it works.

### tsParticles Version

3.0.0

### tsParticles Configuration

```json
static particlesOptions = {
    style:{
        zIndex: '10'
    },
}
```

### What browsers are you seeing the problem on?

Microsoft Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
https://github.com/tsparticles/tsparticles/issues/5319#issuecomment-1994577498
