### ISSUE TITLE
[Bug]:   The package particles.js can't be installed with tsparticles, since it can lead to unexpected behaviors, please uninstall particles.js and remove it from the package.json file.

### ISSUE THREAD

**Issue by CodeHare** [tsparticles/tsparticles#5331]
### Contact Details

coder_bqr@163.com

### What happened?

**node version Node.js v21.7.2 、node version Node.js v14.21.3、node version Node.js v18.20.1 and v16 etc.**

When installing dependencies for my project There have always been the following errors: 

`error /Users/xxx/node_modules/tsparticles: Command failed.
Exit code: 1
Command: node ./scripts/install.js
Arguments: 
Directory: /Users/xxx/node_modules/tsparticles
Output:
Thank you for installing tsParticles.
Remember to checkout the official website https://particles.js.org to explore some samples.
You can find more samples on CodePen too: https://codepen.io/collection/DPOage
If you need documentation you can find it here: https://particles.js.org
Remember to leave a star on the tsParticles repository if you like the project and want to support it: https://github.com/matteobruni/tsparticles
The package particles.js can't be installed with tsparticles, since it can lead to unexpected behaviors, please uninstall particles.js and remove it from the package.json file.
/Users/xxx/node_modules/tsparticles/scripts/install.js:101
        throw error;
        ^

Error: react-particles-js-found
    at Object.<anonymous> (/Users/xxx/node_modules/tsparticles/scripts/install.js:27:15)
    at Module._compile (node:internal/modules/cjs/loader:1368:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1426:10)
    at Module.load (node:internal/modules/cjs/loader:1205:32)
    at Module._load (node:internal/modules/cjs/loader:1021:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:142:12)`

### tsParticles Version

1.29.2

### tsParticles Configuration

```json
-
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
The title is self explaining. Not a bug.
