### ISSUE TITLE
[Bug]: autoprefixer Gradient outdated syntax Warning ( Tailwind )

### ISSUE THREAD

**Issue by taymakz** [tsparticles/tsparticles#5333]
### What happened?

./public/assets/css/tailwind.css.webpack[javascript/auto]!=!./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[11].oneOf[12].use[2]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[11].oneOf[12].use[3]!./public/assets/css/tailwind.css
Warning

(3:1) autoprefixer: Gradient has outdated direction syntax. New syntax is like `closest-side at 0 0` instead of `0 0, closest-side`.

### tsParticles Version

@tsparticles/react": "^3.0.0", @tsparticles/slim": "^3.3.0

### tsParticles Configuration

```json
const defaultOptions = {
    background: {
      color: {
        value: background,
      },
    },
    fullScreen: {
      enable: false,
      zIndex: 1,
    },
    fpsLimit: 120,
    particles: {
      color: {
        value: color,
      },
      move: {
        enable: true,
        direction: "none" as const,
        speed: {
          min: minSpeed || speed / 10,
          max: speed,
        },
        straight: false,
      },
      number: {
        value: density,
      },
      opacity: {
        value: {
          min: minOpacity || opacity / 10,
          max: opacity,
        },
        animation: {
          enable: true,
          sync: false,
          speed: opacitySpeed,
        },
      },
      size: {
        value: {
          min: minSize || size / 2.5,
          max: size,
        },
      },
    },
    detectRetina: true,
  }
```

### Relevant log output

```shell
./public/assets/css/tailwind.css.webpack[javascript/auto]!=!./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[11].oneOf[12].use[2]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[11].oneOf[12].use[3]!./public/assets/css/tailwind.css
Warning

(3:1) autoprefixer: Gradient has outdated direction syntax. New syntax is like `closest-side at 0 0` instead of `0 0, closest-side`.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
Not a bug here, Tailwind or `closest-side` used. I think it's something on your side. 

```
      color: {
        value: background,
      },
```

This variable is missing too, but maybe that's the point where you are having issues.

**Comment by taymakz** [comment]
> Not a bug here, Tailwind or `closest-side` used. I think it's something on your side.
> 
> ```
>       color: {
>         value: background,
>       },
> ```
> 
> This variable is missing too, but maybe that's the point where you are having issues.

i used these config 
https://lunarui.dev/components/react/feature-blocks/sparkles

**Comment by matteobruni** [comment]
I still don't see anything related to the error. Particles works using JavaScript canvas, no gradient CSS is used unless set by options. The issue seems to be somewhere else.
