### ISSUE TITLE
[Bug]: Confetti flat option is not passed to new calls

### ISSUE THREAD

**Issue by andela9** [tsparticles/tsparticles#5338]
### What happened?

When you use multiple confetti calls, only one flat option value is used. 

Can we add rotate, tilt, roll and wobble in [setConfetti addEmitter](https://github.com/tsparticles/tsparticles/blob/ec9599d8398efb64bbc88631a4d6b89516e19ca8/bundles/confetti/src/confetti.ts#L161)?

### tsParticles Version

@tsparticles/confetti 3.3.0

### tsParticles Configuration

```json
confetti({
  shapes: ["circle", "square"],
  flat: false,
 });

confetti({
  shapes: ["circle", "square"],
  flat: true,
 });
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by andela9** [comment]
Thank you for the quick fix! When will v3 be released?

**Comment by matteobruni** [comment]
> Thank you for the quick fix! When will v3 be released?

I need to do more tests, maybe 1-2 weeks
