### ISSUE TITLE
tsparticle package not working on react vite project

### ISSUE THREAD

**Issue by ahmedrazabaloch** [tsparticles/tsparticles#5364]
### Contact Details

ahmed.raza1054@gmail.com

### What do you need?

I need help! When I'm using the tsparticles package in my React Vite project, it doesn't work.

### tsParticles Version

    "react-tsparticles": "^2.12.2",

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
This seems invalid here, please open an issue in the [React repository](https://github.com/tsparticles/react) or check if there are similar issues there.
