### ISSUE TITLE
[Bug]: Particles stop rendering when add emitters 

### ISSUE THREAD

**Issue by ericklv** [tsparticles/tsparticles#5371]
### What happened?

The particles work correctly without using emitters, they are constantly generated. When I add emitters, the particles are generated only once, the emitters keep repeating but the particles are not generated again.
<img width="1569" alt="Screenshot 2024-07-11 at 11 33 19 PM" src="https://github.com/user-attachments/assets/6d298551-f3d9-4d7f-88ef-90f7e31c9bed">

[test.json](https://github.com/user-attachments/files/16188704/test.json)

I am using ts-particles for react 

import Particles, { initParticlesEngine } from "@tsparticles/react";
import { type Container } from "@tsparticles/engine";
import { loadFull } from "tsparticles";

...

### tsParticles Version

3.0.0

### tsParticles Configuration

```json
useEffect(() => {
        if (co["ts-particles"]) {
            initParticlesEngine(async (engine) => { await loadFull(engine); });
        }
    }, []);

    const particlesLoaded = async (c?: Container): Promise<void> => {c};

    const options: any = useMemo(() => (config), [],);

    return (co["ts-particles"]) ?
        <Particles
            id="tsparticles"
            particlesLoaded={particlesLoaded}
            options={options}
        /> : <></>;
```

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

### Relevant log output

```shell
-
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
I'm already investigating this issue, It's a bug introduced with tsParticles 3.2.0, using 3.1.0 works as expected. You can try downgrading the library as a workaround.
