### ISSUE TITLE
[Bug]: zIndex has no effect in confetti

### ISSUE THREAD

**Issue by BeLi4L** [tsparticles/tsparticles#5375]
## Current behavior

I am using `@tsparticles/confetti` and as the docs says, I passed a custom zIndex to the `confetti` function, but the z-index does NOT appear in the DOM.

```ts
import { confetti } from '@tsparticles/confetti'

confetti({
  zIndex: 1234
})
```

## Expected behavior

I expect to see a `z-index` in the DOM (on the canvas I guess).

## Potential solution

I guess it should be added here in `getDomContainer()`: https://github.com/tsparticles/tsparticles/blob/main/engine/src/Core/Engine.ts#L157 ?

### tsParticles Version

3.5.0

### tsParticles Configuration

```json
{ zIndex: 1234 }
```

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
Yep, something broke between 3.1.0 and newer versions. The `z-index` style should be applied to the `<canvas>` element, but I can't find it after 3.1.0. This is a @tsparticles/engine bug, not related to @tsparticles/confetti. You can try using 3.1.0 as a workaround.

**Comment by matteobruni** [comment]
3.6.0-beta.0 should fix this, let me know if it works
