### ISSUE TITLE
[Bug]: tsParticles sound stills plays when the sounds property is set to false in Fireworks option

### ISSUE THREAD

**Issue by rishabhgist** [tsparticles/tsparticles#5411]
### Contact Details

damyrachit@gmail.com

### What happened?

tsParticles sound stills plays when the sounds property is set to false in Fireworks option
i am using 

### tsParticles Version

3.0.0

### tsParticles Configuration

```json
import { tsParticles } from "@tsparticles/engine";
import { loadFireworksPreset } from "@tsparticles/preset-fireworks";

const loadFireworks = async () => {
  await loadFireworksPreset(tsParticles);

  await tsParticles.load({
    id: "tsparticles",
    options: {
      preset: "fireworks",
      background: { color: "#0000" },
      sounds: false,
    },
  });
};
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rishabhgist** [comment]
i am using these versions 

@tsparticles/engine: ^3.5.0,
@tsparticles/preset-fireworks: ^3.1.0,
@tsparticles/react: ^3.0.0,

**Comment by matteobruni** [comment]
Have you tried this?

```
sounds: { enable: false }
```
