### ISSUE TITLE
Generic Issue - Changing colors while toggling

### ISSUE THREAD

**Issue by JHeroGR** [tsparticles/tsparticles#5418]
### Contact Details

jheroytc@gmail.com

### What do you need?

I am attempting to make a toggle dark mode functionality with the tsparticles, but when I try toggling between dark and light, the background works, but the particles don't change color.

e.g.

white background with dark particles - toggle light mode
black background with white particles - toggle dark mode

I am trying to do this on VueJS, but I can't seem to get it to work. Been trying to do this for the past 3 days already, and I'm not sure what other method I can do.

Methods already tried:
- separate components
- separate config files
- hardcoded boolean properties
- chatgpt suggestions

if anyone's experienced something like this, please let me know. 

I am on a Vue3 project.

### tsParticles Version

latest

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
https://codepen.io/matteobruni/pen/rNeOaWP

Theming is already supported by tsParticles, check this sample, the container in Vue is retrieved by the `particlesLoaded` attribute.

**Comment by JHeroGR** [comment]
I am having an issue with the 'load' property:

`Cannot read properties of undefined (reading 'load') 
TypeError: Cannot read properties of undefined (reading 'load')`

Here is the code i tried...

>  import { tsParticles } from "tsparticles";
>   
>   export default {
>     data() {
>       return {
>         particlesInstance: null, // Holds the tsParticles instance
>       };
>     },
>     methods: {
>       async initParticles() {
>         this.particlesInstance = await tsParticles.load("tsparticles", {
>           themes: [
>             {
>               name: "light",
>               default: { value: true, mode: "light" },
>               options: {
>                 background: { color: "#ffffff" },
>                 particles: { color: { value: ["#000000", "#0000ff"] } },
>               },
>             },

**Comment by matteobruni** [comment]
`tsParticles` is exported by `@tsparticles/engine` package

**Comment by JHeroGR** [comment]
i tried a different approach, and copied your sample and translated it to vue3 for a component to see if it worked, its giving me a weird error now: `TypeError: (0 , tsparticles__WEBPACK_IMPORTED_MODULE_0__.default) is not a function`

Here's the component script, i don't know what else i'm doing wrong: 

~~~
<template>
    <!-- tsParticles container -->
    <div id="tsparticles"></div>
    <div id="theme-buttons">
      <div class="row">
        <div class="col text-center">
          <h4>Themes</h4>
          <h6>Try changing the device theme and reload the page</h6>
        </div>
      </div>
      <div class="row">
        <div class="col">
          <button type="button" class="btn btn-block btn-light" id="light">Light</button>
        </div>
        <div class="col">
          <button type="button" class="btn btn-block btn-dark" id="dark">Dark</button>
        </div>
      </div>
    </div>
  </template>
  
  <script>
  import loadFull from 'tsparticles';
  import { tsParticles } from "@tsparticles/engine"; // Ensure you're importing the correct library
  
  export default {
    name: "ParticlesComponent",
    data() {
      return {
        themeableContainer: null, // Holds the tsParticles instance
      };
    },
    async mounted() {
      // Load tsParticles options
      await loadFull(tsParticles);
      this.themeableContainer = await tsParticles.load("tsparticles", this.getParticleOptions());
  
      // Initialize theme buttons
      document.querySelector("#light").addEventListener("click", () => {
        this.themeableContainer.loadTheme("light");
      });
      document.querySelector("#dark").addEventListener("click", () => {
        this.themeableContainer.loadTheme("dark");
      });
    },
    methods: {
      getParticleOptions() {
        // Extracted particle options for readability
        return {
          id: "tsparticles",
          options: {
            themes: [
              {
                name: "light",
                options: {
                  background: { color: "#ffffff" },
                  particles: { color: { value: ["#000000", "#0000ff"] } },
                },
              },
              {
                name: "dark",
                options: {
                  background: { color: "#000000" },
                  particles: { color: { value: ["#ffffff", "#ff0000"] } },
                },
              },
            ],
            particles: {
              color: { value: "#fff" },
              number: { value: 30, density: { enable: true } },
              shape: { type: ["circle", "square"] },
              opacity: { value: 1 },
              size: { value: { min: 15, max: 30 } },
              rotate: {
                value: 0,
                direction: "random",
                animation: { speed: 5, enable: true },
              },
              move: { enable: true, speed: 6, direction: "none", outModes: "out" },
            },
            interactivity: {
              events: {
                onHover: { enable: true, mode: "repulse" },
                onClick: { enable: true, mode: "push" },
              },
            },
          },
        };
      },
    },
  };
  </script>
  
  <style>
  /* Add your custom styles */
  </style>
  ~~~

**Comment by matteobruni** [comment]
It is `import { loadFull } from "tsparticles";` not `import loadFull from "tsparticles";`

**Comment by JHeroGR** [comment]
I managed to fix my particles toggle... it was a lot of json work, but I managed to make it work, not the best way, but it works :)
