### ISSUE TITLE
[Bug]: Particles still appearing without control

### ISSUE THREAD

**Issue by CesarV404** [tsparticles/tsparticles#5430]
### Contact Details

rawrcesar13@gmail.com

### What happened?

I was looking for a solution, but i give up, i start my number of particles in 5, but, when i just move the scroll or i just get afk, the particles keep increasing. 

This image is when i open the page,
![how-starts](https://github.com/user-attachments/assets/38fcd137-ec54-4b98-84d6-ade8eb787855)

But, after a minutes, this happens:
![how-finish](https://github.com/user-attachments/assets/4369326a-7452-4162-987f-6bf76e51ee5e)

I really don't know what i'm doing wrong, thanks for your time. 

### tsParticles Version

@tsparticles/react: ^3.0.0  @tsparticles/slim: ^3.5.0

### tsParticles Configuration

```json
const options: ISourceOptions = useMemo(
    () => ({
      background: {
        color: {
          value: "#111",
        },
      },
      fullScreen: false,
      fpsLimit: 120,
      interactivity: {
        events: {
          onClick: {
            enable: true,
            mode: "push",
          },
          onHover: {
            enable: true,
            mode: "repulse",
          },
        },
        modes: {
          push: {
            quantity: 3,
          },
          repulse: {
            distance: 100,
            duration: 0.4,
          },
        },
      },
      particles: {
        color: {
          value: "#ffffff",
        },
        links: {
          color: "#ffffff",
          distance: 200,
          enable: true,
          opacity: 0.5,
          width: 1,
        },
        move: {
          direction: MoveDirection.none,
          enable: true,
          outModes: {
            default: OutMode.out,
          },
          random: false,
          speed: 1.2,
          straight: false,
        },
        number: {
          density: {
            enable: false,
          },
          value: 5,
        },
        opacity: {
          value: 0.5,
        },
        shape: {
          type: "circle",
        },
        size: {
          value: { min: 1, max: 5 },
        },
      }
    }),
    [],
  );
```

### What browsers are you seeing the problem on?

Firefox, Microsoft Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
Can you update `@tsparticles/slim` to 3.6.0 and let me know if the problem is fixed? Otherwise please provide a full sample with the issue

**Comment by CesarV404** [comment]
I had some problems updating but i did it, and still the problem,  but i found the reason, i know why particles appear just using the scroll. It's because the component detect the clicks out of its canvas box. So, when i click in some place of the page, appear more particles. Do u need that i upload my page to reply the problem? Give me some time i didnt uploaded my page to any host. Thanks for your reply

**Comment by matteobruni** [comment]
> I had some problems updating but i did it, and still the problem, but i found the reason, i know why particles appear just using the scroll. It's because the component detect the clicks out of its canvas box. So, when i click in some place of the page, appear more particles. Do u need that i upload my page to reply the problem? Give me some time i didnt uploaded my page to any host. Thanks for your reply

No if you already found the issue no need to send a sample. The default value for `interactivity.detectsOn` is `window` because it has the best behavior, but since you don't need it, you can use `canvas` instead, this detects clicks only inside the canvas and not in the whole window.

**Comment by CesarV404** [comment]
thank you so much, sorry i didn't know
