### ISSUE TITLE
Port from 3.3.0

### ISSUE THREAD

**Issue by om3ga6400** [tsparticles/tsparticles#5438]
### What do you need?

How would I port this:

`particles: {
    size: {
      value: 1,
    },
    line_linked: {
      enable: true,
    },
    move: {
      enable: true,
      speed: 1.5,
    },
  },
});`

to the latest version

### tsParticles Version

2.8.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
The only problem I see is `line_linked` that was replaced by `links`

**Comment by om3ga6400** [comment]
just did that but when I still see nothing when I change from 2.8.0 to 3.7.1

![image](https://github.com/user-attachments/assets/28e03f42-0879-4045-b098-f0d750a0303e)
v3

![image](https://github.com/user-attachments/assets/f7319126-12e1-4b74-93eb-6840a603f2cf)
v2

**Comment by matteobruni** [comment]
Please provide the full code

**Comment by om3ga6400** [comment]
[https://github.com/om3ga6400/om3ga6400.github.io/tree/dev](https://github.com/om3ga6400/om3ga6400.github.io/tree/dev)

**Comment by matteobruni** [comment]
This is the problem:

https://github.com/om3ga6400/om3ga6400.github.io/blob/5089bbaa318bbf74ef4326af571e3866bc38afa0/js/app.js#L1

Because APIs were changed in 3.x, as you can see in the README here:

https://github.com/tsparticles/tsparticles/tree/main/engine#usage

**Comment by om3ga6400** [comment]
now I can only go up to 3.3.0

**Comment by matteobruni** [comment]
https://github.com/tsparticles/tsparticles/tree/main/bundles/full#usage

Check the readme of the package you are using, you need to load the bundle before calling the `load` function

**Comment by om3ga6400** [comment]
thank you
