### ISSUE TITLE
New GitHub Pages website

### ISSUE THREAD

**Issue by matteobruni** [tsparticles/tsparticles#752]
The current Github Page is just the readme, but creating a cool website with samples and guides would be awesome.
The documentation created by TypeDoc inside the `core\main` folder could be included too.

The website architecture could be done with everything, I don't care about it. Angular, React, Vue.js, plain HTML is all good, the only requirement is it must work fine, and obviously **tsParticles** must be used to create particles effects.

If ideas are needed you can check out the CodePen collection actively updated with tsParticles configurations: http://codepen.io/collection/DPOage

The website will be hosted at https://particles.js.org (as you can see it's really bad), this is the documentation created by TypeDoc https://particles.js.org/core/main/docs/ but it has issues with Jekill because filenames start with the underscore.

The website will be created inside the new `website` branch and deployed to `gh-pages` branch with the build output files.
The branch `gh-pages` has no `.gitignore` for `docs/` folder, while others have, this behavior must be kept.

The branches tree should be:
```
website
`- master
   `- gh-pages
```

If this tree can lead to problems we can discuss about it

**Comment by matteobruni** [comment]
I've updated the TypeDoc scripts to solve the #773 issue in the #775 PR, it deploys to the `gh-pages` branch the TypeDoc generated files, probably the simplest way is to customize the theme instead of a new website

**Comment by matteobruni** [comment]
The TypeDoc theme used is this: https://github.com/tsparticles/typedoc-particles-theme

**Comment by Waterstraal** [comment]
Just a heads up: The demo's listed in the [README](https://github.com/matteobruni/tsparticles/blob/master/README.md) are not working. For example https://particles.matteobruni.it/#polygonMask does not show a Polygon Mask example.

**Comment by matteobruni** [comment]
Thanks I forgot to update them, it’s missing the Samples folder.

Those links should be https://particles.matteobruni.it/Samples/#polygonMask
