### ISSUE TITLE
Connected dots that only move slightly out of place and clickable elements

### ISSUE THREAD

**Issue by Waterstraal** [tsparticles/tsparticles#797]
Is it possible to create the image below using this library? Here the dots should be connected and move slightly and slowly. And the "i"s should be clickable and open an overlay with extra info if possible:

![connected-dots](https://user-images.githubusercontent.com/2691730/92449620-9c7efb00-f1ba-11ea-99e9-e93020c31d16.png)

**Comment by matteobruni** [comment]
Hi @Waterstraal,

Particles moving around their initial position currently are not configurable, they can only vibrate but I don't think this is the feature you're requesting, and it's a nice one that will be implemented as soon as possible.

About the clickable particles there's a global click handler that returns the particles in the clicked position.

You can see more details on issue #450 about the click handling
