### ISSUE TITLE
Help undestanding particles.number 

### ISSUE THREAD

**Issue by hidarikani** [tsparticles/tsparticles#810]
Since I can't find docs for `particles.number` I've tried experimenting with the [demo editor](https://particles.matteobruni.it/Samples#default) to figure out the settings. I've enabled the "More" > "Toggle Stats" option to see the current particle number. Unfortunately I still can't seem to understand the config options.

Why does the following config render 18 particles on the screen (according to the stats box)? My expectation is 10 rendered particles.
```
"number": {
  "density": {
	"enable": false,
	"area": 800,
	"factor": 1000
  },
  "limit": 0,
  "value": 10
}
```

![image](https://user-images.githubusercontent.com/19387605/92720176-e90a3800-f36c-11ea-875a-6596c1cee9f4.png)

Why does the following config render 2 particles on the screen (according to the stats box)? My expectation is 1 rendered particle.

```
"number": {
  "density": {
	"enable": false,
	"area": 800,
	"factor": 1000
  },
  "limit": 1,
  "value": 10
}
```

What is the unit of `density.area`. Is it the number of particles per 800x800 pixels?
What does the `density.factor` mean?

**Comment by matteobruni** [comment]
Hi @hidarikani,

Those values are used in the formula used [here](https://github.com/matteobruni/tsparticles/blob/8460dd210fe4ba69d597052684549a31644a6d6c/core/main/src/Core/Container.ts#L387)

```javascript
this.density = (canvas.width * canvas.height) / (densityOptions.factor * pxRatio * densityOptions.area);

// this.density will be multiplied with the particles.number value
```

This formula is inherited from particles.js changing a hard coded value with a customizable `factor`.

Disabling the `density` should use only the `value` for the count, if it’s not it’s a bug I need to investigate
