### ISSUE TITLE
Is there no option for dynamic opacity of the links proportional to its length? 

### ISSUE THREAD

**Issue by microraptor** [tsparticles/tsparticles#831]
**Is your feature request related to a problem? Please describe.**
I would like to make the links between particles have less opacity the longer they are. Particles.js behaves this way and it looks pretty good in my opinion.

**Describe the solution you'd like**
A suboption for the opacity of links

**Additional context**
I did this net in particles.js and it would be awesome if tsparticles could do that too:
![image](https://user-images.githubusercontent.com/15663536/93651675-92f35f80-fa12-11ea-8186-96c131312930.png)

**Comment by microraptor** [comment]
Maybe random opacity for links would look good as well.

**Comment by matteobruni** [comment]
Links opacity uses the same particles.js formula, is calculated using distance and the value set in options is the maximum opacity

**Comment by microraptor** [comment]
Then there might be a bug.
This is what it looks like for me on Chrome and Firefox using tsParticles:
![image](https://user-images.githubusercontent.com/15663536/93653692-4b70d180-fa1a-11ea-8f58-7288802df1be.png)
https://codepen.io/microraptor-the-sans/pen/MWyPojK

This is what it looks like for me on Chrome and Firefox using particles.js:
![image](https://user-images.githubusercontent.com/15663536/93654164-78be7f00-fa1c-11ea-9442-a3bca4687224.png)
https://codepen.io/microraptor-the-sans/pen/BaKqZRE

The config:

```json
{
  "particles": {
    "number": {
      "value": 150,
      "density": {
        "enable": true,
        "value_area": 800
      }
    },
    "color": {
      "value": "#ffffff"
    },
    "shape": {
      "type": "circle",
      "stroke": {
        "width": 0,
        "color": "#000000"
      },
      "polygon": {
        "nb_sides": 5
      },
      "image": {
        "src": "img/github.svg",
        "width": 100,
        "height": 100
      }
    },
    "opacity": {
      "value": 0.5,
      "random": true,
      "anim": {
        "enable": false,
        "speed": 0.15,
        "opacity_min": 0.1,
        "sync": false
      }
    },
    "size": {
      "value": 3,
      "random": true,
      "anim": {
        "enable": false,
        "speed": 40,
        "size_min": 0.1,
        "sync": false
      }
    },
    "line_linked": {
      "enable": true,
      "distance": 150,
      "color": "#ffffff",
      "opacity": 0.4,
      "width": 1
    },
    "move": {
      "enable": false,
      "speed": 2,
      "direction": "none",
      "random": false,
      "straight": false,
      "out_mode": "out",
      "bounce": false,
      "attract": {
        "enable": false,
        "rotateX": 600,
        "rotateY": 1200
      }
    }
  },
  "interactivity": {
    "detect_on": "window",
    "events": {
      "onhover": {
        "enable": false,
        "mode": "repulse"
      },
      "onclick": {
        "enable": false,
        "mode": "push"
      },
      "resize": true
    },
    "modes": {
      "grab": {
        "distance": 400,
        "line_linked": {
          "opacity": 1
        }
      },
      "bubble": {
        "distance": 400,
        "size": 40,
        "duration": 2,
        "opacity": 8,
        "speed": 3
      },
      "repulse": {
        "distance": 120,
        "duration": 0.4
      },
      "push": {
        "particles_nb": 4
      },
      "remove": {
        "particles_nb": 2
      }
    }
  },
  "retina_detect": true
}
```

**Comment by microraptor** [comment]
I run Ubuntu and also none of the tsParticles sample configs have links with different opacity for me on both machines. It is the same on all browsers on my Android, although particles.js doesn't show up there at all. Under Windows the dynamic opacity works, but the lines don't become quite as transparent as in particles.js.

**Comment by matteobruni** [comment]
Thanks, I’ll have a look on that

**Comment by matteobruni** [comment]
I found a bug in particles being more opaque than set in options. Links are working fine, I double-checked them logging all values from tsParticles and particles.js.
