### ISSUE TITLE
detectRetina breaks dynamic link opacity on HiDPI screens

### ISSUE THREAD

**Issue by microraptor** [tsparticles/tsparticles#837]
Thank you for fixing the random particle opacity of issue #831 . That is some seriously fast support and deployment. However, the problems, that the links still don't look right for me persists.

**Describe the bug**
I have run some tests and the issue is the same on all my OSes. If detectRetina is enabled on a high DPI screen, the dynamic link opacity doesn't work as good anymore and long links loose their transparency. The issue gets worse the higher the OS display scaling is (higher DPI).

**To Reproduce**
See this codepen on a HiDPI device (left side has retina detection disabled and right side has it enabled):
https://codepen.io/microraptor-the-sans/full/abNRwpw

**Expected behavior**
Both sides should look the same, except that the right side with detectRetina should be sharper.

**Screenshots**
This is on a 4K screen with 350% scaling:
![350hdpi](https://user-images.githubusercontent.com/15663536/93670122-0f308600-fa99-11ea-88a2-460252e40459.PNG)

This is on a 4K screen with 200% scaling:
![200dpi](https://user-images.githubusercontent.com/15663536/93670129-22dbec80-fa99-11ea-87df-9bdabf2355e5.PNG)

This is on a 4K screen with 100% scaling:
![100hdpi](https://user-images.githubusercontent.com/15663536/93670120-06d84b00-fa99-11ea-97d4-388ad8a8ed08.PNG)

**Desktop (please complete the following information):**
Windows and Ubuntu with Firefox and Chrome show the same behavior.

**Smartphone (please complete the following information):**
Android 10 with Firefox and Edge shows the same behavior.

**Additional context**
Changing the link width doesn't change the problem. Setting the maximal opacity very low of the links shows up correctly on HiDPI devices, so they are able to show very transparent links.

**Comment by matteobruni** [comment]
Nice catch, I need to do more tests on my Retina Display, I'll have a look at that deeply.

**Comment by microraptor** [comment]
Thanks for the quick fix. Looks amazing now on HiDPI screens! :+1:
