### ISSUE TITLE
Manual Particles

### ISSUE THREAD

**Issue by matteobruni** [tsparticles/tsparticles#839]
tsParticles options should contain a `manual` property with an array of coordinates of initial particles added to the canvas, this could help some fixed layouts that only need node interactions and not random animations

The option should be something like this:

```javascript
manual: [
    {
        x: 0,
        y: 0,
        particles: { /* particles options to override the global options, optional property */ }
    }
]
```

The coordinates should be relative, probably the best solution should be a percent value. So this configuration will work fine on every screen size

**Comment by ahayder** [comment]
Hey @matteobruni I want to do this.

**Comment by matteobruni** [comment]
Hi @ahayder,

Welcome!! Thanks, feel free to fork the repository and add this feature. If you need help or want to share ideas on this feature you can freely join the Slack linked in README.

**Comment by ahayder** [comment]
Ok I will thanks.
