### ISSUE TITLE
Update documentation for 1.18 release

### ISSUE THREAD

**Issue by matteobruni** [tsparticles/tsparticles#857]
The 1.18 version will have new options that need documentation, also the markdown pages listing those options need an update to be aligned with all the new options.

The editor needs some documentation too, how to install and enable it.

If other docs need updates freely report here

**Comment by soophoo** [comment]
it's possible to contribute in this issue ?

**Comment by matteobruni** [comment]
Yes, you can find documentation to update on `dev` branch
