### ISSUE TITLE
Documentation site background is extremely distracting

### ISSUE THREAD

**Issue by joshhunt** [tsparticles/tsparticles#888]
**Describe the bug**
When browsing the documentation website, the background is a highly animated demo of the particle library, with no (obvious) way to disable it. It is extremley distracting and disorientating. 

I first loaded the site and it was a bunch of large coloured blobs, which was irritating. When I navigating to a new page, it had lots of planes constantly moving around which was even worse.

**To Reproduce**
1. Go to https://particles.js.org

**Expected behavior**
The background is not animated

**Screenshots**

![image](https://user-images.githubusercontent.com/46142/94461330-e489b000-01b1-11eb-8b00-f5142e2093a9.png)

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome
 - Version: latest, ish

**Additional context**

I appreciate you're very proud of this library and want to show it off, but while I'm browsing the documentation I'm trying to read technical documentation and the background is oppressively distracting and prevents me from being able to read the site.

I think the background should not be animated. If you absolutely insist that it is (which i strongly disagree with), then there should be an obvious toggle and should honor the `prefers-reduced-motion` media query ([more info on that](https://css-tricks.com/revisiting-prefers-reduced-motion-the-reduced-motion-media-query/))

See this issue from another repo for additional context https://github.com/styled-components/styled-components/issues/3278

Thanks!

**Comment by matteobruni** [comment]
Hi @joshhunt, thanks for the feedback.

I'm already aware of that and it will be updated soon, I'm working to release a 1.18.0 beta and it's really close.
About the `prefers-reduced-motion` I was thinking to implement it directly in the library and not in the typedoc theme, but for now can be a nice workaround.

The theme repository is here: https://github.com/tsparticles/typedoc-particles-theme

EDIT: I forgot I already have an issue there: https://github.com/tsparticles/typedoc-particles-theme/issues/1
