### ISSUE TITLE
Localized READMEs and documentation

### ISSUE THREAD

**Issue by matteobruni** [tsparticles/tsparticles#895]
This project documentation can be improved localizing it in multiple languages so it can be clearer to new users or for those who can't read/speak English how to use the library and all its features.

READMEs could be localized too for the same reason.

I can only contribute to English and Italian, any other language is welcome.

**Comment by lordvins226** [comment]
I want to contribute for the French language.

**Comment by matteobruni** [comment]
Hi @lordvins226,

Welcome and feel free to contribute, I don't have thought a file structure for localizations for now but if you have some good ideas I'm open to consider them.

If you need any help with the existing documentation or READMEs feel free to ask here on in Slack

**Comment by lordvins226** [comment]
We can create a folder named Lang or traduction and use this style ``README.fr.md`` for files

> Hi @lordvins226,
> 
> Welcome and feel free to contribute, I don't have thought a file structure for localizations for now but if you have some good ideas I'm open to consider them.
> 
> If you need any help with the existing documentation or READMEs feel free to ask here on in Slack

We can create a folder named Lang or traduction and use this style ``README.fr.md`` for files

**Comment by matteobruni** [comment]
Looks good to me

**Comment by baptixta** [comment]
Hi @matteobruni , I can contribute for the Portuguese language.

**Comment by matteobruni** [comment]
Hi @baptixta, welcome.

Yes feel free to contribute, follow the guidelines reported above by @lordvins226 so it's easier to merge all the files.

**Comment by baptixta** [comment]
@lordvins226 are you going to name the folder Lang or traduction?

**Comment by lordvins226** [comment]
Traduction. it's good?

**Comment by lordvins226** [comment]
> @lordvins226 are you going to name the folder Lang or traduction?

Traduction. it's good?

**Comment by baptixta** [comment]
@lordvins226 great, thank you.

**Comment by baptixta** [comment]
@matteobruni just sent the pull request on the dev branch with the portuguese translation :)

**Comment by matteobruni** [comment]
Thank you @baptixta,

If you want there are other READMEs located inside `components` and `core` subfolders. `presets` and `shapes` have other READMEs too but they're not much used or read.

Other documentation to be translated is located under `core/main/markdown`

**Comment by Winner95** [comment]
Hi @matteobruni ,

It is a great library!

I would like to provide translation in Russian, if you don’t mind?

**Comment by matteobruni** [comment]
Hi @Winner95 welcome,

Yes, a Russian translation is welcome.

Please follow the guidelines reported above

**Comment by gaurang7goel** [comment]
Hey @matteobruni .
I would like to provide translation in HIndi, if you don’t mind.

**Comment by matteobruni** [comment]
Hi @gaurang7goel welcome,

Yes, feel free to add it

**Comment by matteobruni** [comment]
I need to clarify a thing for everyone working on translations since I got some single file PRs:

This project has many README.md files, not just the root one and in `core/main/markdown` there are more documentation pages.

It's preferred to translate all those files instead of the root README.md. Users will be grateful for that since they won't need to read any English written file.

Please be more specific about translations: If you just want to translate the root README.md file let everyone know so maybe another user can translate other files too.

**Comment by ankitaugale23** [comment]
Can I work on this? I would like to do it for Hindi translation if it's ok.

**Comment by matteobruni** [comment]
Hi @ankitaugale23 welcome,

Actually @gaurang7goel created a PR (#907) for the main README, if he won't work on other files that also require localizations you could work on them

**Comment by gaurang7goel** [comment]
Sure , not a problem  @ankitaugale23  can work on rest of the files .

**Comment by gaurang7goel** [comment]
Sir @matteobruni  you can assign it to her, and also  pls look over my PR too.

**Comment by jpyamamoto** [comment]
Hello.
Cool project.
Can I be in charge of adding the Spanish translation?
Thanks

**Comment by matteobruni** [comment]
Hi @JPYamamoto welcome,

Sure, it’s missing for now so it’s yours

**Comment by RVxLab** [comment]
I can contribute Dutch if you’d like.

**Comment by matteobruni** [comment]
Hi @RVxLab sure, it’s all yours

**Comment by yunffee** [comment]
hi @matteobruni , can i add Indonesia translation?
Thanks.

**Comment by matteobruni** [comment]
Hi @yuandahanif, sure feel free to add it

**Comment by MicheleMarschner** [comment]
Hi @matteobruni. I could work on the German translation?

**Comment by matteobruni** [comment]
Hi @MicheleMarschner, sure it's all yours

**Comment by dBiazioli** [comment]
Is anyone working on a Brazilian Portuguese translation? If not, I'll be happy to do it.

**Comment by codefunlearn** [comment]
HI @matteobruni . I can do the Swedish version. Can you assign it to me?
One question: I see only the READMEs done in the _traduction_ folder . Is this the only document to translate?  
thanks

**Comment by matteobruni** [comment]
Hi @codefunlearn,

You are free to do it, there are many traduction folders, there are many READMEs that you can find in every subfolder. The `demo` folder can be ignored.

There are also some markdown files inside `core/main/markdown` if you want to translate them too
