### ISSUE TITLE
Adding More Tests

### ISSUE THREAD

**Issue by matteobruni** [tsparticles/tsparticles#896]
The main library has some tests that were added a few months ago and they can be improved with new tests or tests that can be added to components and editor too.

I'd like to cover more code so testing would be easier.

Actually the project uses Mocha, Chai, and Instanbul together.

If you prefer using another suite for a specific component we can discuss it in Slack

**Comment by sadn1ck** [comment]
Hey! I'm pretty new to testing, but I'd like to work on this!

**Comment by matteobruni** [comment]
Hi @sadn1ck, welcome, and feel free to start on this issue.

If you need help you can ask here or on Slack

**Comment by Prasad-Chaudhari** [comment]
Do you mind you if I take up the task???

**Comment by matteobruni** [comment]
Hi @Prasad-Chaudhari welcome,

Actually @sadn1ck said he'll work on that, you can cooperate if you want. He already joined the project Slack if you want to share the issue.

It's not a problem for me if both of you work on this, it can be a huge activity

**Comment by sadn1ck** [comment]
~~Yep I have no problem, just join slack, we can collab on which tests we add so as not to overlap. @Prasad-Chaudhari~~

~~@matteobruni If you're okay with this :D~~

Have been extremely busy with college, sorry might not be able to work on this! Very sorry!

**Comment by matteobruni** [comment]
It's fine for me
