### ISSUE TITLE
Confusing input option typings for framework components

### ISSUE THREAD

**Issue by Achilles1515** [tsparticles/tsparticles#898]
Many of the framework components are manually constructing the input options object type like so:
 
React:
```ts
import type { RecursivePartial } from "tsparticles/dist/Types/RecursivePartial";

import type { IOptions } from "tsparticles/dist/Options/Interfaces/IOptions";
import type { IPolygonMaskOptions } from "tsparticles/dist/Plugins/PolygonMask/PolygonMaskPlugin";
import type { IAbsorberOptions } from "tsparticles/dist/Plugins/Absorbers/AbsorbersPlugin";
import type { IEmitterOptions } from "tsparticles/dist/Plugins/Emitters/EmittersPlugin";

export interface ParticlesProps {
    // ...
    options: RecursivePartial<IOptions & IPolygonMaskOptions & IAbsorberOptions & IEmitterOptions>;
    // ...
}
```

Angular is defining a new `IParticlesParams` type:
```ts
export type IParticlesParams = RecursivePartial<IOptions & IAbsorberOptions & IEmitterOptions & IPolygonMaskOptions>;
```

[Vue](https://github.com/matteobruni/tsparticles/blob/master/components/vue/src/Particles/Particles.vue) isn't event including the absorber, emitter, and polygon mask options...?

and the `IOptions & IPolygonMaskOptions & IAbsorberOptions & IEmitterOptions` type (without the `RecursivePartial`) already exists in the library:

https://github.com/matteobruni/tsparticles/blob/dbe56a05f72044e9e3fba9809989af9c36747488/core/main/src/Interfaces/Options/IOptions.ts#L1-L6

...so why aren't the frameworks just importing this type to begin with?

* Can a *single* interface in this library be created and exported that is the **definite** type for [default] user input options?
--> Basically, similar to the Angular library `IParticlesParams` type.

The individual components shouldn't need to know or care about this recursive partial business and `and`ing together these different plugin types. All they need is a single, cohesive type exported from the library.

**Comment by matteobruni** [comment]
Hi @Achilles1515, welcome!

Good report, I never thought that! `tsparticles` and `tsparticles.slim` should export all the available options in a single exported type!

This will be included in 1.18.0 release since this is a small effort task.
