### ISSUE TITLE
IntersectionObserver to pause/play animations

### ISSUE THREAD

**Issue by matteobruni** [tsparticles/tsparticles#931]
Particles animation can affect website performance and a good improvement could be detecting if particles container is visible on the screen

I've thought about [Intersection Observer API](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) to check this but some browsers can't use this feature so a check of the API availability is needed.

This could interact with the existing `pauseOnBlur` property (that pauses animations when the window loses its focus) or a new one can be used, personally I prefer the first solution.

**Comment by KolCrooks** [comment]
I could try and do this!

**Comment by KolCrooks** [comment]
I am looking into how I would implement the changes that you are mentioning here. The biggest thing that I am trying to figure out is where to put the intersection observer. It looks like the easiest place is in the EventListeners class but it doesn't feel like it fits there. Do you have an idea of what class you would want it to be implemented in?

**Comment by matteobruni** [comment]
I think EventListeners class could fit, but Container can be a valid alternative

**Comment by KolCrooks** [comment]
Okay I have implemented the IntersectionObserver but I am running into a problem where Mocha doesn't think that it exists. I think the only way to fix this is with mocking but I don't really have a good understanding of how the codebase works. Do you know any potential fixes to this problem?
![image](https://user-images.githubusercontent.com/20110047/95521900-b6b61f80-0998-11eb-8d46-f42a4214da3f.png)

**Comment by matteobruni** [comment]
`mocha` is run by node so many front end utilities are not defined.

I made an utils to check if the request is run in a server environment and you can see a sample here:

https://github.com/matteobruni/tsparticles/blob/06f374637634c7425f9b32c8f1a7bbb370e6903a/core/main/src/Core/Retina.ts#L35

The IntersectionObserver code must be run only if `IsSsr()` returns `false`

**Comment by KolCrooks** [comment]
I'm not sure if i'm not implementing it properly but the fix you mentioned isn't working.
```Typescript
        if (!Utils.isSsr()) {
            console.log("SSR IS FALSE");
            this.intersectionObserver = new IntersectionObserver(this.intersectionManager);

            if (this.interactivity.element instanceof HTMLElement)
                this.intersectionObserver.observe(this.interactivity.element);
        }
```
Output:
![image](https://user-images.githubusercontent.com/20110047/95527419-3c3ecd00-09a3-11eb-9cde-90c95b11291a.png)
As you can see, the line "SSR IS FALSE" is being called.

**Comment by matteobruni** [comment]
Right, mocha has a window workaround, the intersection observer object needs its own checks like for media query, it’s in retina.ts too (v1.18.3)

`if (InteractionObserver)` probably is enough

**Comment by KolCrooks** [comment]
I created a pull request that implements what we have talked about #942. Preview here: 
[![Image](https://i.gyazo.com/cdb61e991bd5e840ced5ac98894fb74a.gif)](https://gyazo.com/cdb61e991bd5e840ced5ac98894fb74a)
