### ISSUE TITLE
TypeError: undefined is not a function error for iOS devices with Retina displays on 1.18.3

### ISSUE THREAD

**Issue by hoonsubin** [tsparticles/tsparticles#947]
**Describe the bug**
The same error that was described in issue https://github.com/matteobruni/tsparticles/issues/84 is still occurring on version `1.18.3`. Desktop (including macOS with Retina display) and Android browsers seem to behave correctly, but iPhone and iPad on both Chrome and Safari will show the error exactly on this line https://github.com/matteobruni/tsparticles/blob/7784898e703dc04ae5b7cf7d69a9fb18baece16c/core/main/src/Core/Retina.ts#L51-L56

**To Reproduce**
1. create a react app that imports `react-tsparticles@1.18.3`
2. copy the particle options from this example https://codepen.io/matteobruni/pen/BaoZBZy
3. start a development server
4. access the development server from an iOS device
5. see the error

**Expected behavior**
The polygon mask particle effect should be correctly displayed

**Screenshots**

![IMG_0607](https://user-images.githubusercontent.com/40356749/95608693-78a02500-0a98-11eb-9719-2d8608b8e7dd.png)
![IMG_0605](https://user-images.githubusercontent.com/40356749/95608703-7c33ac00-0a98-11eb-86ed-3feeb163eb4e.png)
![IMG_0174](https://user-images.githubusercontent.com/40356749/95608705-7ccc4280-0a98-11eb-86c9-a3822e99c4d3.png)

**Smartphone (please complete the following information):**
 - Device: iPhone, iPad
 - OS: iOS 13
 - Browser Safari, Chrome

**Additional context**
As you can see from the screenshot, I have tested from both the template (manually updated the package to be `1.18.3`) app and the website I was working on (made with Gatsby), on the same package version.
I was only able to test this using react.
Additionally, the web application that is deployed on a remote server is showing the same issue as well, albeit with a white blank screen right before the particle load instead of any error messages.

**Comment by hoonsubin** [comment]
okay, I noticed that my iOS device was actually running on iOS 13 and not 14. For some low-level magical reasons, upgrading iOS to 14 fixed this issue for me. I'll close this issue since I think it's been addressed. Thank you for the update.

**Comment by felipefa** [comment]
This problem is still happening for iOS 12 (and lower) devices using `react-tsparticles@1.18.8`.

I was able to bypass the error by wrapping the code from line 24 to 32 of the `Core/Retina.js` file inside a try/catch block, but I'm waiting for a proper fix if possible.

![image](https://user-images.githubusercontent.com/12715851/97919003-d04b4c80-1d35-11eb-97ef-172ad28a80e6.png)

**Comment by matteobruni** [comment]
Found the issue and tested, version `1.18.9` is now with the fix

**Comment by felipefa** [comment]
Thank you for such a quick reply, but after upgrading to version `1.18.9` I'm getting this error.

![image](https://user-images.githubusercontent.com/12715851/97993245-8eb4b300-1dc2-11eb-9f42-4578eaef7023.png)

And also this warnings on the console.
![image](https://user-images.githubusercontent.com/12715851/97993608-10a4dc00-1dc3-11eb-9adb-f5a7c5387916.png)

I even tried deleting the node_modules folder and installing everything again, but no success. Should I open a new issue?

**Comment by matteobruni** [comment]
I'm releasing the version `1.18.10` that could fix this issue, this version will be released very soon, let me know if that version fixes this issue

**Comment by matteobruni** [comment]
`1.18.10` is out, let me know if it works

**Comment by felipefa** [comment]
Yes, it's all working now.

Thank you very much!
