### ISSUE TITLE
Failed to load resource: The file "purify.js.map" could not be loaded

### ISSUE THREAD

**Issue by daggy1234** [tsparticles/tsparticles#952]
**Describe the bug**
On a very small subset of devices, ts Particles raises an error `
```
failed to load resource purify.js.map
```

**To Reproduce**
Website: https://dagpi.xyz
Repo: https://github.com/daggy1234/dagpi-dashboard

**Expected behavior**

**Screenshots**
https://media.discordapp.net/attachments/715744000077725769/765959979487199243/unknown.png?width=1394&height=669

**Desktop (please complete the following information):**
 - OS: MacOs Catalina 10.15.6
 - Browser Safari 13.1.2

For multiple machines

**Smartphone (please complete the following information):**
Works on all smartphones

**Additional context**
Very limited subset of devices specifically MacoS cataline 10.15.6

**Comment by matteobruni** [comment]
That error looks coming from a Safari Extension. Do you have Purify extension installed?

**Comment by daggy1234** [comment]
lemme test

**Comment by daggy1234** [comment]
Uhhh so purify is not a safari extension. This is not working on chrome either.

Some mobile users are also having problems

<img src="https://media.discordapp.net/attachments/715744000077725769/767415865163120691/unknown.png?width=1304&height=670" />

**Comment by matteobruni** [comment]
The error is still coming from the safari-extension scheme in your screenshot, I need more info about the configuration. There's no `purify.js` in the project as you can see [here](https://github.com/matteobruni/tsparticles/search?q=purify)

**Comment by matteobruni** [comment]
@Daggy1234 I got that error in InfernoJS demo project in this repository. It's not an error related to `purify.js.map` but it was an error based on the `webpack serve` command (in my case).

It's probably something caused by a misconfiguration of the output files. I'll have a look at your repository to see if I found the error

**Comment by matteobruni** [comment]
Ok, I found the issue @Daggy1234, Upgrade `react-tsparticles` to the latest version, and the particles will work fine.
There was an issue with high-density particles with collisions enabled before version 1.18.0.
