### ISSUE TITLE
"core" vs "full"?

### ISSUE THREAD

**Issue by mmilano** [tsparticles/tsparticles#953]
Great work on the active development of tsParticles!

Is there any option to import a reduced/smaller, more "core" tsParticles library?
Core in the sense of the fundamental behavior and options.

Something like 
```
import { tsParticlesCore } from "tsparticles";
```
that would provide only the most slimmed down possible functionality, and then could allow 
importing additional aspects if needed (manually)?

Theoretical example of more extensive features...
```
import { tsParticlesCore, tsParticlesShapes, tsParticlesPlugins,  } from "tsparticles";
```
Or support for the entire library if wanted, using the known regular import:
```
import { tsParticles } from "tsparticles";
```

Thanks in advance for thoughts.

**Comment by matteobruni** [comment]
Hi @mmilano,

Actually, there are two builds: `tsparticles.slim` and `tsparticles`.

The `slim` version doesn't have plugins preinstalled (Absorbers, PolygonMask, Emitters), the other build has all features.

If you want a more `slimmer` version you can check out the [`Loader`](https://particles.js.org/classes/_core_loader_.loader.html) class, it's the class that creates all the container and the `tsParticles` object is just a wrapper to it loading shapes and plugins.

That class should be the lightest way to load tsParticles but I'm trying to bring more composability to the project so everyone can load only what is really necessary.

**Comment by carlassmann** [comment]
@matteobruni is the slim build somehow available when using a component framework like React or Preact? I'm using Gatsby and ts-particles (awesome tool) is by far the largest part in my build even though I only use the core features.

**Comment by matteobruni** [comment]
Hi @ccssmnn, actually is not available but I'm working on the 2.x release that will be more customizable.
