### ISSUE TITLE
Syntax Error: Unexpected token { from Try/Catch in install script

### ISSUE THREAD

**Issue by ecrookoh** [tsparticles/tsparticles#966]
The addition of an unbound catch in v1.18.5 193bf0f183f235cd43358c7f3a9251ed19fc998b prevents building when using earlier versions of node. 
Passing the error object to the catch may prevent this error from occurring: `catch(err){}` instead of `catch{}`

**Project Information**
Node: 8.12.0
tsparticles: 1.18.5

I've reverted to a previous version of tsparticles for now. Although I'd like to, I'm unable to update the version of node at this time. Let me know if there is any other information that would be helpful.

**Error from Build**
> tsparticles@1.18.5 install /home/gitlab-runner/builds/t8r7aAZg/0/fe/reactpaxwizard/node_modules/tsparticles
 node ./scripts/install.js
/home/gitlab-runner/builds/t8r7aAZg/0/fe/reactpaxwizard/node_modules/tsparticles/scripts/install.js:82
} catch {
        ^
SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3`

**Comment by matteobruni** [comment]
Thanks for reporting the issue, the fix will be released soon in 1.18.6, you can keep the 1.18.4 for now

**Comment by ecrookoh** [comment]
Thank you for the fix, the new version is working perfectly for me!
