### ISSUE TITLE
Add particles option for "z index" to always draw particles on top of others

### ISSUE THREAD

**Issue by matteobruni** [tsparticles/tsparticles#979]
Particles are now drawn in a random order, a cool option could be something like a `z index` that places particles in a different `plane` of others, drawing them before or after other `z indexes`.

Particles with lower `z indexes` will be drawn first, the others with higher `z index` will be drawn last. The last drawn particles will be on top (particles in the same `z index` will be still randomly drawn).

The `z index` can affect also size, opacity or speed (other options). The lower the `z index` the smaller the particle is, the same for speed and opacity.

We could have some cool configurations from this feature.

**Comment by Pingviinituutti** [comment]
I could tackle this issue/enhancment! One thing though. The `contributing.md` says 

> There's a small demo app inside the repository in the core folder, just run yarn start and go to http://localhost:3000

However, there's no "`start`" command defined in the `package.json` files under the `core/` folder. Is testing supposed to be ran in some of the `demo/` folders? Where should I run `yarn start` as in to see the effect of all my changes? :D Would help to get started a bit faster.

**Comment by matteobruni** [comment]
Hi @Pingviinituutti,

I started working on this issue some days ago, but you can improve it. I did some changes in the `dev` branch but that branch has a different configuration than `master`.

I migrated from `yarn`/`lerna` to `pnpm`/`rush`. You can read more in the `Contributing.md` of the `dev` branch.

The demo app is inside `demo/main` folder, you can `pnpm start` inside that folder after building all the projects with the `rush update && rush build` command.
