### ISSUE TITLE
onHover modes and parallax interact weirdly

### ISSUE THREAD

**Issue by cbossut** [tsparticles/tsparticles#995]
When enabling parallax, it seems to disrupt onHover modes.
Thus far, I tested repulse and trail. Repulse is utterly disabled when parallax is enabled, and trailing particles jet out in the parallax direction.

Also, onHover modes are enabled if parallax is enabled, event if onHover is disabled.

**Comment by matteobruni** [comment]
Hi @cbossut,

Actually, all particles respond to the same interactivity events. This is a configuration that will be changed in the `2.x` version but it won't be out soon.

The `1.19.x` probably will be the latest `1.x` version and will be out earlier than the `2.x`.
