### ISSUE TITLE
parallax is off centered if canvas isn’t the whole screen

### ISSUE THREAD

**Issue by cbossut** [tsparticles/tsparticles#996]
When the canvas is a portion of the window, parallax is off centered.
I think it comes from using window.innerHeight and Width in Movers.moveParallax.
Don’t know if it should rather be canvas by default, or using the interactivity.detectsOn property instead.

**Comment by matteobruni** [comment]
Hi @cbossut,

Thanks for reporting that, I never noticed that, it will be investigated and fixed soon (don't know if in version `1.18.9` or `1.19.0`)
