### ISSUE TITLE
1.18.0 tsparticles.slim.js crashes on load

### ISSUE THREAD

**Issue by cbossut** [tsparticles/tsparticles#999]
tsparticles.slim.js:8263 Uncaught ReferenceError: Cannot access 'main_slim_MainSlim' before initialization
    at Module.5 (tsparticles.slim.js:8263)

Seems the different modules from standard and slim libs are not concatenated in an acceptable order.
Tried changing slightly the concatenation, but I didn’t find a way to make it executable.

**Comment by matteobruni** [comment]
Hi @cbossut,

Are you using the version `1.18.0` or the `1.18.9`? I'm preparing a `1.18.10` for some module errors and this could be fixed too in that version

**Comment by cbossut** [comment]
It happened in `1.18.0`

**Comment by matteobruni** [comment]
> It happened in `1.18.0`

Can you upgrade to latest version and check if the issue is still there?
